force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AdditionalNumber__c.field-meta.xml
<CustomField>
    <fullName>AdditionalNumber__c</fullName>
    <description>Reference number of the opportunity that is used by BO.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference number of the opportunity that is used by BO.</inlineHelpText>
    <label>Additional Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SecondChoice__c.field-meta.xml
<CustomField>
    <fullName>SecondChoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Second Choice (obsolete)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/AdditionalNumber__c.field-meta.xml
<CustomField>
    <fullName>AdditionalNumber__c</fullName>
    <externalId>true</externalId>
    <label>Additional Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DispatchedQuantity__c.field-meta.xml
<CustomField>
    <fullName>DispatchedQuantity__c</fullName>
    <label>Shipped (t)</label>
    <summarizedField>OrderItem.DispatchedQuantity__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.DispatchedQuantity__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsSecondChoice__c.field-meta.xml
<CustomField>
    <fullName>IsSecondChoice__c</fullName>
    <formula>SecondChoiceProductsNumber__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Second Choice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/DispatchedQuantity__c.field-meta.xml
<CustomField>
    <fullName>DispatchedQuantity__c</fullName>
    <description>Dispatched quantity of product in metric tons</description>
    <inlineHelpText>Dispatched quantity of product in metric tons</inlineHelpText>
    <label>Shipped (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/QuotaType__c.field-meta.xml
<CustomField>
    <fullName>QuotaType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop</description>
    <inlineHelpText>Production shop</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed by mill</label>
            </value>
            <value>
                <fullName>Produced</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductionJournalRecord__c/ProductionJournalRecord__c.object-meta.xml
<CustomObject>
    <label>Production Journal Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Journal Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductionJournalRecord__c/fields/DispatchedQuantity__c.field-meta.xml
<CustomField>
    <fullName>DispatchedQuantity__c</fullName>
    <label>Dispatched (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductionJournalRecord__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Production Journal Records</relationshipLabel>
    <relationshipName>Production_Journal_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductionJournalRecord__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Fact</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotaType__c/QuotaType__c.object-meta.xml
<CustomObject>
    <description>Type of quota that is defined by production shop for particular sales manager</description>
    <label>Quota Type</label>
    <nameField>
        <label>Quota Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotas Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotaType__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuotaType__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop that the quota relates to</description>
    <inlineHelpText>Production shop that the quota relates to</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Quotas Types</relationshipLabel>
    <relationshipName>QuotasTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/SalesPlanFact__c.object-meta.xml
<CustomObject>
    <label>Sales Plan and Fact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plan and Fact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanFact__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>Id code of the order item in the ERP system (used only for Plan or Fact record types).</description>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/InitialRecordId__c.field-meta.xml
<CustomField>
    <fullName>InitialRecordId__c</fullName>
    <description>Salesforce Id of the initial record</description>
    <externalId>true</externalId>
    <label>Initial Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/ProductionAmount__c.field-meta.xml
<CustomField>
    <fullName>ProductionAmount__c</fullName>
    <label>Dispatched Amount (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/QuotaType__c.field-meta.xml
<CustomField>
    <fullName>QuotaType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Sales Plan and Fact</relationshipLabel>
    <relationshipName>Sales_Plan_and_Fact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/SecondChoice__c.field-meta.xml
<CustomField>
    <fullName>SecondChoice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Second Choice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Sales Plan and Fact</relationshipLabel>
    <relationshipName>Sales_Plan_and_Fact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Budget</fullName>
                <color>#FFCC33</color>
                <label>Initial Budget</label>
            </value>
            <value>
                <fullName>Corrected Budget</fullName>
                <color>#DDDDDD</color>
                <label>Corrected Budget</label>
            </value>
            <value>
                <fullName>Actual Budget</fullName>
                <color>#78C953</color>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Plan</fullName>
                <color>#AFCADF</color>
                <label>Plan</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <color>#2F5D85</color>
                <label>Open Orders</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <color>#419249</color>
                <label>Open Orders &amp; Opps</label>
            </value>
            <value>
                <fullName>Fact</fullName>
                <color>#2F5D85</color>
                <label>Fact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Fact.recordType-meta.xml
<RecordType>
    <fullName>Fact</fullName>
    <active>true</active>
    <description>Actual production and sales data</description>
    <label>Fact</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <description>Open order</description>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Plan.recordType-meta.xml
<RecordType>
    <fullName>Plan</fullName>
    <active>true</active>
    <description>Production and sales plan data</description>
    <label>Plan</label>
</RecordType>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in ERP system</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in ERP system</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AllocateOrdersToProduction.cls
global class AllocateOrdersToProduction implements Database.Batchable<SObject> {
	
	List<SalesPlanFact__c> spfToInsert = new List<SalesPlanFact__c>();

	//global AllocateOrdersToProduction() {
		
	//}
	
	/**
	 * @description gets invoked when the batch job starts
	 * @param context contains the job ID
	 * @returns the record set as a QueryLocator object that will be batched for execution
	 */ 
	global Database.QueryLocator start(Database.BatchableContext context) {
		
		Date firstDayOfThisMonth = Date.today().toStartOfMonth();
		
		// Выберем все позиции заказов, которые есть в плане этого месяца, чтобы включить их в распределение на текущий месяц даже если они уже перешли в закрытую стадию
		List<SalesPlanFact__c> plannedOI = new List<SalesPlanFact__c> (
			[	SELECT	InitialRecordId__c
				FROM	SalesPlanFact__c
				WHERE	Period__c = :firstDayOfThisMonth
				 AND	Type__c = 'Plan'
				 AND	ProductionAmount__c > 0
			]);
		
		Set<String> plannedOIIdList = ApexUtil.getFieldValues(plannedOI, 'InitialRecordId__c');
		System.debug('----> Planned OI Ids: ' + plannedOIIdList);

		// Выберем все позиции заказов, по которым была отгрузка в этом месяце, чтобы включить их в распределение на текущий месяц даже если они перешли в закрытую стадию
		//List<ProductionJournalRecord__c> producedOI = new List<ProductionJournalRecord__c> (
			//[	SELECT	OrderItem__c
				//FROM	ProductionJournalRecord__c
				//WHERE	Period__c = :firstDayOfThisMonth
				 //AND	Type__c = 'Fact'
				 //AND	DispatchedQuantity__c > 0
			//]);

		//Set<String> producedOIIdList = ApexUtil.getFieldValues(producedOI, 'OrderItem__c');
		//System.debug('----> Planned OI Ids: ' + producedOIIdList);

		return Database.getQueryLocator(
				'	SELECT	Id, ID_ERP__c, Shop__c, QuotaType__c, OrderId, Quantity ' +
				'	FROM	OrderItem ' + 
				'	Where	((Stage__c != \'Dispatched\' And Stage__c != \'Shipped\' And Stage__c != \'Cancelled\' And Order.Status != \'Closed\') ' +
				'				OR Id in :plannedOIIdList) ' +
				'			AND	Quantity >= 2 ' +
				'			AND	Order.IsSecondChoice__c = False' + 
				'			AND	Order.MarketSegment__c = \'00002\'' +
				'			AND	Order.Owner.IsActive = true'
		);
	}

	/**
	 * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
	 * @param context contains the job ID
	 * @param scope contains the batch of records to process.
	 */ 
   	global void execute(Database.BatchableContext context, List<OrderItem> scope) {
		
		// Сформируем необходимые списки, мапы и т.п.
		Set<String> oiIdSet = ApexUtil.getFieldValues(scope, 'Id');
		Set<String> orderIdSet = ApexUtil.getFieldValues(scope, 'OrderId');
		Map<Id, Order> orderMap = new Map<Id, Order>([
			SELECT Id, AdditionalNumber__c, MarketSegment__c, Country__c, AccountId, OwnerId, IsSecondChoice__c
			FROM Order
			WHERE Id in :orderIdSet
		]);
		Map<Id, Map<Date, Decimal>> productionMap = getProductionMap(oiIdSet);
		Map<String, Decimal> budgetMap = getBudgetMap();
		Set<Date> plannedPeriods = getPlannedPeriods();

		System.debug('------->>> Production Map: ' + productionMap);
		System.debug('------->>> Budget Map: ' + budgetMap);

		Map<String, Id> rtNameMap = new Map<String, Id>();
		for (RecordType rt : [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'SalesPlanFact__c']) {
			rtNameMap.put(rt.DeveloperName, rt.Id);
		}

		for (OrderItem oi : scope) {
			createRelatedSPF(oi, productionMap, budgetMap, orderMap, rtNameMap, plannedPeriods);
		}
		System.debug('---->> SPF to insert: ' + spfToInsert);
		insert spfToInsert;
		spfToInsert.clear();
	}
	
	/**
	 * @description gets invoked when the batch job finishes. Place any clean up code in this method.
	 * @param context contains the job ID
	 */ 
	global void finish(Database.BatchableContext context) {
		
	}


	private Set<Date> getPlannedPeriods() {
		
		Set<Date> plannedPeriods = new Set<Date>();

		//Узнаем, по каким периодам есть план, начиная с текущего месяца (за прошлые периоды он должен быть однозначно)
		Date firstDayOfThisMonth = Date.today().toStartOfMonth();
		AggregateResult[] plannedPeriodsInPJR = 
				[	SELECT		Period__c
					FROM		ProductionJournalRecord__c
					WHERE		Type__c = 'Plan'
					 AND		Period__c >= :firstDayOfThisMonth
					GROUP BY	Period__c
				];
		
		for (AggregateResult plan : plannedPeriodsInPJR) {
			plannedPeriods.add((Date)plan.get('Period__c'));
		}

		return plannedPeriods;
	}

	private Map<Id, Map<Date, Decimal>> getProductionMap(Set<String> oiIdSet) {
		Map<Id, Map<Date, Decimal>> productionMap = new Map<Id, Map<Date, Decimal>>();

		Date firstDayOfThisMonth = Date.today().toStartOfMonth();

		AggregateResult[] producedQuantity = 
				[	SELECT	OrderItem__c oiId, Type__c, Period__c per, SUM(DispatchedQuantity__c) sumDispatched
					FROM	ProductionJournalRecord__c
					WHERE	((Type__c = 'Fact' and Period__c < :firstDayOfThisMonth) OR (Type__c = 'Fact' and ApprovedFact__c = True) OR (Type__c = 'Plan' and Period__c >= :firstDayOfThisMonth))
					 And	OrderItem__c in :oiIdSet
					GROUP	BY OrderItem__c, Type__c, Period__c
					ORDER	BY Period__c
				];
		For (AggregateResult pq : producedQuantity) {
			Id oiId = (Id) pq.get('oiId');
			Decimal dispatched = (Decimal) pq.get('sumDispatched');
			Date per = (Date) pq.get('per');
			String prodType = (String) pq.get('Type__c');
			
			Map<Date, Decimal> oiProdMap = productionMap.get(oiId);
			if (oiProdMap == null) {
				oiProdMap = new Map<Date, Decimal>();
				oiProdMap.put(per, dispatched);
				productionMap.put(oiId, oiProdMap);
			} else {
				if (!(oiProdMap.containsKey(per)) || prodType == 'Fact') {
					oiProdMap.put(per, dispatched);
				}
			}
		}

		return productionMap;
	}

	private Map<String, Decimal> getBudgetMap() {
		Map<String, Decimal> budgetMap = new Map<String, Decimal>();
		Date firstDayOfThisMonth = Date.today().toStartOfMonth();
		AggregateResult[] spfAgg;

		// Получим данные по непокрытому бюджету: соберем данные по бюджету и вычтем из них уже раскиданные ордера
		spfAgg =
		[	SELECT		Type__c recType, Period__c per, MarketSegment__c ms, Shop__c shop, SUM(ProductionAmount__c) q
			FROM		SalesPlanFact__c
			WHERE		(Type__c = 'Actual Budget' OR Type__c = 'Order')
			 AND		Period__c >= :firstDayOfThisMonth
			GROUP BY	Type__c, Period__c, MarketSegment__c, Shop__c
		];

		for (AggregateResult bq : spfAgg) {
			Date per = (Date) bq.get('per');
			String ms = (String) bq.get('ms');
			Id shop = (Id) bq.get('shop');
			String recType = (String) bq.get('recType');
			Decimal q = recType == 'Actual Budget' ? (Decimal) bq.get('q') : - (Decimal) bq.get('q');

			String keyFields = per + '|' + ms + '|' + shop;
			Decimal currentQuantity = budgetMap.get(keyFields);
			if (currentQuantity == null) {
				budgetMap.put(keyFields, q);
			} else {
				budgetMap.put(keyFields, currentQuantity + q); // (Если это Budget, то q - положительное, если это Order, то q - отрицательное.
			}
		}

		
		return budgetMap;
	}

	private void createRelatedSPF(OrderItem oi, Map<Id, Map<Date, Decimal>> productionMap,
									Map<String, Decimal> budgetMap, Map<Id, Order> orderMap,
									Map<String, Id> rtNameMap, Set<Date> plannedPeriods) {
		
		// Распределим свободное количество по месяцам, начиная с текущего.
		
		Order ord = orderMap.get(oi.OrderId);
		Decimal oiQuantity = oi.Quantity;
		Decimal producedQuantity = 0;

		//Посчитаем, сколько было произведено продукции в прошлых периодах:
		Date per = Date.today().toStartOfMonth();
		Map<Date, Decimal> oiProdMap = productionMap.get(oi.Id);
		if (oiProdMap != null) {
			Set<Date> keySet = oiProdMap.keySet();
			for (Date key : keySet) {
				if (key < per) {
					producedQuantity += oiProdMap.get(key);
				}
			}
		} else {
			producedQuantity = 0;
		}
			
		Decimal restQuantity = oiQuantity - producedQuantity;
		if (restQuantity < 2) {
			// Количество меньше двух тонн попросили не распределять.
			return;
		}
		while (restQuantity > 0) {
			SalesPlanFact__c spf = new SalesPlanFact__c();

			spf.InitialRecordId__c = String.valueOf(oi.Id);
			spf.InitialRecordURL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/' + oi.Id;
			spf.Period__c = per;
			spf.RecordTypeId = rtNameMap.get('Order');
			spf.OrderAdditionalNumber__c = ord.AdditionalNumber__c;
			spf.ID_ERP__c = oi.ID_ERP__c;
			spf.Shop__c = oi.Shop__c;
			spf.QuotaType__c = oi.QuotaType__c;
			spf.MarketSegment__c = ord.MarketSegment__c;
			spf.Country__c = ord.Country__c;
			spf.Account__c = ord.AccountId;
			spf.OwnerId = ord.OwnerId;
			spf.CurrencyIsoCode = 'USD';
			spf.ProductionAmount__c = restQuantity;
			spf.SalesAmount__c = 0;
			spf.Revenue__c = 0;
			spf.Margin__c = 0;
			spf.Probability__c = 100;
			spf.SecondChoice__c = ord.IsSecondChoice__c;

			spfToInsert.add(spf);

			spf = spf.clone();
			spf.RecordTypeId = rtNameMap.get('Opportunity');
			spfToInsert.add(spf);

			// Для следующего месяца учтем план производства текущего месяца, либо если его еще нет, то бюджет этого месяца.
			if (plannedPeriods.contains(per)) {
				// Для этого месяца есть планы производства. Значит мы должны учесть именно их для следующего месяца
				If (oiProdMap != null) {
					// Для этой строки заказа существуют записи PJR
					Decimal prodPlanForThisPer = oiProdMap.get(per);
					restQuantity -= (prodPlanForThisPer != null ? prodPlanForThisPer : 0);
				}
					
			} else {
				// Для этого месяца планов производства еще нет, поэтому учтем бюджет для этого месяца
				String keyFields = per + '|' + ord.MarketSegment__c + '|' + oi.Shop__c;
				Decimal budgetThisMonth = budgetMap.get(keyFields);
				if (budgetThisMonth != null) {
					restQuantity -= budgetThisMonth;
					// Вычтем из карты бюджетов учтенное только что количество:
					budgetMap.put(keyFields, budgetThisMonth - Math.min(spf.ProductionAmount__c, budgetThisMonth));
				}
			}
				
			per = per.addMonths(1);
			if (per > Date.today().addMonths(2)) {
				// Если мы уже раскидали количество на текущий месяц и два следующих, то остановимся
				break;
			}
		}
	}
}