force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/A2Code__c.field-meta.xml
<CustomField>
    <fullName>A2Code__c</fullName>
    <description>Country code according to ISO A2 codes for countries</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A2 codes for countries</inlineHelpText>
    <label>A2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/A3Code__c.field-meta.xml
<CustomField>
    <fullName>A3Code__c</fullName>
    <description>Country code according to ISO A3 codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A3 codes for countries.</inlineHelpText>
    <label>A3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/Market_Segment__c.field-meta.xml
<CustomField>
    <fullName>Market_Segment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/fields/NumCode__c.field-meta.xml
<CustomField>
    <fullName>NumCode__c</fullName>
    <description>Country code according to ISO numeric codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO numeric codes for countries.</inlineHelpText>
    <label>Numeric Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/PhoneCode__c.field-meta.xml
<CustomField>
    <fullName>PhoneCode__c</fullName>
    <label>Phone Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/SysName__c.field-meta.xml
<CustomField>
    <fullName>SysName__c</fullName>
    <label>System Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Currencies</relationshipLabel>
    <relationshipName>Currencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CountryRepository.cls
public class CountryRepository {
    private static Map<String, Country__c> countriesA2CodesMap;// <A2Code, Country__c>
    private static Map<String, Country__c> countriesNumCodesMap;
    private static Map<Id, Country__c> countriesMap;
    private static Boolean isLoaded = false;

    public static void loadAllContries() {
        if(isLoaded) return;
        countriesA2CodesMap = new Map<String, Country__c>();
        countriesNumCodesMap = new Map<String, Country__c>();
        countriesMap = new Map<Id, Country__c>();
        List<Country__c> countryList = [SELECT
                                            Id, A2Code__c, A3Code__c, Name, Currency__c, SysName__c,
                                            ID_ERP__c, Market_Segment__c, NumCode__c, PhoneCode__c
                                        FROM Country__c
                                        WHERE A2Code__c!='0'
                                        ];
        if(!countryList.isEmpty()) {
            for(Country__c c: countryList) {
                countriesA2CodesMap.put(c.A2Code__c, c);
                countriesNumCodesMap.put(c.NumCode__c, c);
                countriesMap.put(c.Id, c);
            }
        }
        isLoaded = true;
    }

    public static Country__c getById(Id id) {
        loadAllContries();
        return countriesMap.get(id);
    }

    public static Country__c getByA2Code (String A2Code) {
        loadAllContries();
        return countriesA2CodesMap.get(A2Code);     
    }

     public static Country__c getByNumCode (String NumCode) {
        loadAllContries();
        return countriesNumCodesMap.get(NumCode);       
    }   

     //--- Чистимо кеш
    public static void clearCache() {
        isLoaded = false;
        countriesA2CodesMap = null;
        countriesNumCodesMap = null;
        countriesMap = null;
    }
    //--- Рефрешимо кеш
    public static void refresh() {
        clearCache();
        loadAllContries();
    }   

}