force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryQuantity__c.field-meta.xml
<CustomField>
    <fullName>InquiryQuantity__c</fullName>
    <description>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</description>
    <inlineHelpText>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryUnit__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnit__c</fullName>
    <description>Measuring unit for the product in the customer&apos;s inquiry.</description>
    <inlineHelpText>Measuring unit for the product in the customer&apos;s inquiry.</inlineHelpText>
    <label>Measurement Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>34</fullName>
                <label>t</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>m</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>ft</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>pcs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnitPrice__c</fullName>
    <description>Product price per inquiry measurement unit.</description>
    <inlineHelpText>Product price per inquiry measurement unit.</inlineHelpText>
    <label>Price per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Opportunity product full name, that will be displayed</description>
    <inlineHelpText>This name will be displayed on the list layouts, some reports, etc.</inlineHelpText>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_ft__c.field-meta.xml
<CustomField>
    <fullName>Quantity_ft__c</fullName>
    <description>Quantity in feet</description>
    <inlineHelpText>Quantity in feet</inlineHelpText>
    <label>Quantity (ft)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_m__c.field-meta.xml
<CustomField>
    <fullName>Quantity_m__c</fullName>
    <description>Quantity in meters</description>
    <inlineHelpText>Quantity in meters</inlineHelpText>
    <label>Quantity (m)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_pcs__c.field-meta.xml
<CustomField>
    <fullName>Quantity_pcs__c</fullName>
    <description>Number of pieces of the product</description>
    <inlineHelpText>Number of pieces of the product</inlineHelpText>
    <label>Quantity (pcs)</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ShippingPoint__c.field-meta.xml
<CustomField>
    <fullName>ShippingPoint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Shipping point where to deliver products</description>
    <inlineHelpText>Shipping point where to deliver products</inlineHelpText>
    <label>Shipping Point</label>
    <referenceTo>ShippingPoint__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SteelGrade__c.field-meta.xml
<CustomField>
    <fullName>SteelGrade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Steel grade</description>
    <inlineHelpText>Steel grade</inlineHelpText>
    <label>Steel Grade</label>
    <referenceTo>SteelGrade__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeOD__c.field-meta.xml
<CustomField>
    <fullName>TubeOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube outside diameter</description>
    <inlineHelpText>Tube outside diameter</inlineHelpText>
    <label>OD</label>
    <referenceTo>TubeOD__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeWT__c.field-meta.xml
<CustomField>
    <fullName>TubeWT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube wall thickness</description>
    <inlineHelpText>Tube wall thickness</inlineHelpText>
    <label>WT</label>
    <referenceTo>TubeWT__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ShippingPoint__c/ShippingPoint__c.object-meta.xml
<CustomObject>
    <description>Shipping points such as sea ports, railway stations, etc.</description>
    <label>Shipping Point</label>
    <nameField>
        <label>Shipping Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ShippingPoint__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Country of the shipping point location</description>
    <inlineHelpText>Country of the shipping point location</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Shipping Points</relationshipLabel>
    <relationshipName>Shipping_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SteelGrade__c/SteelGrade__c.object-meta.xml
<CustomObject>
    <label>Steel Grade</label>
    <nameField>
        <label>Steel Grade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Steel Grades</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeLengthSize__c/TubeLengthSize__c.object-meta.xml
<CustomObject>
    <description>Possible tube length size</description>
    <label>Tube Length Size</label>
    <nameField>
        <label>Length Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tube Length Sizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeLengthSize__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TubeOD__c/TubeOD__c.object-meta.xml
<CustomObject>
    <description>Tube outside diameter</description>
    <label>Tube OD</label>
    <nameField>
        <label>Tube OD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes OD</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeOD__c/fields/OD_mm__c.field-meta.xml
<CustomField>
    <fullName>OD_mm__c</fullName>
    <description>Precise outside diameter in millimeters</description>
    <inlineHelpText>Precise outside diameter in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/TubeWT__c.object-meta.xml
<CustomObject>
    <description>Tube wall thickness</description>
    <label>Tube WT</label>
    <nameField>
        <label>Tube WT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes WT</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeWT__c/fields/WT_mm__c.field-meta.xml
<CustomField>
    <fullName>WT_mm__c</fullName>
    <description>Precise wall thickness in millimeters</description>
    <inlineHelpText>Precise wall thickness in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/addProductController.cls
public with sharing class addProductController {
	@TestVisible static Boolean isInSalesforce1 = UserInfo.getUIThemeDisplayed() == 'Theme4t';
	public static TubeOD__c od = new TubeOD__c();
	public static TubeWT__c wt = new TubeWT__c();
	public static TubeLengthSize__c ls = new TubeLengthSize__c();
	public static SteelGrade__c sg = new SteelGrade__c();

	@AuraEnabled
	public static Boolean getIsAllowedToAddProducts(Id oppId) {
		Opportunity opp = [SELECT Id, ID_ERP__c FROM Opportunity WHERE Id = :oppId];
		return String.isBlank(opp.ID_ERP__c);
	}

	@AuraEnabled
	public static Map<String, String> getProductNames(Id oppId) {
		Map<String, String> values = new Map<String, String> ();
		Opportunity opp = [SELECT Id, Pricebook2Id, CurrencyIsoCode FROM Opportunity WHERE Id = :oppId];
		List<PriceBookEntry> pb2 = [select Id, UnitPrice, Product2Id, Product2.Name, Product2.IsActive from PriceBookEntry where Pricebook2Id = :opp.Pricebook2Id and CurrencyISOcode = :opp.CurrencyISOcode AND Product2.IsActive = true];
		for (PriceBookEntry pbe : pb2) {
			values.put(pbe.Product2Id, pbe.Product2.Name);
		}
		System.debug(values);
		return values;

	}

	@AuraEnabled
	public static String getCurrencyIsoCode(Id oppId) {
		Opportunity opp = [SELECT CurrencyIsoCode FROM Opportunity WHERE Id = :oppId];
		return opp.CurrencyIsoCode;
	}

	@AuraEnabled
	public static OpportunityLineItem getNewOppProduct() {
		return new OpportunityLineItem();
	}

	@AuraEnabled
	public static Map<String, String> getFieldPicklistValues(String picklistField) {
		Schema.SObjectType sobjectType = Schema.getGlobalDescribe().get('OpportunityLineItem');
		List<Schema.PicklistEntry> picklistValues = sobjectType.getDescribe().fields.getMap().get(picklistField).getDescribe().getPickListValues();
		Map<String, String> values = new Map<String, String> ();
		for (Schema.PicklistEntry pklVal : picklistValues) {
			values.put(pklVal.getLabel(), pklVal.getValue());
		}
		return values;
	}

	@AuraEnabled
	public static Map<String, String> getNames(String objectApiName) {
		Map<String, String> values = new Map<String, String> ();
		List<SObject> objList = Database.query('SELECT Id, Name FROM ' + objectApiName);
		for (SObject obj : objList) {
			values.put(obj.Id, (String) obj.get('Name'));
		}
		return values;
	}

	@AuraEnabled
	public static Boolean isMobile() {
		return(isInSalesforce1);
	}

	@AuraEnabled
	public static Map<String, String> getShippingPointForCountry(Id oppId) {
		Map<String, String> values = new Map<String, String> ();
		Opportunity opp = [SELECT Country__c FROM Opportunity WHERE Id = :oppId];

		List<ShippingPoint__c> spList = [SELECT Id, Name FROM ShippingPoint__c WHERE Country__c = :opp.Country__c];
		for (ShippingPoint__c sp : spList) {
			values.put(sp.Id, sp.Name);
		}
		return values;
	}

	@AuraEnabled
	public static String addOppProductQ(OpportunityLineItem oppProduct, Id oppId) {
		String errorMessage = '';
		try {
			Opportunity opp = [SELECT Id, CurrencyISOcode FROM Opportunity WHERE Id = :oppId];
			PriceBookEntry pb2;
			if (Test.isRunningTest()) {
				Id pricebookId = Test.getStandardPricebookId();
				pb2 = [select Id, UnitPrice from PriceBookEntry where Pricebook2Id = :pricebookId LIMIT 1];
			} else {
				Pricebook2 pb1 = [select Id, Name, IsActive from PriceBook2 where IsStandard = True LIMIT 1];
				pb2 = [select Id, UnitPrice from PriceBookEntry where Pricebook2Id = :pb1.Id and Product2Id = :oppProduct.Product2Id and CurrencyISOcode = :opp.CurrencyISOcode LIMIT 1];
			}
			OpportunityLineItem oppProductToInsert = new OpportunityLineItem();
			oppProductToInsert = oppProduct;
			if (oppProduct.InquiryUnit__c == '34') {
				oppProductToInsert.Quantity = oppProductToInsert.InquiryQuantity__c;
			}
			else if (oppProduct.InquiryUnit__c == '20') {
				oppProductToInsert.Quantity_m__c = oppProductToInsert.InquiryQuantity__c;
			} else if (oppProduct.InquiryUnit__c == '74') {
				oppProductToInsert.Quantity_ft__c = oppProductToInsert.InquiryQuantity__c;
			} else if (oppProduct.InquiryUnit__c == '43') {
				oppProductToInsert.Quantity_pcs__c = oppProductToInsert.InquiryQuantity__c;
			}

			oppProductToInsert.PricebookEntryId = pb2.Id;
			//oppProductToInsert.UnitPrice = oppProduct.UnitPrice != null ? oppProduct.UnitPrice : 0;

			oppProductToInsert.OpportunityId = oppId;
			System.debug(oppProductToInsert.InquiryUnit__c);
			if (oppProduct.InquiryUnitPrice__c != null) {
				oppProductToInsert.UnitPrice = oppProductToInsert.InquiryUnitPrice__c;
			}
			else {
				oppProductToInsert.UnitPrice = 0;
			}
			oppProductToInsert.TotalPrice = null;
			oppProductToInsert.Name__c = (sg.Name != null ? sg.Name : '') + ' ' + od.OD_mm__c + 'x' + wt.WT_mm__c + ' ' + (ls.Name != null ? ls.Name : '');
			System.debug(oppProductToInsert);
			Database.SaveResult result = Database.insert(oppProductToInsert);

			/*Database.Error[] errors = result.getErrors();
			  for(Database.Error error : errors){
			  errorMessage+=error + '. ';
			  }*/
		}
		catch(Exception e) {
			errorMessage = e.getMessage();
			errorMessage += e.getStackTraceString();
		}
		return errorMessage;
	}

	public class ResponseData {
		public Boolean isSuccess;
		public Map<String, Object> results;
		public String errMsg;

		public ResponseData() {
			this.isSuccess = true;
			this.results = new Map<String, Object> ();
		}

		public void addError(String errMsg) {
			this.errMsg = errMsg;
			this.isSuccess = false;
		}

		public String getJsonString() {
			return JSON.serialize(this);
		}
	}
}