force-app/main/default/objects/GeneralProductStandard__c/GeneralProductStandard__c.object-meta.xml
<CustomObject>
    <label>General Product Standard</label>
    <nameField>
        <label>Product Standard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Product Standards</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PipeLinearWeight__c/PipeLinearWeight__c.object-meta.xml
<CustomObject>
    <description>A reference for determining pipe linear weight</description>
    <label>Pipe Linear Weight</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>PipeLinearWeight Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pipes Linear Weights</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PipeLinearWeight__c/fields/GeneralProductStandard__c.field-meta.xml
<CustomField>
    <fullName>GeneralProductStandard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>General Product Standard</label>
    <referenceTo>GeneralProductStandard__c</referenceTo>
    <relationshipLabel>Pipes Linear Weights</relationshipLabel>
    <relationshipName>Pipes_Linear_Weights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PipeLinearWeight__c/fields/KeyField__c.field-meta.xml
<CustomField>
    <fullName>KeyField__c</fullName>
    <formula>GeneralProductStandard__r.ID_ERP__c + &apos;|&apos; +
Text(CalculationGroup__c) + &apos;|&apos; +
TubeOD__r.ID_ERP__c + &apos;|&apos; +
TubeWT__r.ID_ERP__c + &apos;|&apos; +
Text(TubeEndsType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key Field</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PipeLinearWeight__c/fields/TubeOD__c.field-meta.xml
<CustomField>
    <fullName>TubeOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube outside diameter</description>
    <inlineHelpText>Tube outside diameter</inlineHelpText>
    <label>OD</label>
    <referenceTo>TubeOD__c</referenceTo>
    <relationshipLabel>Pipes Linear Weights</relationshipLabel>
    <relationshipName>Pipes_Linear_Weights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PipeLinearWeight__c/fields/TubeWT__c.field-meta.xml
<CustomField>
    <fullName>TubeWT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WT</label>
    <referenceTo>TubeWT__c</referenceTo>
    <relationshipLabel>Pipes Linear Weights</relationshipLabel>
    <relationshipName>Pipes_Linear_Weights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PipeLinearWeight__c/fields/Weight_kpm__c.field-meta.xml
<CustomField>
    <fullName>Weight_kpm__c</fullName>
    <description>Linear weight (kilograms per meter)</description>
    <inlineHelpText>Linear weight (kilograms per meter)</inlineHelpText>
    <label>Weight (kpm)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PipeLinearWeight__c/fields/Weight_ppf__c.field-meta.xml
<CustomField>
    <fullName>Weight_ppf__c</fullName>
    <description>Linear weight (pounds per foot)</description>
    <inlineHelpText>Linear weight (pounds per foot)</inlineHelpText>
    <label>Weight (ppf)</label>
    <precision>11</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/LinearWeightCalculationGroup__c.field-meta.xml
<CustomField>
    <fullName>LinearWeightCalculationGroup__c</fullName>
    <description>Defines how to calculate linear weight for OCTG tubes.</description>
    <inlineHelpText>Only used for OCTG tubes.</inlineHelpText>
    <label>Linear Weight Calculation Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tubing</fullName>
            </value>
            <value>
                <fullName>Casing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TubeEnds__c/TubeEnds__c.object-meta.xml
<CustomObject>
    <description>Tube ends</description>
    <label>Tube Ends</label>
    <nameField>
        <label>Tube Ends Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes Ends</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeEnds__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;PE&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>STD</fullName>
            </value>
            <value>
                <fullName>NO CROPPING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TubeOD__c/TubeOD__c.object-meta.xml
<CustomObject>
    <description>Tube outside diameter</description>
    <label>Tube OD</label>
    <nameField>
        <label>Tube OD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes OD</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeOD__c/fields/OD_inch__c.field-meta.xml
<CustomField>
    <fullName>OD_inch__c</fullName>
    <description>Precise outside diameter in inches</description>
    <inlineHelpText>Precise outside diameter in inches</inlineHelpText>
    <label>inch</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeOD__c/fields/OD_mm__c.field-meta.xml
<CustomField>
    <fullName>OD_mm__c</fullName>
    <description>Precise outside diameter in millimeters</description>
    <inlineHelpText>Precise outside diameter in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/TubeWT__c.object-meta.xml
<CustomObject>
    <description>Tube wall thickness</description>
    <label>Tube WT</label>
    <nameField>
        <label>Tube WT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes WT</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeWT__c/fields/WT_inch__c.field-meta.xml
<CustomField>
    <fullName>WT_inch__c</fullName>
    <description>Precise wall thickness in inches</description>
    <inlineHelpText>Precise wall thickness in inches</inlineHelpText>
    <label>inch</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/fields/WT_mm__c.field-meta.xml
<CustomField>
    <fullName>WT_mm__c</fullName>
    <description>Precise wall thickness in millimeters</description>
    <inlineHelpText>Precise wall thickness in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel</fullName>
    </customValue>
    <customValue>
        <fullName>Tyre</fullName>
    </customValue>
    <customValue>
        <fullName>Axle</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel set</fullName>
    </customValue>
    <customValue>
        <fullName>Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Cookware</fullName>
    </customValue>
    <description>Our product types</description>
    <masterLabel>Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PipeWeightCalculations.cls
public class PipeWeightCalculations  {

	public static List<PipeLinearWeight__c> plwList;
	public static Map<String, Id> plwIdMap = new Map<String, Id>();
	public static Map<Id, PipeLinearWeight__c> idPlwMap = new Map<Id, PipeLinearWeight__c>();

	static {
		plwList = [SELECT Id, KeyField__c, Weight_kpm__c, Weight_ppf__c FROM PipeLinearWeight__c];
		idPlwMap.putAll(plwList);
		for (PipeLinearWeight__c plw : plwList) {
			System.debug('Key field of the record: ' + plw.KeyField__c);
			plwIdMap.put(plw.KeyField__c, plw.Id);
		}
	}
	
	public static Map<String, Decimal> getPipeLinearWeight(Product2 product, GeneralProductStandard__c gps, TubeOD__c od, TubeWT__c wt, TubeEnds__c ends) {
		Map<String, Decimal> lwMap = new Map<String, Decimal>();

		if (product.Family == 'OCTG'){
			//Вес погонного метра OCTG труб определяем по справочнику:
			if (gps == null) {
				return lwMap;
			}
			String keyField = gps.ID_ERP__c + '|' + product.LinearWeightCalculationGroup__c + '|' + od.ID_ERP__c + '|' + wt.ID_ERP__c + '|' + ends.Type__c;

			System.debug('Key field for Pipe Linear Weight table: ' + keyField);
			System.debug('Key field (with hyphens): ' + gps.ID_ERP__c + '-' + product.LinearWeightCalculationGroup__c + '-' + od.ID_ERP__c + '-' + wt.ID_ERP__c + '-' + ends.Type__c);
			System.debug('PLW map: ' + plwIdMap);

			Id plwId = plwIdMap.get(keyField);
			if (plwId != null){
				lwMap.put('kpm', idPlwMap.get(plwId).Weight_kpm__c);
				lwMap.put('ppf', idPlwMap.get(plwId).Weight_ppf__c);
			}
		} else {
			//Вес погонного метра гладких труб вычисляем по формуле:
			lwMap.put('kpm', (od.OD_mm__c - wt.WT_mm__c) * wt.WT_mm__c * 0.02466);
			lwMap.put('ppf', (od.OD_inch__c - wt.WT_inch__c) * wt.WT_inch__c * 10.69);
		}

		return lwMap;
	}

}