force-app/main/default/objects/Bank_Details__mdt/fields/HeaderText__c.field-meta.xml
<CustomField>
    <fullName>HeaderText__c</fullName>
    <defaultValue>&quot;Dear Sirs,&lt;br/&gt;We thankfully acknowledge receipt of your enquiry &amp; we are pleased to submit our offer for the supply of materials with the following additional details:&quot;</defaultValue>
    <label>HeaderText</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryQuantity__c.field-meta.xml
<CustomField>
    <fullName>InquiryQuantity__c</fullName>
    <description>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</description>
    <inlineHelpText>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryUnit__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnit__c</fullName>
    <description>Measuring unit for the product in the customer&apos;s inquiry.</description>
    <inlineHelpText>Measuring unit for the product in the customer&apos;s inquiry.</inlineHelpText>
    <label>Measurement Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>34</fullName>
                <label>t</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>m</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>ft</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>pcs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnitPrice__c</fullName>
    <description>Product price per inquiry measurement unit.</description>
    <inlineHelpText>Product price per inquiry measurement unit.</inlineHelpText>
    <label>Price per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LengthSize__c.field-meta.xml
<CustomField>
    <fullName>LengthSize__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tube length size</description>
    <inlineHelpText>Tube length size</inlineHelpText>
    <label>Length Size</label>
    <referenceTo>TubeLengthSize__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Product type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_m__c.field-meta.xml
<CustomField>
    <fullName>Quantity_m__c</fullName>
    <description>Quantity in meters</description>
    <inlineHelpText>Quantity in meters</inlineHelpText>
    <label>Quantity (m)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeOD__c.field-meta.xml
<CustomField>
    <fullName>TubeOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube outside diameter</description>
    <inlineHelpText>Tube outside diameter</inlineHelpText>
    <label>OD</label>
    <referenceTo>TubeOD__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeWT__c.field-meta.xml
<CustomField>
    <fullName>TubeWT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube wall thickness</description>
    <inlineHelpText>Tube wall thickness</inlineHelpText>
    <label>WT</label>
    <referenceTo>TubeWT__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Weight_kpm__c.field-meta.xml
<CustomField>
    <fullName>Weight_kpm__c</fullName>
    <description>Pipe linear weight - kilograms per meter (kg/m)</description>
    <inlineHelpText>Pipe linear weight - kilograms per meter (kg/m)</inlineHelpText>
    <label>Linear Weight (kpm)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Weight_ppf__c.field-meta.xml
<CustomField>
    <fullName>Weight_ppf__c</fullName>
    <description>Pipe linear weight - pounds per foot (lb/ft)</description>
    <inlineHelpText>Pipe linear weight - pounds per foot (lb/ft)</inlineHelpText>
    <label>Linear Weight (ppf)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductType__c/ProductType__c.object-meta.xml
<CustomObject>
    <label>Product Type</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote/fields/HeaderText__c.field-meta.xml
<CustomField>
    <fullName>HeaderText__c</fullName>
    <description>Text that will appear in the top of the PDF document.</description>
    <inlineHelpText>Text that will appear in the top of the PDF document.</inlineHelpText>
    <label>Header Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/TubeLengthSize__c.object-meta.xml
<CustomObject>
    <description>Possible tube length size</description>
    <label>Tube Length Size</label>
    <nameField>
        <label>Length Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tube Length Sizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeLengthSize__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/MaxLength__c.field-meta.xml
<CustomField>
    <fullName>MaxLength__c</fullName>
    <description>Maximum length of the tube in millimeters</description>
    <inlineHelpText>Maximum length of the tube in millimeters</inlineHelpText>
    <label>Max Length</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/MinLength__c.field-meta.xml
<CustomField>
    <fullName>MinLength__c</fullName>
    <description>Minimal length of the tube in millimeters</description>
    <inlineHelpText>Minimal length of the tube in millimeters</inlineHelpText>
    <label>Min Length</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typical size of the tube.</description>
    <inlineHelpText>Typical size of the tube.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>R2</fullName>
            </value>
            <value>
                <fullName>R3</fullName>
            </value>
            <value>
                <fullName>DRL</fullName>
            </value>
            <value>
                <fullName>SRL</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TubeOD__c/TubeOD__c.object-meta.xml
<CustomObject>
    <description>Tube outside diameter</description>
    <label>Tube OD</label>
    <nameField>
        <label>Tube OD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes OD</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeOD__c/fields/OD_mm__c.field-meta.xml
<CustomField>
    <fullName>OD_mm__c</fullName>
    <description>Precise outside diameter in millimeters</description>
    <inlineHelpText>Precise outside diameter in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/TubeWT__c.object-meta.xml
<CustomObject>
    <description>Tube wall thickness</description>
    <label>Tube WT</label>
    <nameField>
        <label>Tube WT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes WT</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeWT__c/fields/WT_mm__c.field-meta.xml
<CustomField>
    <fullName>WT_mm__c</fullName>
    <description>Precise wall thickness in millimeters</description>
    <inlineHelpText>Precise wall thickness in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel</fullName>
    </customValue>
    <customValue>
        <fullName>Tyre</fullName>
    </customValue>
    <customValue>
        <fullName>Axle</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel set</fullName>
    </customValue>
    <customValue>
        <fullName>Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Cookware</fullName>
    </customValue>
    <description>Our product types</description>
    <masterLabel>Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerHandlerTest.cls
@isTest
private class QuoteTriggerHandlerTest extends BaseTest {

	@isTest
	private static void testHeaderOnUpdate() {
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		Quote testQuote = new Quote(Name='Test', OpportunityId = opp.Id, Pricebook2Id = Test.getStandardPricebookId());
		insert testQuote;

		t.start();
		testQuote.HeaderText__c = 'Test Header';
		update testQuote;
		t.stop();

		Quote updatedQuote = [SELECT HeaderText__c FROM Quote WHERE Id = :testQuote.Id];
		System.assertEquals('Test Header', updatedQuote.HeaderText__c);
	}

	@isTest
	private static void testHeaderOnInsert() {
		Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		Quote testQuote = new Quote(Name='Test', OpportunityId = opp.Id, Pricebook2Id = Test.getStandardPricebookId());
		List<Bank_Details__mdt> banks = [SELECT Id, HeaderText__c FROM Bank_Details__mdt];		

		t.start();
		insert testQuote;
		t.stop();

		Quote updatedQuote = [SELECT HeaderText__c FROM Quote WHERE Id = :testQuote.Id];
		System.assertEquals(banks[0].HeaderText__c.replaceAll('<[/a-zAZ0-9]*>',''), updatedQuote.HeaderText__c.replaceAll('<[/a-zAZ0-9]*>',''));
	}

	@testSetup 
    static void testSetup() {

      Account testAccount = t.newAccounts('Test Account')[0];
      testAccount.ID_ERP__c = 'acc1';
      insert testAccount;     

      Opportunity testOpp = t.newOpportunities('Test', testAccount.Id, 'Qualification', Date.today())[0];
      insert testOpp;

      Id pricebookId = Test.getStandardPricebookId();
      Product2 testProd1 = t.newProducts('Test product', '0000')[0];
      testProd1.ID_ERP__c = 'pr1';
      insert testProd1;

      PricebookEntry testPriceBookEntry1 = new PricebookEntry(
          Pricebook2Id = pricebookId,
          Product2Id = testProd1.Id,
          UnitPrice = 100.00,
          IsActive = true
      );
      insert testPriceBookEntry1;

      TubeWT__c wt = new TubeWT__c(ID_ERP__c = 'wt', Name = 'TestWT', WT_mm__c = 1.4);
      insert wt;

      TubeLengthSize__c size = new TubeLengthSize__c(ID_ERP__c = 'si', Name = 'testLS');
      size.MaxLength__c = 10;
      size.MinLength__c = 2;
	  size.Type__c = 'R1';
      insert size;

      TubeOD__c od = new TubeOD__c(ID_ERP__c = 'od', OD_mm__c = 5.3);
      insert od;
    
      OpportunityLineItem testOppProd1 = t.newOpportunityProducts(testPriceBookEntry1.Id, testOpp.Id)[0];
        testOppProd1.Quantity_m__c = 14854.0295;
        testOppProd1.InquiryUnit__c = '20';
        testOppProd1.InquiryQuantity__c = 1;
        testOppProd1.Quantity = 1;
        testOppProd1.TubeOD__c = od.Id;
        testOppProd1.TubeWT__c = wt.Id;
        testOppProd1.LengthSize__c = size.Id;
        testOppProd1.ID_ERP__c = '0001';
        testOppProd1.ProductType__c = 'Tube';
        testOppProd1.Weight_kpm__c = 10245.12;
        testOppProd1.Weight_ppf__c = 1234.56;
        testOppProd1.UnitPrice = testPriceBookEntry1.UnitPrice;
		testOppProd1.InquiryUnitPrice__c = 2;
      insert testOppProd1;
    }
    static { BaseTest.t = new QuoteTriggerHandlerTest(); }
    static BaseTest t { get { return BaseTest.t; } }
}