force-app/main/default/objects/PriceApprovalRequest__c/PriceApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>Price Approval Request</label>
    <nameField>
        <label>Doc. Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Approval Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceApprovalRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Approval Requests</relationshipLabel>
    <relationshipName>PriceApprovalRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PriceApprovalRequestTriggerHandlerTest.cls
@isTest
private class PriceApprovalRequestTriggerHandlerTest extends BaseTest {
	
	//@IsTest
	//static void testGetJsonString() {
		//PriceApprovalRequestTriggerHandler.getJsonString('111111', 'SalesRep:1', '55616', 'Salesforce Administrator');
	//}

	@IsTest
	static void testChangeDocName() {
		PriceApprovalRequest__c par = [select Id, Name from PriceApprovalRequest__c].get(0);
		par.name = '2020/0002';
		update par;
	}

	@testSetup 
	static void testSetup() {
		
		Account testAccount = t.newAccounts('Test Account')[0];
		insert testAccount;

		PriceApprovalRequest__c par = new PriceApprovalRequest__c();
		par.Account__c = testAccount.Id;
		par.Name = '2020/0001';
		insert par;
	}

	static { BaseTest.t = new PriceApprovalRequestTriggerHandlerTest(); }
	static BaseTest t { get { return BaseTest.t; } }
}