force-app/main/default/objects/Trade_Data__c/Trade_Data__c.object-meta.xml
<CustomObject>
    <label>Trade Data</label>
    <nameField>
        <displayFormat>TD-{0000000000}</displayFormat>
        <label>Trade Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_Data__c/fields/Exporter__c.field-meta.xml
<CustomField>
    <fullName>Exporter__c</fullName>
    <label>Exporter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExcelImportBatchTest.cls
@isTest
private class ExcelImportBatchTest {
	static testmethod void importBatch() {        
        List<trade_data__c> tradeData = new List<trade_data__c>();
       		for (Integer i=0;i<200;i++) {
            	tradeData.add(new Trade_Data__c(Exporter__c='test'+i));
            }
        insert tradeData;
        Test.startTest();
        String q = 'Select Id from Trade_data__c';
        ExcelImportBatch tb = new ExcelImportBatch(tradeData);
        Id batchId = Database.executeBatch(tb);
        Test.stopTest();
            Integer td=[select count() from Trade_Data__c];
        
        System.assertEquals(200, td);
             }
}