force-app/main/default/objects/AccountBOS__c/AccountBOS__c.object-meta.xml
<CustomObject>
    <label>Account BO Specialist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Account BO Specialist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account BO Specialists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBOS__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account BO Specialists</relationshipLabel>
    <relationshipName>Account_BO_Specialists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBOS__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BO Specialist</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND 5</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Chatter Free User</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Back Office Specialist</value>
        </filterItems>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Sales Support Department</value>
        </filterItems>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Back Office</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_BO_Specialists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountSalesSegmentation__c/AccountSalesSegmentation__c.object-meta.xml
<CustomObject>
    <label>Account Sales Segmentation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RowNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Segmentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSalesSegmentation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Segmentation</relationshipLabel>
    <relationshipName>Account_Sales_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountSalesSegmentation__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Sales_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTeamCanonicalMigrationAnalyzer.cls
public with sharing class AccountTeamCanonicalMigrationAnalyzer {

    public static AccountTeamCanonicalMigrationResult analyzeAll() {

        List<AccountSalesSegmentation__c> seg =
            [SELECT Id, Account__c, Manager__c
             FROM AccountSalesSegmentation__c
             WHERE Account__c != null
               AND Manager__c != null
               AND Manager__r.IsActive = true];

        Set<Id> accountIds = new Set<Id>();
        for (AccountSalesSegmentation__c s : seg) {
            accountIds.add(s.Account__c);
        }

        List<AccountBOS__c> bos =
            [SELECT Id, Account__c, User__c
             FROM AccountBOS__c
             WHERE Account__c IN :accountIds];

        AccountTeamCanonicalMigrationService.Config cfg =
            new AccountTeamCanonicalMigrationService.Config();

        cfg.isDryRun = true;

        return AccountTeamCanonicalMigrationService.process(seg, bos, cfg);
    }
}