force-app/main/default/objects/AccountBOS__c/AccountBOS__c.object-meta.xml
<CustomObject>
    <label>Account BO Specialist</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Account BO Specialist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account BO Specialists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountBOS__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account BO Specialists</relationshipLabel>
    <relationshipName>Account_BO_Specialists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountBOS__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BO Specialist</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>(1 OR 2) AND (3 OR 4) AND 5</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Chatter Free User</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Back Office Specialist</value>
        </filterItems>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Sales Support Department</value>
        </filterItems>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Back Office</value>
        </filterItems>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_BO_Specialists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountSalesSegmentation__c/AccountSalesSegmentation__c.object-meta.xml
<CustomObject>
    <label>Account Sales Segmentation</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>RowNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Sales Segmentation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSalesSegmentation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Sales Segmentation</relationshipLabel>
    <relationshipName>Account_Sales_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountSalesSegmentation__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Sales_Segmentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTeamCanonicalMigrationServiceTest.cls
@IsTest
private class AccountTeamCanonicalMigrationServiceTest  {

    private static User createUser(String email) {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];

        User u = new User(
            Alias = email.substring(0,5),
            Email = email,
            EmailEncodingKey = 'UTF-8',
            LastName = 'Test',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Europe/Paris',
            Username = email + System.currentTimeMillis()
        );
        insert u;
        return u;
    }

    @IsTest
    static void test_full_logic() {

        User owner = createUser('owner@test.com');
        User sales = createUser('sales@test.com');
        User bos = createUser('bos@test.com');

        Account acc = new Account(
            Name = 'Test Acc',
            OwnerId = owner.Id
        );
        insert acc;

        // Existing READ team member to test upgrade
        AccountTeamMember existing = new AccountTeamMember(
            AccountId = acc.Id,
            UserId = sales.Id,
            TeamMemberRole = 'BO Specialist',
            AccountAccessLevel = 'Read',
            OpportunityAccessLevel = 'Read',
            ContactAccessLevel = 'Read',
            CaseAccessLevel = 'None'
        );
        insert existing;

        AccountSalesSegmentation__c seg =
            new AccountSalesSegmentation__c(
                Account__c = acc.Id,
                Manager__c = sales.Id
            );

        AccountBOS__c bosRec =
            new AccountBOS__c(
                Account__c = acc.Id,
                User__c = bos.Id
            );

        insert seg;
        insert bosRec;

        AccountTeamCanonicalMigrationService.Config cfg =
            new AccountTeamCanonicalMigrationService.Config();
        cfg.isDryRun = false;

        Test.startTest();

        AccountTeamCanonicalMigrationResult res =
            AccountTeamCanonicalMigrationService.process(
                new List<AccountSalesSegmentation__c>{ seg },
                new List<AccountBOS__c>{ bosRec },
                cfg
            );

        Test.stopTest();

        System.assertEquals(1, res.upgraded); // sales upgraded
        System.assertEquals(1, res.inserted); // bos inserted

        List<AccountTeamMember> members =
            [SELECT UserId, AccountAccessLevel
             FROM AccountTeamMember
             WHERE AccountId = :acc.Id];

        System.assertEquals(2, members.size());

        for (AccountTeamMember m : members) {
            if (m.UserId == sales.Id) {
                System.assertEquals('Edit', m.AccountAccessLevel);
            }
        }
    }
}