force-app/main/default/objects/Currency__c/Currency__c.object-meta.xml
<CustomObject>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Currency__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country Currency</label>
    <referenceTo>Currency__c</referenceTo>
    <relationshipLabel>Currencies</relationshipLabel>
    <relationshipName>Currencies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Opportunity product full name, that will be displayed</description>
    <inlineHelpText>This name will be displayed on the list layouts, some reports, etc.</inlineHelpText>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/Reclamation__c.object-meta.xml
<CustomObject>
    <label>Reclamation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reclamations</relationshipLabel>
    <relationshipName>Reclamations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/ContractDate__c.field-meta.xml
<CustomField>
    <fullName>ContractDate__c</fullName>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/ContractNum__c.field-meta.xml
<CustomField>
    <fullName>ContractNum__c</fullName>
    <label>Contract Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/CreationDate__c.field-meta.xml
<CustomField>
    <fullName>CreationDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Creation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/ID_in_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_in_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID_in_ERP</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/No_Refund__c.field-meta.xml
<CustomField>
    <fullName>No_Refund__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/ReclSum__c.field-meta.xml
<CustomField>
    <fullName>ReclSum__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Reclamation Summary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sended</fullName>
            </value>
            <value>
                <fullName>_1</fullName>
                <label>Registered</label>
            </value>
            <value>
                <fullName>_2</fullName>
                <label>Is being considered</label>
            </value>
            <value>
                <fullName>_8</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>_9</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>_5</fullName>
                <label>Director decision</label>
            </value>
            <value>
                <fullName>Accepted_PendingCompensation</fullName>
                <label>Accepted  (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially_PendingCompensation</fullName>
                <label>Accepted partially (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially</fullName>
                <label>Accepted partially</label>
            </value>
            <value>
                <fullName>OnHold</fullName>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/Reclamation_Detail__c.object-meta.xml
<CustomObject>
    <label>Reclamation Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Reclamation Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation_Detail__c/fields/ClaimQty__c.field-meta.xml
<CustomField>
    <fullName>ClaimQty__c</fullName>
    <label>Claim Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ClaimSum__c.field-meta.xml
<CustomField>
    <fullName>ClaimSum__c</fullName>
    <label>Claim Summary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ID_in_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_in_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/MeasurementUnit__c.field-meta.xml
<CustomField>
    <fullName>MeasurementUnit__c</fullName>
    <label>Measurement Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>t</fullName>
            </value>
            <value>
                <fullName>m</fullName>
            </value>
            <value>
                <fullName>ft</fullName>
            </value>
            <value>
                <fullName>pcs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/Mistmatch_SubType__c.field-meta.xml
<CustomField>
    <fullName>Mistmatch_SubType__c</fullName>
    <label>Mistmatch SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mistmatch_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>geometry</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>defects</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>marking / stamping</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>coating / packaging</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>mechanical damage</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>mechanical properties</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>chemical composition</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>documentation</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>quantity</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>delivery period</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>others</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>defects after machining</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>simple vehicle</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>delivery period (Logistic)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>place of delivery (Logistic)</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>mechanical damage (Logistic)</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>marketable condition</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>salt</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>demerge</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>others (Logistic)</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>ordering</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>price</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>documentation (Commercial)</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>others (Commercial)</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Vehicles downtime</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>BWW</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>production planning</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Error in order (planning)</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>technical expertise</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>others (Maintenance)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/Mistmatch_Type__c.field-meta.xml
<CustomField>
    <fullName>Mistmatch_Type__c</fullName>
    <label>Mistmatch Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Manufacturing</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Logistic</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Exploitation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderItemID__c.field-meta.xml
<CustomField>
    <fullName>OrderItemID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Number</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderQty__c.field-meta.xml
<CustomField>
    <fullName>OrderQty__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ReclID__c.field-meta.xml
<CustomField>
    <fullName>ReclID__c</fullName>
    <label>Reclamation ID</label>
    <referenceTo>Reclamation__c</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ReclamationItemDatatableController.cls
public without sharing class ReclamationItemDatatableController {
	@AuraEnabled(cacheable=false)
    public static Reclamation__c getReclamationDetail(String ReclamationId){
        return [SELECT id,Name,CreationDate__c,Account__r.Name,ID_in_ERP__c,ContractNum__c,ContractDate__c,CurrencyIsoCode,toLabel(Status__c),No_Refund__c,Comment__c,Owner.firstName,Owner.LastName,
                (SELECT PO_Number__c,OrderItemID__r.Product2.Name,OrderItemID__r.Name__c,OrderQty__c,MeasurementUnit__c,ClaimQty__c,ClaimSum__c,Currency__c,CurrencyIsoCode,tolabel(Mistmatch_Type__c),tolabel(Mistmatch_SubType__c) FROM Reclamation_Details__r)
                FROM Reclamation__c
				WHERE id = :ReclamationId ];
    }
    
    @AuraEnabled
    public static void deleteReclamation(String ReclamationId){
        delete [SELECT id
                FROM Reclamation__c
				WHERE id = :ReclamationId ];
    }
    
    @AuraEnabled
    public static void deleteReclamationItem(String idRecord){
        delete [SELECT id FROM Reclamation_Detail__c WHERE id=:idRecord];
    }
    
    public static Set<Id> orderIds = new Set<id>();
    public Id currentReclamationId;
    
	@AuraEnabled
    public static List<List<String>> confirmReclamationIt(String reclamationId){       
        Set<Id> orderIdsFromReclamation = new Set<id>();
        List<List<String>> resultList = new List<List<String>>();
        List<String> innerResultList = new List<String>();
        String idERPAssignedBo;
        Reclamation__c reclamation = [SELECT Id,Name ,CreationDate__c, OwnerId, MarketSegment__c, ContractNum__c, ContractDate__c,ReclSum__c,
                                      AssignedBO_ID__c,CurrencyIsoCode,Comment__c,Account__r.ID_ERP__c FROM Reclamation__c WHERE Id=:reclamationId limit 1];
        List<Reclamation_Detail__c> reclamationDetails = [SELECT ID_in_ERP__c,Mistmatch_Type__c, MismatchDate__c,Mistmatch_SubType__c,ClaimQty__c,OrderID__c,
                                                          ClaimSum__c,CurrencyIsoCode,ClaimReason__c,OrderItemID__r.Quantity,iteNumber__c FROM Reclamation_Detail__c WHERE ReclID__c=:reclamationId];
        
        if(!Test.isRunningTest()){
            User assignedBO = [SELECT ID_ERP__c,LoginERP__c	 FROM User WHERE Id = :reclamation.AssignedBO_ID__c LIMIT 1];
        	idERPAssignedBo = assignedBO.LoginERP__c;
        } else {
            idERPAssignedBo = 'test123';
        }
        
        
        system.debug(reclamationDetails);
        Map<String,OpportunityLineItem> relatedOppLineItemMap = getRelatedOppLineItem(reclamationDetails);
        system.debug(relatedOppLineItemMap);
        try{
        JSONGenerator jsonToSend = JSON.createGenerator(true);
        string currentTime = string.valueof(DateTime.now());
		jsonToSend.writeStartObject();
            jsonToSend.writeFieldName('header');
            jsonToSend.writeStartObject();
           
                jsonToSend.writeObjectField('DT','2021-02-12T00:00:00');
            	jsonToSend.writeObjectField('DT_IN',currentTime);
            	//jsonToSend.writeObjectField('K_CL_T',' ');
            	jsonToSend.writeObjectField('KSEC',reclamation.MarketSegment__c==null?'0':reclamation.MarketSegment__c);
            	jsonToSend.writeObjectField('ORG',reclamation.Account__r.ID_ERP__c==null?' ':reclamation.Account__r.ID_ERP__c);
            	
            	jsonToSend.writeObjectField('DES_AMNT',reclamation.ReclSum__c==null?0:reclamation.ReclSum__c);
           		jsonToSend.writeObjectField('OVAL',reclamation.CurrencyIsoCode);
            	jsonToSend.writeObjectField('DESCR',reclamation.Comment__c==null?'none':reclamation.Comment__c);
            	jsonToSend.writeObjectField('UID_RESP',idERPAssignedBo);
                                              
        	jsonToSend.writeEndObject();
        	jsonToSend.writeFieldName('lines');
        	jsonToSend.writeStartArray();
       
        for(Reclamation_Detail__c reclItem: reclamationDetails){
            system.debug(reclItem);
            system.debug(reclItem.ITENumber__c);
            system.debug(relatedOppLineItemMap.get(reclItem.ITENumber__c));
            jsonToSend.writeStartObject();
            jsonToSend.writeObjectField('KZAJNPP',reclItem.iteNumber__c==null?'0':reclItem.iteNumber__c);
            jsonToSend.writeObjectField('K_MISTM',reclItem.Mistmatch_SubType__c==null?null:reclItem.Mistmatch_SubType__c);
            jsonToSend.writeObjectField('DT_MISTM',reclItem.MismatchDate__c==null?null:reclItem.MismatchDate__c);
            jsonToSend.writeObjectField('DESCR',reclItem.ClaimReason__c==null?'0':reclItem.ClaimReason__c);
           
            
            jsonToSend.writeObjectField('TONS',relatedOppLineItemMap.get(reclItem.ITENumber__c).quantity==null?0:relatedOppLineItemMap.get(reclItem.ITENumber__c).quantity);
            jsonToSend.writeObjectField('METERS',relatedOppLineItemMap.get(reclItem.ITENumber__c).Quantity_m__c==null?0:relatedOppLineItemMap.get(reclItem.ITENumber__c).Quantity_m__c);
            jsonToSend.writeObjectField('PCS',relatedOppLineItemMap.get(reclItem.ITENumber__c).Quantity_pcs__c==null?0:relatedOppLineItemMap.get(reclItem.ITENumber__c).Quantity_pcs__c.setScale(0));
           
            
            jsonToSend.writeEndObject();
            orderIdsFromReclamation.add(reclItem.OrderID__c);
        }
        
        jsonToSend.writeEndArray();       
        jsonToSend.writeEndObject();
        
        system.debug(jsonToSend.getAsString());
        makeCallout(jsonToSend.getAsString(), reclamation,orderIdsFromReclamation,reclamation.id);
         
        //searchAndSendNotificationForOrderOwners(orderIdsFromReclamation,reclamation.id);    
        } catch(Exception e ){
            system.debug(e.getMessage());
            innerResultList.add('Error occur. \n Notification mail was sent for administrator');
            system.debug(innerResultList);
            resultList.add(innerResultList);
            searchAndSendNotificationForAdministrator('Error occur: \n Problem with Formalize JSON' + e.getMessage(),reclamation.id);
            return resultList;
        }
        innerResultList.add('Reclamation was created');
        resultList.add(innerResultList);
        return resultList;
        
    }
    
    public static String makeCallout(string jsonString,Reclamation__c currentReclamation,Set<id> orderIds, Id reclamationId){
         SFToERP.WebServiceSoap ERPhandler = new SFToERP.WebServiceSoap();
        String login = Credentials__c.getOrgDefaults().User_Login__c;
		String password = Credentials__c.getOrgDefaults().User_Password__c;
		String response = ERPhandler.LoginEx(login, password);
        ERPRequestParser.LoginResponse requestObject = (ERPRequestParser.LoginResponse) System.JSON.deserialize(response, ERPRequestParser.LoginResponse.class);

		String calc = '_ADD_CLAIM_FROM_SF';
		String ticket = requestObject.Ticket;
		String arg = jsonString;
		ERPRequestParser.ExecuteResponceReclamation idResponse = null;
        try{
			String erpResult = ERPhandler.ExecuteEx(calc, arg, ticket);
			system.debug(arg);
            system.debug(arg.remove('\\'));
            system.debug(json.serializePretty(arg));
            System.debug('JSON before deserialization - ' + erpResult);
			String processed = erpResult.remove('\\');
			idResponse = (ERPRequestParser.ExecuteResponceReclamation) JSON.deserialize(processed, ERPRequestParser.ExecuteResponceReclamation.class);
            Map<String, Object> mappingResponse = (Map<String, Object>) JSON.deserializeUntyped(processed);
            
        
            if(mappingResponse.get('ERROR') == null){
                system.debug('Success');  
                searchAndSendNotificationForOrderOwners(orderIds,reclamationId);
                //currentReclamation.Comment__c = idResponse.id;
                currentReclamation.ID_in_ERP__c = String.valueOf(mappingResponse.get('ID'));
                currentReclamation.ERPSyncDate__c =  Date.today();
                currentReclamation.ERP_Number__c =String.valueOf(mappingResponse.get('NUMBER'));
                currentReclamation.Status__c = '_1';
                update currentReclamation;
            } else {
                //sendEmail(idResponse.Comments);
                system.debug('error');
                CalloutException e = new CalloutException();
                e.setMessage(String.valueof(mappingResponse.get('ERROR')));
                throw e;
            }
                       
            return processed;
        } catch(CalloutException callfail) {
			String errorMessage = callfail.getMessage() + '\n' + callfail.getStackTraceString();
			//ERPWebServiceHandler.insertErrorTask('SF to ERP (callout exception)', arg, errorMessage, wrapper.oppo.Id);	
			system.debug(errorMessage);	
           // sendEmail('Call invalid for json quote item');
			AuraHandledException e = new AuraHandledException('Call invalid for json reclamation');
            e.setMessage(errorMessage);
            system.debug(e);
        throw e;
		} catch(System.JSONException jsfailed) {
			String errorMessage = jsfailed.getMessage() + '\n' + jsfailed.getStackTraceString();
            system.debug(errorMessage);
           // sendEmail('JSONException. ' + errorMessage);
			//ERPWebServiceHandler.insertErrorTask('SF to ERP (serialization exception)', arg, errorMessage, wrapper.oppo.Id);			
			throw new AuraHandledException(Label.InvalidJSONReceived);
		} finally {
           //closeSessionAsync.closeCurrentSessionAsync(ticket);
       } 
    }
    
    public static List<String> takeLinksToAttachedFiles(id reclamationId){
        List<ContentDocumentLink> contentDocumentLinkList = [SELECT ContentDocumentId, ContentDocument.title FROM ContentDocumentLink WHERE  LinkedEntityId =:reclamationId];
        List<id> contentDocumentIds = new List<id>();
        List<id> contentVersionIds = new List<id>();
        List<String> documentLinks = new List<String>();
        List<ContentDistribution> contentDistributionsToInsert = new List<ContentDistribution>();
        system.debug('136');
        for(ContentDocumentLink cdl:contentDocumentLinkList){
            contentDocumentIds.add(cdl.ContentDocumentId);
        }        
        for(ContentVersion cv : [SELECT Id, IsLatest, title FROM ContentVersion WHERE ContentDocumentId in :contentDocumentIds]){
            contentVersionIds.add(cv.id);
            ContentDistribution cd = new ContentDistribution();
            cd.Name = cv.Title;
            cd.ContentVersionId = cv.Id;
            cd.PreferencesAllowViewInBrowser = true;
            cd.PreferencesLinkLatestVersion = true;
            cd.PreferencesNotifyOnVisit = false;
            cd.PreferencesPasswordRequired = false;
            cd.PreferencesAllowOriginalDownload = true;
            	contentDistributionsToInsert.add(cd);
        }
        system.debug('152');
        insert contentDistributionsToInsert;
        system.debug('154');
        for(ContentDistribution cd:[SELECT Id, ContentDownloadUrl FROM ContentDistribution WHERE ContentVersionId in:contentVersionIds]){
            documentLinks.add(cd.ContentDownloadUrl);
        }
        system.debug(documentLinks);
        return documentLinks;
    }
    
    public static Map<String,OpportunityLineItem> getRelatedOppLineItem(List<Reclamation_Detail__c> reclamationDetails){
       Map<String,OpportunityLineItem> resultMap = new Map<String,OpportunityLineItem>();
       List<String> iteNumberList = new  List<String>();
       for(Reclamation_Detail__c rd:reclamationDetails){
            iteNumberList.add(rd.iteNumber__c);
       }
       system.debug(iteNumberList);        
       List<OpportunityLineItem> fetchedOppLineItem = [SELECT ITENumber__c,Quantity,Quantity_m__c,Quantity_pcs__c FROM OpportunityLineItem WHERE ITENumber__c in:iteNumberList];
       system.debug(fetchedOppLineItem);
        for(OpportunityLineItem oli:fetchedOppLineItem){
            resultMap.put(oli.ITENumber__c,oli);
       }
       return resultMap;
    }
    
    public static void searchAndSendNotificationForOrderOwners(Set<id> orderIds, Id reclamationId){
        List<String> orderBoOwnerEmails = new List<String>();
        Set<String> ownerOppIds = new Set<String>();
        String orgUrl = Label.OrganizationURL;
        String mailBody = 'Reclamation was registered. Link: '+ orgUrl+ '/'+reclamationId;
        
        try{
            for(Order orderSearch:[SELECT Owner.Email,OwnerId FROM ORDER WHERE Id in:orderIds] ){
                //orderOwnerEmails.add(orderSearch.Owner.Email);
                ownerOppIds.add(orderSearch.OwnerId);
            }
        }catch(Exception e){          
            system.debug(e.getMessage());
        }
        
        try{
            for(User boUser:[SELECT AssignedBOS__r.Email,AssignedBOS__c FROM User WHERE Id in:ownerOppIds] ){
                orderBoOwnerEmails.add(boUser.AssignedBOS__r.Email);                      
            }
        }catch(Exception e){          
            system.debug(e.getMessage());
        }    
        
        try{
            //orderBoOwnerEmails.add('Olga.Napkhanko@m.interpipe.biz');
            //orderBoOwnerEmails.add('onaphanko@m.interpipe.biz');
        }catch(Exception e){          
            system.debug(e.getMessage());
        }     
        
        try{
            for(User boUser:[SELECT Manager.Email FROM User WHERE Id in:ownerOppIds] ){
            	orderBoOwnerEmails.add(boUser.Manager.Email);                  
        	}
        }catch(Exception e){          
            system.debug(e.getMessage());
        }
        
        if(orderBoOwnerEmails.size()>0){
           Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
            message.toAddresses = orderBoOwnerEmails;
            message.optOutPolicy = 'FILTER';
            message.subject = 'Registrered Reclamation';
            message.htmlbody = mailBody;
        }                           
    }
    
    public static void searchAndSendNotificationForAdministrator(String errorText, Id reclamationId){
        List<String> administratorEmails = new List<String>();
        
        String mailBody = errorText +' \n Reclamation id: '+ reclamationId;
        String administratorEmail =  Label.email_name_for_send_error;        
        administratorEmails.add(administratorEmail);
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = administratorEmails;
        message.optOutPolicy = 'FILTER';
        message.subject = 'Error Reclamation';
        message.htmlbody = mailBody;
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);             
    }
    
    @AuraEnabled
    public static void editReclamationItem(Object reclamationItem){
        Map<String, Integer> mistmatchTypeMap = getMapTypes();
        String jsonString = Json.serialize(reclamationItem);
        Reclamation_Detail__c itemToUpdate = (Reclamation_Detail__c) Json.deserialize(jsonString , Reclamation_Detail__c.class);
		//Reclamation_Detail__c itemToUpdate = (Reclamation_Detail__c) reclamationItem;
        update new Reclamation_Detail__c(id = itemToUpdate.id,
                                         ClaimQty__c = itemToUpdate.ClaimQty__c,
                                        Mistmatch_Type__c =String.valueOf(mistmatchTypeMap.get(String.valueOf(itemToUpdate.Mistmatch_Type__c))),
           								Mistmatch_SubType__c =String.valueOf(mistmatchTypeMap.get(String.valueOf(itemToUpdate.Mistmatch_SubType__c))));
    }
    
    public static Map<String,Integer> getMapTypes(){
        //Map<String, Integer> MistmatchType = new Map<String, Integer>();
    	
        Map<String,Integer> valueSubTypeMap= new Map<String,Integer>();
		
		Schema.DescribeFieldResult fieldResult = Reclamation_Detail__c.Mistmatch_SubType__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){			
            valueSubTypeMap.put(pickListVal.getLabel(),Integer.valueOf(pickListVal.getValue()));
		} 
        
        Schema.DescribeFieldResult fieldResult2 = Reclamation_Detail__c.Mistmatch_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple2 = fieldResult2.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple2){			
            valueSubTypeMap.put(pickListVal.getLabel(),Integer.valueOf(pickListVal.getValue()));
		}
                                                       
        return valueSubTypeMap;
    }
}