force-app/main/default/objects/OpportunityLineItem/fields/CDD__c.field-meta.xml
<CustomField>
    <fullName>CDD__c</fullName>
    <description>Critical Date of Dispatch (the last date when the mill has to dispatch the products from the shop).</description>
    <inlineHelpText>Critical Date of Dispatch (the last date when the mill has to dispatch the products from the shop).</inlineHelpText>
    <label>CDD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinalCDD__c.field-meta.xml
<CustomField>
    <fullName>FinalCDD__c</fullName>
    <formula>IF(ISBLANK(ConfirmedCDD__c), CDD__c, ConfirmedCDD__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final CDD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PriceApprovalRequestItem__c/PriceApprovalRequestItem__c.object-meta.xml
<CustomObject>
    <label>Price Approval Request Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Approval Request Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PriceApprovalRequestItem__c/fields/OpportunityLineItemId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItemId__c</fullName>
    <label>Opportunity Product</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PARItemsUpdateCDD.cls
global class PARItemsUpdateCDD implements Database.Batchable<SObject> {
	
    global Map<String,PriceApprovalRequestItem__c> oppIdToPARItems = new Map<String, PriceApprovalRequestItem__c>();
    global List<String> oppIdsFromPARItems = new List<String>();
    
    global PARItemsUpdateCDD() {
        List<PriceApprovalRequestItem__c> PARItems = [SELECT CDD__c, OpportunityLineItemId__c FROM PriceApprovalRequestItem__c WHERE OpportunityLineItemId__c != NULL AND CDD__c = NULL];
        for(PriceApprovalRequestItem__c parItem : PARItems){
            if(parItem.OpportunityLineItemId__c != null){
            	oppIdToPARItems.put(parItem.OpportunityLineItemId__c,parItem);
                oppIdsFromPARItems.add(parItem.OpportunityLineItemId__c);
            }
        }       
    }   
    
    global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator('SELECT Id, CDD__c, FinalCDD__c FROM OpportunityLineItem WHERE id in :oppIdsFromPARItems' );
	}
	
   	global void execute(Database.BatchableContext context, List<OpportunityLineItem> scope) {
			List<PriceApprovalRequestItem__c> PARItemsToUpdate = new List<PriceApprovalRequestItem__c>();
        for(OpportunityLineItem oli : scope){
            PriceApprovalRequestItem__c currentPARItem = oppIdToPARItems.get(oli.id);
            currentPARItem.CDD__c = oli.FinalCDD__c;
            PARItemsToUpdate.add(currentPARItem);
            system.debug(currentPARItem);
        }
        update PARItemsToUpdate;
	}
	
	
	global void finish(Database.BatchableContext context) {
       		
    }
}