force-app/main/default/objects/OpportunityLineItem/fields/QuotaType__c.field-meta.xml
<CustomField>
    <fullName>QuotaType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of quota that the item is related to.</description>
    <inlineHelpText>The type of production shop quota that the item is related to.</inlineHelpText>
    <label>Quota Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>QuotaType__c.Shop__c</field>
            <operation>equals</operation>
            <valueField>$Source.Shop__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotaType__c/QuotaType__c.object-meta.xml
<CustomObject>
    <description>Type of quota that is defined by production shop for particular sales manager</description>
    <label>Quota Type</label>
    <nameField>
        <label>Quota Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotas Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop_Quota__c/Shop_Quota__c.object-meta.xml
<CustomObject>
    <description>Production Quotas for a manual input from Sales Managers</description>
    <label>Shop Quota</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Shop Quota</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shop Quotas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop_Quota__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Production_Quotas_Sales_Managers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shop_Quota__c/fields/Quota_Type__c.field-meta.xml
<CustomField>
    <fullName>Quota_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Shop Quotas</relationshipLabel>
    <relationshipName>Production_Quotas_Sales_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteExtraShopQuotaOpportunity.cls
public class DeleteExtraShopQuotaOpportunity implements Queueable  {

    List<Id> shopQuotaExist = new List<Id>();
    Set<id> oppIdsForCheck = new Set<id>();
    Set<id> test = new Set<id>();
    
    public DeleteExtraShopQuotaOpportunity(Set<id> quotaTypesIds,  Set<Id> oppIds){
                
        this.test = quotaTypesIds;
        system.debug(quotaTypesIds);
        system.debug(oppIds);
        List<Shop_Quota__c> existingShopQuota = [SELECT Id                    
                    FROM Shop_Quota__c
                    WHERE Opportunity__c in :oppIds
                    AND Quota_Type__c in :quotaTypesIds];
        
        for(Shop_Quota__c sqe : existingShopQuota){
			this.shopQuotaExist.add(sqe.id) ;           
        }
               
        this.oppIdsForCheck = oppIds;
    }
    
    
    public void execute(QueueableContext context) { 
        Map<Id,List<OpportunityLineItem>> oppLi = new Map<Id,List<OpportunityLineItem>>();
        for(OpportunityLineItem li : [select QuotaType__c,OpportunityId from OpportunityLineItem where OpportunityId in:this.oppIdsForCheck  ]){
            system.debug(li.QuotaType__c);
            if(oppLi.get(li.OpportunityId)==null){
                oppLi.put(li.OpportunityId,new List<OpportunityLineItem>());
            }
            List<OpportunityLineItem> updateList = oppLi.get(li.OpportunityId);
            updateList.add(li);
            oppLi.put(li.OpportunityId,updateList);
        }
        system.debug(oppLi);
        
        Map<Id,Set<id>> oppLiQuotasType = new Map<Id,Set<id>>();
        for(OpportunityLineItem li : [select QuotaType__c,OpportunityId from OpportunityLineItem where OpportunityId in:this.oppIdsForCheck  ]){
            system.debug(li.QuotaType__c);
            if(oppLiQuotasType.get(li.OpportunityId)==null){
                oppLiQuotasType.put(li.OpportunityId,new Set<id>());
            }
            Set<id> updateLista = oppLiQuotasType.get(li.OpportunityId);
            updateLista.add(li.QuotaType__c);
            oppLiQuotasType.put(li.OpportunityId,updateLista);
        }
        system.debug(oppLiQuotasType);
        
        Map<Id,List<Shop_Quota__c>> oppShopQuotass = new Map<Id,List<Shop_Quota__c>>();
        for(Shop_Quota__c sq : [SELECT Name,Opportunity__c,Quota_Type__c,Id,Quota_Type__r.Name FROM Shop_Quota__c WHERE Opportunity__c in:this.oppIdsForCheck ]){
            if(oppShopQuotass.get(sq.Opportunity__c)==null){
                oppShopQuotass.put(sq.Opportunity__c,new List<Shop_Quota__c>());
            }
            List<Shop_Quota__c> listToUpdate = oppShopQuotass.get(sq.Opportunity__c);
            listToUpdate.add(sq);
             oppShopQuotass.put(sq.Opportunity__c,listToUpdate);
        }
        system.debug(oppShopQuotass);
        
        List<Shop_Quota__c> shopQuotesToDelete = new  List<Shop_Quota__c>();
        for(Id idOpp : oppShopQuotass.keySet()){
            List<Shop_Quota__c> shopQuotaListCheck = oppShopQuotass.get(idOpp);
            Set<Id> oppQuotaTypeIds = oppLiQuotasType.get(idOpp);
            for(Shop_Quota__c sqc : shopQuotaListCheck){
                system.debug(sqc.Quota_Type__r.Name);
                system.debug(oppQuotaTypeIds);
                system.debug(sqc);
                if (oppQuotaTypeIds == null  && sqc.Quota_Type__r.Name == 'Not Added'){
                    shopQuotesToDelete.add(sqc);
                } else if(oppQuotaTypeIds != null && !oppQuotaTypeIds.contains(sqc.Quota_Type__c) && sqc.Quota_Type__r.Name == 'Not Added'){
                    shopQuotesToDelete.add(sqc);
                } 
            }                            
        }
        system.debug('');
        system.debug(shopQuotesToDelete);
        delete shopQuotesToDelete;
        /*
    	List<Shop_Quota__c> allShopQuotas = [SELECT id FROM Shop_Quota__c WHERE Opportunity__c in :this.oppIdsForCheck];
        List<Shop_Quota__c> shopQuotasForDelete = new List<Shop_Quota__c>();
        system.debug(this.oppIdsForCheck);
        system.debug(allShopQuotas);
        system.debug(this.shopQuotaExist);
        system.debug(this.test);
        
        if(this.shopQuotaExist.size()>0){
            for(Shop_Quota__c sq : allShopQuotas){
            if(!this.shopQuotaExist.contains(sq.id)){
                shopQuotasForDelete.add(sq);
                system.debug(shopQuotasForDelete);
            }
        }
        }
        
        system.debug(shopQuotasForDelete);
        delete shopQuotasForDelete;
*/
    }
}