force-app/main/default/objects/IPCams_Credentials__c/IPCams_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>IP Cams Credentials</label>
</CustomObject>

force-app/main/default/objects/IPCams_Credentials__c/fields/Login__c.field-meta.xml
<CustomField>
    <fullName>Login__c</fullName>
    <label>Login</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_IPCams_Setting__mdt/Site_IPCams_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Site IPCams Setting</label>
    <pluralLabel>Site IPCams Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Site_IPCams_Setting__mdt/fields/Camera_Id__c.field-meta.xml
<CustomField>
    <fullName>Camera_Id__c</fullName>
    <label>Camera Id</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Site_IPCams_Setting__mdt/fields/IP_Camera_URL__c.field-meta.xml
<CustomField>
    <fullName>IP_Camera_URL__c</fullName>
    <inlineHelpText>Example: https://motionntz.interpipe.biz/cam1</inlineHelpText>
    <label>IP Camera URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Site_IPCams_Setting__mdt/fields/Preview_IMG__c.field-meta.xml
<CustomField>
    <fullName>Preview_IMG__c</fullName>
    <description>Name of image from static resources</description>
    <inlineHelpText>Name of image from static resources</inlineHelpText>
    <label>Preview IMG</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SiteIPCamsController.cls
public with sharing class SiteIPCamsController {
    @AuraEnabled(cacheable=true)
    public static List<Site_IPCams_Setting__mdt> getCameraSettings() {
        return [SELECT MasterLabel, Camera_Id__c, IP_Camera_URL__c, Preview_IMG__c,Description__c FROM Site_IPCams_Setting__mdt];
    }
    @AuraEnabled(cacheable=true)
    public static String getCameraCredentials() {
        IPCams_Credentials__c creds = IPCams_Credentials__c.getOrgDefaults();
        if (creds != null) {
            return JSON.serialize(new Map<String, String>{
                'username' => creds.Login__c,
                'password' => creds.Password__c
            });
        }
        return null;
    }
}