force-app/main/default/objects/Order/fields/AdditionalNumber__c.field-meta.xml
<CustomField>
    <fullName>AdditionalNumber__c</fullName>
    <externalId>true</externalId>
    <label>Additional Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/DispatchedQuantity__c.field-meta.xml
<CustomField>
    <fullName>DispatchedQuantity__c</fullName>
    <label>Shipped (t)</label>
    <summarizedField>OrderItem.DispatchedQuantity__c</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.DispatchedQuantity__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/ProducedQuantity__c.field-meta.xml
<CustomField>
    <fullName>ProducedQuantity__c</fullName>
    <label>Produced (t)</label>
    <summarizedField>OrderItem.ProducedQuantity__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/ShippedQuantity__c.field-meta.xml
<CustomField>
    <fullName>ShippedQuantity__c</fullName>
    <label>Delivered acc to Incoterms (t)</label>
    <summarizedField>OrderItem.ShippedQuantity__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/TotalOrderQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalOrderQuantity__c</fullName>
    <label>Quantity (t)</label>
    <summarizedField>OrderItem.Quantity</summarizedField>
    <summaryFilterItems>
        <field>OrderItem.Quantity</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/SiteOrderDatatablePDFController.cls
public without sharing class SiteOrderDatatablePDFController {
    public List<Order> ordersList{get;set;}

    public SiteOrderDatatablePDFController() {
        system.debug(ApexPages.currentPage().getUrl());
        System.debug(ApexPages.currentPage().getParameters());
        String orderIds = ApexPages.currentPage().getParameters().get('Ids');
        List<Id> ids =(List<id>)  JSON.deserialize(orderIds, List<id>.class);
        this.ordersList = [SELECT AdditionalNumber__c, OrderNumber, EffectiveDate, Status, TotalOrderQuantity__c, ProducedQuantity__c, DispatchedQuantity__c,  ShippedQuantity__c 
                            FROM Order 
                            WHERE id in: ids LIMIT 100];   
    }

    
}