force-app/main/default/objects/Order/fields/AdditionalNumber__c.field-meta.xml
<CustomField>
    <fullName>AdditionalNumber__c</fullName>
    <externalId>true</externalId>
    <label>Additional Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/Reclamation_Detail__c.object-meta.xml
<CustomObject>
    <label>Reclamation Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Reclamation Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation_Detail__c/fields/ClaimQty__c.field-meta.xml
<CustomField>
    <fullName>ClaimQty__c</fullName>
    <label>Claim Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ClaimSum__c.field-meta.xml
<CustomField>
    <fullName>ClaimSum__c</fullName>
    <label>Claim Summary</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/Mistmatch_SubType__c.field-meta.xml
<CustomField>
    <fullName>Mistmatch_SubType__c</fullName>
    <label>Mistmatch SubType</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mistmatch_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2</fullName>
                <label>geometry</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>defects</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>marking / stamping</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>coating / packaging</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>mechanical damage</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>mechanical properties</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>chemical composition</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>documentation</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>quantity</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>delivery period</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>others</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>defects after machining</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>simple vehicle</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>delivery period (Logistic)</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>place of delivery (Logistic)</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>mechanical damage (Logistic)</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>marketable condition</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>salt</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>demerge</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>others (Logistic)</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>ordering</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>price</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>documentation (Commercial)</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>others (Commercial)</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>Vehicles downtime</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>BWW</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>production planning</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Error in order (planning)</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>technical expertise</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>others (Maintenance)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/Mistmatch_Type__c.field-meta.xml
<CustomField>
    <fullName>Mistmatch_Type__c</fullName>
    <label>Mistmatch Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Manufacturing</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Logistic</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>Commercial</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>Maintenance</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Exploitation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/Order_Additional_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Additional_Number__c</fullName>
    <label>Order Additional Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderItemID__c.field-meta.xml
<CustomField>
    <fullName>OrderItemID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product Number</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderQty__c.field-meta.xml
<CustomField>
    <fullName>OrderQty__c</fullName>
    <label>Order Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ReclID__c.field-meta.xml
<CustomField>
    <fullName>ReclID__c</fullName>
    <label>Reclamation ID</label>
    <referenceTo>Reclamation__c</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReclamationDetailGroupController.cls
public class ReclamationDetailGroupController {

    @AuraEnabled(cacheable=true)
    public static List<Reclamation_Detail__c> getReclamationDetail (Id recordId){
        
        List<Reclamation_Detail__c> reclamationDetailList = new List<Reclamation_Detail__c>();
        reclamationDetailList = [SELECT ITENumber__c, OrderItemID__r.Product2.Name,ClaimSum__c,ClaimQty__c,  OrderItemID__r.Name__c,CurrencyIsoCode,OrderID__r.AdditionalNumber__c,
                                 OrderQty__c,toLabel(Mistmatch_Type__c),toLabel(Mistmatch_SubType__c),PO_Number__c,Order_Additional_Number__c FROM Reclamation_Detail__c WHERE ReclID__c =: recordId];
        
        // Strip fields that are not readable      
		
        return reclamationDetailList;
    }
}