force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop</description>
    <inlineHelpText>Production shop</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProdPlan__c/OrderItemProdPlan__c.object-meta.xml
<CustomObject>
    <label>Order Item: Prod. Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items: Prod. Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemProdPlan__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Items: Prod. Plans</relationshipLabel>
    <relationshipName>Order_Items_Prod_Plans2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProdPlan__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Order_Items_Prod_Plans3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProdPlan__c/fields/ProdWeek__c.field-meta.xml
<CustomField>
    <fullName>ProdWeek__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProdWeek</label>
    <referenceTo>ProdWeeksH__c</referenceTo>
    <relationshipName>Order_Items_Prod_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProdPlan__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Items: Prod. Plans</relationshipLabel>
    <relationshipName>Order_Items_Prod_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProdPlan__c/fields/WeekNum__c.field-meta.xml
<CustomField>
    <fullName>WeekNum__c</fullName>
    <label>Week Num</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProdWeeksH__c/ProdWeeksH__c.object-meta.xml
<CustomObject>
    <label>Production Weeks</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Production Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdWeeksH__c/fields/WeekNum__c.field-meta.xml
<CustomField>
    <fullName>WeekNum__c</fullName>
    <label>Week Num</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderItemProdPlanBatch.cls
global class OrderItemProdPlanBatch implements Database.Batchable<sObject>, Database.Stateful {

    private Map<String, Id> weekMap = new Map<String, Id>(); // "Week-Month-Year" -> ProdWeekId

    global Database.QueryLocator start(Database.BatchableContext BC) {
    
        for (ProdWeeksH__c week : [SELECT Id, WeekNum__c, Month__c, Year__c FROM ProdWeeksH__c]) {
            String key = week.WeekNum__c + '-' + week.Month__c + '-' + week.Year__c;
            weekMap.put(key, week.Id);
        }

        return Database.getQueryLocator(
            'SELECT Id, ITENumber__c, WeekNum__c, Month__c, Year__c FROM OrderItemProdPlan__c' +
            ' WHERE Order__c = NULL OR OrderItem__c = NULL OR ProdWeek__c = NULL'
        );
    }
    
    global void execute(Database.BatchableContext BC, List<OrderItemProdPlan__c> prodPlans) {
        List<OrderItemProdPlan__c> updates = new List<OrderItemProdPlan__c>();
        Map<String, OrderItem> itemMap = new Map<String, OrderItem>();
        Set<String> itemNumbers = new Set<String>();

        for(OrderItemProdPlan__c plan : prodPlans) {
            if (plan.ITENumber__c != null) {
                itemNumbers.add(plan.ITENumber__c);
            }
        }

        for (OrderItem oi : [SELECT Id, ITENumber__c, OrderId, Shop__c FROM OrderItem WHERE ITENumber__c IN :itemNumbers]) {
            itemMap.put(oi.ITENumber__c, oi);
        }
        
        for (OrderItemProdPlan__c plan : prodPlans) {
            // 1. Знаходимо OrderItem і Order
            if (itemMap.containsKey(plan.ITENumber__c)) {
                OrderItem item = itemMap.get(plan.ITENumber__c);
                plan.OrderItem__c = item.Id;
                plan.Order__c = item.OrderId;
                plan.Shop__c = item.Shop__c;
            }
            
            // 2. Знаходимо ProdWeek
            String key = plan.WeekNum__c + '-' + plan.Month__c + '-' + plan.Year__c;
            if (weekMap.containsKey(key)) {
                plan.ProdWeek__c = weekMap.get(key);
            }
            
            updates.add(plan);
        }

        if (!updates.isEmpty()) {
            update updates;
        }
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Batch process completed.');
    }
}