force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/Reclamation__c.object-meta.xml
<CustomObject>
    <label>Reclamation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sended</fullName>
            </value>
            <value>
                <fullName>_1</fullName>
                <label>Registered</label>
            </value>
            <value>
                <fullName>_2</fullName>
                <label>Is being considered</label>
            </value>
            <value>
                <fullName>_8</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>_9</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>_5</fullName>
                <label>Director decision</label>
            </value>
            <value>
                <fullName>Accepted_PendingCompensation</fullName>
                <label>Accepted  (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially_PendingCompensation</fullName>
                <label>Accepted partially (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially</fullName>
                <label>Accepted partially</label>
            </value>
            <value>
                <fullName>OnHold</fullName>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/Reclamation_Detail__c.object-meta.xml
<CustomObject>
    <label>Reclamation Detail</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Reclamation Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation_Detail__c/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/OrderID__c.field-meta.xml
<CustomField>
    <fullName>OrderID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Number</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reclamation_Detail__c/fields/ReclID__c.field-meta.xml
<CustomField>
    <fullName>ReclID__c</fullName>
    <label>Reclamation ID</label>
    <referenceTo>Reclamation__c</referenceTo>
    <relationshipLabel>Reclamation Details</relationshipLabel>
    <relationshipName>Reclamation_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ReclamationDetailGroupControllerTest.cls
@isTest 
public class ReclamationDetailGroupControllerTest extends BaseTest {
	
    @isTest static void getReclamationDetailTest(){     
        
         Account testAccount = t.newAccounts('Test Account') [0];
		testAccount.ID_ERP__c = '1';
		testAccount.BillingCity = 'City';
		testAccount.BillingCountry = 'Ukraine';
		testAccount.BillingStreet = 'Street';
		testAccount.BillingPostalCode = '12345';
		testAccount.ShippingCity = 'ShipCity';
		testAccount.ShippingCountry = 'Ukraine';
		testAccount.ShippingStreet = 'ShipStreet';
		testAccount.ShippingPostalCode = '54321';
		testAccount.Description = 'Test';
        insert testAccount;
    
    Order testOrder = new Order();
        testOrder.AccountId = testAccount.id;
		testOrder.EffectiveDate = date.TODAY();
		testOrder.Status = 'Draft';        
    	testOrder.ID_ERP__c = '12312331';
        testOrder.ITENumber__c = '34324234';
   		insert testOrder;
        
        Reclamation__c newReclamation = new Reclamation__c(
        Status__c = 'Draft'
        );
        insert newReclamation;
        system.debug(newReclamation.Status__c );
        Reclamation_Detail__c newReclamationDetail = new Reclamation_Detail__c();
        newReclamationDetail.ReclID__c = newReclamation.id;
        newReclamationDetail.OrderID__c = testOrder.id;
        insert newReclamationDetail;
        
        t.start();            
 		ReclamationDetailGroupController.getReclamationDetail(newReclamation.id);
		t.stop();
                        
    }
    
    
    static { BaseTest.t = new ReclamationDetailGroupControllerTest(); }
	static BaseTest t { get { return BaseTest.t; } }
}