force-app/main/default/objects/CancelledOpportunityLineItem__c/CancelledOpportunityLineItem__c.object-meta.xml
<CustomObject>
    <description>Products that initially were in an opportunity but later were cancelled by some reason.</description>
    <label>Cancelled Opportunity Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cancelled Opportunity Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/InquiryQuantity__c.field-meta.xml
<CustomField>
    <fullName>InquiryQuantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/InquiryUnit__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnit__c</fullName>
    <label>Measurement Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/LengthSize__c.field-meta.xml
<CustomField>
    <fullName>LengthSize__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Length Size</label>
    <referenceTo>TubeLengthSize__c</referenceTo>
    <relationshipLabel>Cancelled Opportunity Products</relationshipLabel>
    <relationshipName>Cancelled_Opportunity_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Product Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/TubeOD__c.field-meta.xml
<CustomField>
    <fullName>TubeOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OD</label>
    <referenceTo>TubeOD__c</referenceTo>
    <relationshipLabel>Cancelled Opportunity Products</relationshipLabel>
    <relationshipName>Cancelled_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/TubeWT__c.field-meta.xml
<CustomField>
    <fullName>TubeWT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WT</label>
    <referenceTo>TubeWT__c</referenceTo>
    <relationshipLabel>Cancelled Opportunity Products</relationshipLabel>
    <relationshipName>CancelledProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CancelledOpportunityLineItem__c/fields/Weight_ppf__c.field-meta.xml
<CustomField>
    <fullName>Weight_ppf__c</fullName>
    <label>Weight (ppf)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cancel_reason__c.field-meta.xml
<CustomField>
    <fullName>Cancel_reason__c</fullName>
    <label>Cancel reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Out of product range/size</fullName>
            </value>
            <value>
                <fullName>Out of steel grade</fullName>
            </value>
            <value>
                <fullName>Out of standard</fullName>
            </value>
            <value>
                <fullName>Out of shipment conditions</fullName>
            </value>
            <value>
                <fullName>Client refusal</fullName>
            </value>
            <value>
                <fullName>Price not agreed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Cancel_reason__c.field-meta.xml
<CustomField>
    <fullName>Cancel_reason__c</fullName>
    <label>Cancel reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Out of size range</fullName>
            </value>
            <value>
                <fullName>Out of steel grade</fullName>
            </value>
            <value>
                <fullName>Out of product range</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Cancelled by ERP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryQuantity__c.field-meta.xml
<CustomField>
    <fullName>InquiryQuantity__c</fullName>
    <description>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</description>
    <inlineHelpText>Quantity in customer&apos;s inquiry (in customer&apos;s measurement units).</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InquiryUnit__c.field-meta.xml
<CustomField>
    <fullName>InquiryUnit__c</fullName>
    <description>Measuring unit for the product in the customer&apos;s inquiry.</description>
    <inlineHelpText>Measuring unit for the product in the customer&apos;s inquiry.</inlineHelpText>
    <label>Measurement Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>34</fullName>
                <label>t</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>m</label>
            </value>
            <value>
                <fullName>74</fullName>
                <label>ft</label>
            </value>
            <value>
                <fullName>43</fullName>
                <label>pcs</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LengthSize__c.field-meta.xml
<CustomField>
    <fullName>LengthSize__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tube length size</description>
    <inlineHelpText>Tube length size</inlineHelpText>
    <label>Length Size</label>
    <referenceTo>TubeLengthSize__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeOD__c.field-meta.xml
<CustomField>
    <fullName>TubeOD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube outside diameter</description>
    <inlineHelpText>Tube outside diameter</inlineHelpText>
    <label>OD</label>
    <referenceTo>TubeOD__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TubeWT__c.field-meta.xml
<CustomField>
    <fullName>TubeWT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Tube wall thickness</description>
    <inlineHelpText>Tube wall thickness</inlineHelpText>
    <label>WT</label>
    <referenceTo>TubeWT__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Weight_kpm__c.field-meta.xml
<CustomField>
    <fullName>Weight_kpm__c</fullName>
    <description>Pipe linear weight - kilograms per meter (kg/m)</description>
    <inlineHelpText>Pipe linear weight - kilograms per meter (kg/m)</inlineHelpText>
    <label>Linear Weight (kpm)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Weight_ppf__c.field-meta.xml
<CustomField>
    <fullName>Weight_ppf__c</fullName>
    <description>Pipe linear weight - pounds per foot (lb/ft)</description>
    <inlineHelpText>Pipe linear weight - pounds per foot (lb/ft)</inlineHelpText>
    <label>Linear Weight (ppf)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/TubeLengthSize__c.object-meta.xml
<CustomObject>
    <description>Possible tube length size</description>
    <label>Tube Length Size</label>
    <nameField>
        <label>Length Size Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tube Length Sizes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeLengthSize__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/MaxLength__c.field-meta.xml
<CustomField>
    <fullName>MaxLength__c</fullName>
    <description>Maximum length of the tube in millimeters</description>
    <inlineHelpText>Maximum length of the tube in millimeters</inlineHelpText>
    <label>Max Length</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/MinLength__c.field-meta.xml
<CustomField>
    <fullName>MinLength__c</fullName>
    <description>Minimal length of the tube in millimeters</description>
    <inlineHelpText>Minimal length of the tube in millimeters</inlineHelpText>
    <label>Min Length</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeLengthSize__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Typical size of the tube.</description>
    <inlineHelpText>Typical size of the tube.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R1</fullName>
            </value>
            <value>
                <fullName>R2</fullName>
            </value>
            <value>
                <fullName>R3</fullName>
            </value>
            <value>
                <fullName>DRL</fullName>
            </value>
            <value>
                <fullName>SRL</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TubeOD__c/TubeOD__c.object-meta.xml
<CustomObject>
    <description>Tube outside diameter</description>
    <label>Tube OD</label>
    <nameField>
        <label>Tube OD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes OD</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeOD__c/fields/OD_inch__c.field-meta.xml
<CustomField>
    <fullName>OD_inch__c</fullName>
    <description>Precise outside diameter in inches</description>
    <inlineHelpText>Precise outside diameter in inches</inlineHelpText>
    <label>inch</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeOD__c/fields/OD_mm__c.field-meta.xml
<CustomField>
    <fullName>OD_mm__c</fullName>
    <description>Precise outside diameter in millimeters</description>
    <inlineHelpText>Precise outside diameter in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/TubeWT__c.object-meta.xml
<CustomObject>
    <description>Tube wall thickness</description>
    <label>Tube WT</label>
    <nameField>
        <label>Tube WT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes WT</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeWT__c/fields/WT_inch__c.field-meta.xml
<CustomField>
    <fullName>WT_inch__c</fullName>
    <description>Precise wall thickness in inches</description>
    <inlineHelpText>Precise wall thickness in inches</inlineHelpText>
    <label>inch</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TubeWT__c/fields/WT_mm__c.field-meta.xml
<CustomField>
    <fullName>WT_mm__c</fullName>
    <description>Precise wall thickness in millimeters</description>
    <inlineHelpText>Precise wall thickness in millimeters</inlineHelpText>
    <label>mm</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel</fullName>
    </customValue>
    <customValue>
        <fullName>Tyre</fullName>
    </customValue>
    <customValue>
        <fullName>Axle</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel set</fullName>
    </customValue>
    <customValue>
        <fullName>Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Cookware</fullName>
    </customValue>
    <description>Our product types</description>
    <masterLabel>Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendPostFromFlowCancelledOppTest.cls
@isTest
public class SendPostFromFlowCancelledOppTest  extends BaseTest {

    @IsTest
    static void sendPostRestoreProductTest() {   
        
        Opportunity oppCancelled = [SELECT id FROM Opportunity LIMIT 1];
        String oppCancelledId = oppCancelled.id;
        List<String> test = new List<String>{oppCancelledId};
        SendPostFromFlowCancelledOpp.sendPost(test);
    }
    
    
     @testSetup
	static void testSetup() {

		Account testAccount = t.newAccounts('Test Account') [0];
		testAccount.ID_ERP__c = '1';
		testAccount.BillingCity = 'City';
		testAccount.BillingCountry = 'Ukraine';
		testAccount.BillingStreet = 'Street';
		testAccount.BillingPostalCode = '12345';
		testAccount.ShippingCity = 'ShipCity';
		testAccount.ShippingCountry = 'Ukraine';
		testAccount.ShippingStreet = 'ShipStreet';
		testAccount.ShippingPostalCode = '54321';
		testAccount.Description = 'Test';
		insert testAccount;


		Opportunity testOpp = t.newOpportunities('Test', testAccount.Id, 'Qualification', Date.today()) [0];
        testOpp.Cancel_reason__c = 'Client refusal';
		insert testOpp;

		Id pricebookId = Test.getStandardPricebookId();
		Product2 testProd1 = t.newProducts('Test product', '0000') [0];
		testProd1.ID_ERP__c = 'pr1';
		testProd1.Type__c = 'Tube';
        testProd1.Family = 'LP/GU';
		insert testProd1;
		Product2 testProd2 = t.newProducts('Test product2', '0001') [0];
		testProd2.ID_ERP__c = 'pr2';
		testProd2.Type__c = 'Tube';
        testProd2.Family = 'OCTG';
		insert testProd2;

		PricebookEntry testPriceBookEntry1 = new PricebookEntry(
		                                                        Pricebook2Id = pricebookId,
		                                                        Product2Id = testProd1.Id,
		                                                        UnitPrice = 1000.00,
		                                                        IsActive = true
		);
		insert testPriceBookEntry1;
		PricebookEntry testPriceBookEntry2 = new PricebookEntry(
		                                                        Pricebook2Id = pricebookId,
		                                                        Product2Id = testProd2.Id,
		                                                        UnitPrice = 1000.00,
		                                                        IsActive = true
		);
		insert testPriceBookEntry2;

		TubeOD__c od = new TubeOD__c(ID_ERP__c = 'od', OD_mm__c = 48.30, OD_inch__c = 1.9);
		insert od;

		TubeWT__c wt = new TubeWT__c(ID_ERP__c = 'wt', Name = 'TestWT', WT_mm__c = 5.08, WT_inch__c = 0.2);
		insert wt;

		TubeLengthSize__c size = new TubeLengthSize__c(ID_ERP__c = 'si', Name = 'testLS');
		size.MaxLength__c = 5800;
		size.MinLength__c = 5600;
		size.Type__c = 'R1';
		insert size;

		OpportunityLineItem testOppProd1 = t.newOpportunityProducts(testPriceBookEntry1.Id, testOpp.Id) [0];
		testOppProd1.InquiryUnit__c = '20';
		testOppProd1.InquiryQuantity__c = 18484.288;
		testOppProd1.TubeOD__c = od.Id;
		testOppProd1.TubeWT__c = wt.Id;
		testOppProd1.Weight_kpm__c = 5.41;
		testOppProd1.Weight_ppf__c = 3.63;
		testOppProd1.LengthSize__c = size.Id;
		testOppProd1.ID_ERP__c = '0001';
		testOppProd1.ProductType__c = 'Tube';
		testOppProd1.UnitPrice = testPriceBookEntry1.UnitPrice;
		testOppProd1.InquiryUnitPrice__c = 5.41;
        testOppProd1.Cancel_reason__c = 'Out of size range';
		insert testOppProd1;
		
        
        CancelledOpportunityLineItem__c cancelledToInsert = ERPMessageHandlerOrderItemStage.createCancelledOppProduct(testOppProd1);
        insert cancelledToInsert;
		
		}
    
    static { BaseTest.t = new SendPostFromFlowCancelledOppTest(); }
	static BaseTest t { get { return BaseTest.t; } }
}