force-app/main/default/objects/Account/fields/Activity_Type__c.field-meta.xml
<CustomField>
    <fullName>Activity_Type__c</fullName>
    <label>Activity Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Activity_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CountryId__c.field-meta.xml
<CustomField>
    <fullName>CountryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CountryId</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Accounts (CountryId)</relationshipLabel>
    <relationshipName>Account_CountryId</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/HoldingGroup__c.field-meta.xml
<CustomField>
    <fullName>HoldingGroup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holding Group</label>
    <referenceTo>AccountHoldingGroups__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms_v2__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms_v2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Payment Terms</label>
    <referenceTo>PaymentTerms__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <description>Invoice payment terms and conditions for the customer</description>
    <inlineHelpText>invoice payment terms and conditions for the customer</inlineHelpText>
    <label>Payment Terms (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/ClientLead__c/ClientLead__c.object-meta.xml
<CustomObject>
    <label>Client Lead</label>
    <nameField>
        <label>Potential Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client_Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientLead__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Client_Leads</relationshipLabel>
    <relationshipName>Client_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClientLead__c/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00002</fullName>
                <label>MENA</label>
            </value>
            <value>
                <fullName>00001</fullName>
                <label>Americas</label>
            </value>
            <value>
                <fullName>00004</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>00010</fullName>
                <label>CIS</label>
            </value>
            <value>
                <fullName>00011</fullName>
                <label>Ukraine</label>
            </value>
            <value>
                <fullName>00006</fullName>
                <label>KLW</label>
            </value>
            <value>
                <fullName>00016</fullName>
                <label>Customs Union</label>
            </value>
            <value>
                <fullName>00020</fullName>
                <label>ETA</label>
            </value>
            <value>
                <fullName>00021</fullName>
                <label>Machinery</label>
            </value>
            <value>
                <fullName>00019</fullName>
                <label>Vallourec</label>
            </value>
            <value>
                <fullName>00005</fullName>
                <label>IPS</label>
            </value>
            <value>
                <fullName>00100</fullName>
                <label>Steel</label>
            </value>
            <value>
                <fullName>00099</fullName>
                <label>Recycled Scrap</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related user in the ERP system (used for integration purposes)</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related user in the ERP system (used for integration purposes)</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Lead</label>
    <referenceTo>ClientLead__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <description>Any person outside our company (customer, partner, rival, etc.)</description>
    <label>External</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Lead_Contact.recordType-meta.xml
<RecordType>
    <fullName>Lead_Contact</fullName>
    <active>true</active>
    <label>Lead Contact</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/A2Code__c.field-meta.xml
<CustomField>
    <fullName>A2Code__c</fullName>
    <description>Country code according to ISO A2 codes for countries</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A2 codes for countries</inlineHelpText>
    <label>A2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/SysName__c.field-meta.xml
<CustomField>
    <fullName>SysName__c</fullName>
    <label>System Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/LeadDuplicateAcc__c.object-meta.xml
<CustomObject>
    <label>Lead Duplicate (Account)</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Autonumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Duplicates (Account)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LeadDuplicateAcc__c/fields/AccountNameIT__c.field-meta.xml
<CustomField>
    <fullName>AccountNameIT__c</fullName>
    <label>Account Name from IT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/fields/DuplicateAcc__c.field-meta.xml
<CustomField>
    <fullName>DuplicateAcc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lead Duplicates (Account)</relationshipLabel>
    <relationshipName>Lead_Duplicates_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/fields/JSONBody__c.field-meta.xml
<CustomField>
    <fullName>JSONBody__c</fullName>
    <label>JSON Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/fields/MainLead__c.field-meta.xml
<CustomField>
    <fullName>MainLead__c</fullName>
    <label>Main Lead</label>
    <referenceTo>ClientLead__c</referenceTo>
    <relationshipLabel>Lead Duplicates (Account)</relationshipLabel>
    <relationshipName>Lead_Duplicates_Account</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/fields/MatchIndex__c.field-meta.xml
<CustomField>
    <fullName>MatchIndex__c</fullName>
    <label>Match Index, %</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LeadDuplicateAcc__c/recordTypes/Convertion.recordType-meta.xml
<RecordType>
    <fullName>Convertion</fullName>
    <active>true</active>
    <label>Convertion</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Number of the order in the IT-Enterprise system</description>
    <externalId>true</externalId>
    <inlineHelpText>Number of the order in the IT-Enterprise system</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>ClientLead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_Lead_Rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payment terms for the opportunity</description>
    <inlineHelpText>Payment terms for the opportunity</inlineHelpText>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PaymentTerms__c.Obsolete__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTerms__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/New_Client_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>New_Client_Enquiry</fullName>
    <active>true</active>
    <businessProcess>RFP</businessProcess>
    <description>New Client`s Enquiry</description>
    <label>New Client`s Enquiry</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Tubes_RFP.recordType-meta.xml
<RecordType>
    <fullName>Tubes_RFP</fullName>
    <active>true</active>
    <businessProcess>RFP</businessProcess>
    <description>Request for Proposal (not tender)</description>
    <label>Tubes: Simple RFP</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Wheels_RFP.recordType-meta.xml
<RecordType>
    <fullName>Wheels_RFP</fullName>
    <active>true</active>
    <businessProcess>RFP</businessProcess>
    <description>Request for proposal (not tender)</description>
    <label>Wheels: Simple RFP</label>
</RecordType>

force-app/main/default/objects/SegmentAccount__c/SegmentAccount__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Segments Accounts</label>
</CustomObject>

force-app/main/default/objects/SegmentAccount__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Account_Activity_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Potential</fullName>
        <default>true</default>
        <label>Potential</label>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Banned</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Dormant</fullName>
        <isActive>false</isActive>
        <label>Dormant</label>
    </customValue>
    <customValue>
        <fullName>Freezed</fullName>
        <isActive>false</isActive>
        <label>Freezed</label>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
        <isActive>false</isActive>
        <label>Lost</label>
    </customValue>
    <customValue>
        <fullName>Not Active</fullName>
        <isActive>false</isActive>
        <label>Not Active</label>
    </customValue>
    <masterLabel>Account Activity Types</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PIA</fullName>
        <default>true</default>
        <label>PIA</label>
    </customValue>
    <customValue>
        <fullName>Net 7</fullName>
    </customValue>
    <customValue>
        <fullName>Net 10</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Letter of credit</fullName>
    </customValue>
    <description>Invoice payment terms and conditions</description>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadConvertion.cls
public with sharing class LeadConvertion {
    // --- TEST HOOKS ---
    @TestVisible static Boolean bypassSegmentCheck  = false;
    @TestVisible static Boolean bypassLicenseCheck  = false;
    @TestVisible static List<StringUtilsEx.MatchResult> testDuplicates = null;
    // -------------------

    // Прогрів рт лише потрібних sObject
    static {
        RecordTypeCache.primeFor(new Set<String>{ 'Opportunity', 'Contact', 'Account', 'LeadDuplicateAcc__c' }, false);
    }
    private static Id rtIdOpp  = RecordTypeCache.getId(Opportunity.SObjectType, 'New_Client_Enquiry');
    private static Id rtIdCont = RecordTypeCache.getId(Contact.SObjectType,     'Lead_Contact');
    private static Id rtIdAcc  = RecordTypeCache.getId(Account.SObjectType,     'Customer');

    // ---------- DTO ----------
    public class DataDTO {
        public String  OrderType;
        public String  OrderCurrency;
        public Header  Header;
    }
    public class Header {
        public Integer Undoc;
        public String  IteNumber;
        public String  AltNumber;
        public String  PONumber;
        public String  ID_SF;
        public Datetime CreatedDate;
        public Datetime OrderDate;
        public Acc     Account;

        public String  BusinessSegmentId;
        public Integer RegionId;
        public Integer CountryId;

        public PaymentTerms  PaymentTerms;
        public DeliveryTerms DeliveryTerms;
        public Person        SalesRep;
        public Person        BoSpecialist;

        public String  CrossMarket_BusinessSegment;
        public Person  CrossMarket_SalesRep;
        public Decimal CrossMarket_Percent;
    }
    public class Acc { public String Name; public Integer CountryId; public String Address; public String Id; }
    public class PaymentTerms { public String Name; public String Id; }
    public class DeliveryTerms { public String Name; public String Incoterms; public String Id; }
    public class Person { public String Name; public String UserId; public String Email; public String Id; }
    private class Envelope { public DataDTO Data; }

    public static DataDTO parseData(String jsonPayload) {
        Envelope env = (Envelope) JSON.deserialize(jsonPayload, Envelope.class);
        if (env == null || env.Data == null) {
            throw new AuraHandledException('JSON не містить вузла "Data".');
        }
        return env.Data;
    }
    public static DataDTO parseDataNodeOnly(String jsonPayload) {
        Map<String, Object> root = (Map<String, Object>) JSON.deserializeUntyped(jsonPayload);
        Object dataNode = root.get('Data');
        if (dataNode == null) {
            throw new AuraHandledException('JSON не містить вузла "Data".');
        }
        return (DataDTO) JSON.deserialize(JSON.serialize(dataNode), DataDTO.class);
    }

    // --------- Сегмент → вірт. акаунт ---------
    public static Map<String, Id> getSegmVirtAcc() {
        Map<String, Id> mapSegmAcc = new Map<String, Id>();
        List<SegmentAccount__c> listSA = [SELECT Name, ID_ERP__c FROM SegmentAccount__c];
        for (SegmentAccount__c sa : listSA) {
            Account acc = AccountRepository.getByErp(sa.ID_ERP__c);
            if (acc != null) mapSegmAcc.put(sa.Name, acc.Id);
        }
        return mapSegmAcc;
    }
    public static Id getVirtAccIdBySegm(String segment) {
        Map<String, Id> mapIds = getSegmVirtAcc();
        return mapIds.containsKey(segment) ? mapIds.get(segment) : null;
    }

    // --------- Пошук дублікатів по назві ---------
    public static List<StringUtilsEx.MatchResult> getAccountDuplicates(String sourceName, Decimal threshold) {
         // Тестовий інжектор дублікейтів
        if (Test.isRunningTest() && testDuplicates != null) {
            return testDuplicates;
        }      
        List<StringUtilsEx.MatchResult> matches = new List<StringUtilsEx.MatchResult>();
        if (String.isBlank(sourceName)) {
            System.debug('Source Name is incorrect');
            return matches;
        }
        if (threshold == null || threshold == 0.0 || threshold < 0 || threshold > 1.0) {
            System.debug('Parameter threshold was set to default value 0.8');
            threshold = 0.8;
        }
        IndexWeights idxWeights = IndexWeights.getDefault();
        WeightSet pairWeights   = WeightSet.getDefault();
        return NameSimilarityUtil.finalDuplicateCheck(
            Consts.FIND_BY_NAME,
            sourceName,
            false,
            '',
            null,
            threshold,
            false,
            idxWeights,
            pairWeights
        );
    }

    // --------- Результат конвертації ---------
    public class LeadConvertResult {
        public Boolean accResult;
        public Boolean oppResult;
        public Boolean contResult;
        public Boolean leadConverted;
        public LeadConvertResult() {
            accResult = false; oppResult = false; contResult = false; leadConverted = false;
        }
        public LeadConvertResult(Boolean a, Boolean o, Boolean c, Boolean l) {
            accResult = a; oppResult = o; contResult = c; leadConverted = l;
        }
    }

    // --------- Основний метод ---------
    public static LeadConvertResult convertLead(String payload) {
        LeadConvertResult result = new LeadConvertResult();
        DataDTO dataConv = parseDataNodeOnly(payload);

        if (dataConv == null) {
            System.debug('❌ ERROR: Data structure is invalid!');
            return result;
        }

        // Знаходимо “енквайрі” оппу (head)
        List<Opportunity> headList = [
            SELECT Id, ID_ERP__c, Lead__c, ITENumber__c
            FROM Opportunity
            WHERE Id = :dataConv.Header.ID_SF
            LIMIT 1
        ];
        if (headList.isEmpty()) {
            System.debug('❌ ERROR: Lead Enquiry is invalid!');
            return result;
        }
        Opportunity head = headList[0];

        ClientLead__c lead = LeadRepository.getById(head.Lead__c);
        if (lead == null) {
            System.debug('❌ ERROR: Lead ID is invalid!');
            return result;
        }

        // Дублікати акаунтів
        List<StringUtilsEx.MatchResult> matches = getAccountDuplicates(dataConv.Header.Account.Name, 0.85);
        if (!matches.isEmpty()) {
            List<LeadDuplicateAcc__c> ldaList = new List<LeadDuplicateAcc__c>();
            for (StringUtilsEx.MatchResult mr : matches) {
                ldaList.add(new LeadDuplicateAcc__c(
                    RecordTypeId        = RecordTypeCache.getId(LeadDuplicateAcc__c.SObjectType, 'Convertion'),
                    AccountNameIT__c    = dataConv.Header.Account.Name,
                    DuplicateAcc__c     = mr.account1Id,
                    MainLead__c         = lead.Id,
                    MatchIndex__c       = mr.matchIndex,
                    ID_ERP__c           = dataConv.Header.Account.Id,
                    JSONBody__c         = payload
                ));
            }
            if (!ldaList.isEmpty()) Database.insert(ldaList, false);

            // ── LOG: duplicates found (critical)
            Triton.instance.addEvent(
                TritonTypes.Level.ERROR,
                TritonTypes.Type.AccountDuplicates,
                TritonTypes.Area.LeadConversion,
                'Duplicate Accounts were found during Lead Conversion',
                payload
            );
            return result; // критично — дубль знайдено
        }

        // Перевіряємо сегмент (ERP код vs піктліст)
        Map<String, String> segmentsMap = SysUtils.getPicklistFieldMap('Account', 'MarketSegment__c', true);
        String segmentCandidate = dataConv.Header.BusinessSegmentId;
        // перевірка сегмента
        if (!segmentsMap.containsKey(segmentCandidate) && !bypassSegmentCheck) {
            System.debug('❌ ERROR: Market Segment is invalid (unknown ERP code): ' + segmentCandidate);
            return result;
        }

        // Власник
        User usr = UserRepository.getByLoginERP(dataConv.Header.SalesRep.UserId);
        if (usr == null) {
            // fallback — поточний користувач
            usr = [SELECT Id, Profile.UserLicense.Name FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        } else {
            // гарантуємо, що завантажили ліцензію профілю
            usr = [SELECT Id, Profile.UserLicense.Name FROM User WHERE Id = :usr.Id LIMIT 1];
        }

        // перевірка ліцензії
        if (usr.Profile.UserLicense.Name != 'Salesforce' && !bypassLicenseCheck) {
            System.debug('❌ ERROR: Wrong User Licence (is not Salesforce)!');
            return result;
        }

        // Країна
        Country__c country = CountryRepository.getByNumCode(String.valueOf(dataConv.Header.CountryId));
        if (country == null) {
            System.debug('❌ ERROR: Country is invalid!');
            return result;
        }

        // Довідники
        Id deliveryTermsId = null, paymentTermsId = null;
        List<DeliveryTerms__c> delivTerms = [
            SELECT Id FROM DeliveryTerms__c WHERE ID_ERP__c = :dataConv.Header.DeliveryTerms.Id LIMIT 1
        ];
        if (!delivTerms.isEmpty()) deliveryTermsId = delivTerms[0].Id;

        List<PaymentTerms__c> paymTerms = [
            SELECT Id FROM PaymentTerms__c WHERE ID_ERP__c = :dataConv.Header.PaymentTerms.Id LIMIT 1
        ];
        if (!paymTerms.isEmpty()) paymentTermsId = paymTerms[0].Id;

        // Створюємо акаунт
        Account acc = new Account(
            Name                = dataConv.Header.Account.Name,
            AccountSource       = 'Customer Event',
            CountryId__c        = country.Id,
            BillingCountry      = country.SysName__c,
            BillingCountryCode  = country.A2Code__c,
            BillingStreet       = dataConv.Header.Account.Address,
            MarketSegment__c    = segmentCandidate,
            OwnerId             = usr.Id,
            DeliveryTerms__c    = deliveryTermsId,
            Payment_Terms_v2__c = paymentTermsId,
            CurrencyIsoCode     = dataConv.OrderCurrency,
            Activity_Type__c    = 'Potential',
            HoldingGroup__c     = lead.Holding__c,
            ParentId            = lead.ParentAccount__c,
            Phone               = lead.Phone__c,
            Mobile__c           = lead.Mobile__c,
            Email__c            = lead.Email__c,
            Website             = lead.Web__c,
            Type                = 'End User',
            RecordTypeId        = rtIdAcc,
            ID_ERP__c           = dataConv.Header.Account.Id
        );

        Database.SaveResult accSr = Database.insert(acc, false);
        if (!accSr.isSuccess()) {
            System.debug('❌ ERROR: Account creation was unsuccessful!');
            // ── LOG: account creation failed
            Triton.instance.addError(
                TritonTypes.Type.DMLResult,
                TritonTypes.Area.LeadConversion,
                'Account creation was unsuccessful',
                'Account Name: ' + dataConv.Header.Account.Name
            );
            return result;
        }
        result.accResult = true;
        Id newAccId = accSr.getId();

        // Мапа RT для опп
        String division = (dataConv.OrderType == null ? '' : dataConv.OrderType.trim().toUpperCase());
        String oppTargetRtDevName = (division == 'TUBES') ? 'Tubes_RFP' : 'Wheels_RFP';

        // Перекодовуємо оппи, створені як Enquiry
        List<Opportunity> oppList = [
            SELECT Id, RecordTypeId, Status__c, AccountId
            FROM Opportunity
            WHERE Lead__c = :lead.Id
              AND RecordTypeId = :rtIdOpp
        ];
        if (!oppList.isEmpty()) {
            Id newOppRtId = RecordTypeCache.getId(Opportunity.SObjectType, oppTargetRtDevName);
            for (Opportunity o : oppList) {
                o.RecordTypeId = (newOppRtId != null ? newOppRtId : o.RecordTypeId);
                o.AccountId    = newAccId;
                o.Status__c    = 'Opportunity';
            }
            Database.SaveResult[] oppSrs = Database.update(oppList, false);
            Boolean ok = true;
            String errStr = '\n❌ ERROR: Opportunity update was unsuccessful!\nBad IDs:\n';
            for (Integer i = 0; i < oppSrs.size(); i++) {
                ok &= oppSrs[i].isSuccess();
                if (!oppSrs[i].isSuccess()) errStr += oppSrs[i].getId() + '\n';
            }
            if (!ok) {
                System.debug(errStr);
                // ── LOG: opportunity update failed
                Triton.instance.addError(
                    TritonTypes.Type.DMLResult,
                    TritonTypes.Area.LeadConversion,
                    'Opportunity update was unsuccessful',
                    errStr
                );
            } else {
                result.oppResult = true;
            }
        } else {
            System.debug('ℹ️ No Enquiry opportunities to update for lead ' + lead.Id);
        }

        // Контакти з ліда → акаунт
        List<Contact> contList = [
            SELECT Id, AccountId, RecordTypeId
            FROM Contact
            WHERE Lead__c = :lead.Id
              AND RecordTypeId = :rtIdCont
        ];
        if (!contList.isEmpty()) {
            Id externalRt = RecordTypeCache.getId(Contact.SObjectType, 'External');
            for (Contact c : contList) {
                c.AccountId    = newAccId;
                if (externalRt != null) c.RecordTypeId = externalRt;
            }
            Database.SaveResult[] contSrs = Database.update(contList, false);
            Boolean ok = true;
            String errStr = '\n❌ ERROR: Contacts update were unsuccessful!\nBad IDs:\n';
            for (Integer i = 0; i < contSrs.size(); i++) {
                ok &= contSrs[i].isSuccess();
                if (!contSrs[i].isSuccess()) errStr += contSrs[i].getId() + '\n';
            }
            if (!ok) {
                System.debug(errStr);
                // ── LOG: contacts update failed
                Triton.instance.addError(
                    TritonTypes.Type.DMLResult,
                    TritonTypes.Area.LeadConversion,
                    'Contacts update were unsuccessful',
                    errStr
                );
            } else {
                result.contResult = true;
            }
        } else {
            System.debug('ℹ️ No Lead_Contact contacts to update for lead ' + lead.Id);
        }

        // Фінал: відмічаємо лід як Converted, якщо все ОК
        if (result.accResult && result.oppResult && result.contResult) {
            lead.LeadStage__c = 'Converted';
            Database.SaveResult lSr = Database.update(lead, false);
            if (!lSr.isSuccess()) {
                System.debug('❌ ERROR: Lead Converted status update failed!');
                // ── LOG: lead status failed
                Triton.instance.addError(
                    TritonTypes.Type.DMLResult,
                    TritonTypes.Area.LeadConversion,
                    'Lead Converted status was unsuccessful',
                    'Lead Conversion was unsuccessful - Stage was not updated to Converted'
                );
            } else {
                result.leadConverted = true;
            }
        }
        return result;
    }
}