force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Current Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DealingStatus__c.field-meta.xml
<CustomField>
    <fullName>DealingStatus__c</fullName>
    <label>Dealing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DealingStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GroupPastDueDebt15More__c.field-meta.xml
<CustomField>
    <fullName>GroupPastDueDebt15More__c</fullName>
    <label>Group Past Due Debt (over 15 days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/GroupPastDueDebt__c.field-meta.xml
<CustomField>
    <fullName>GroupPastDueDebt__c</fullName>
    <label>Group Past Due Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PastDueDebt15More__c.field-meta.xml
<CustomField>
    <fullName>PastDueDebt15More__c</fullName>
    <label>Past Due Debt (over 15 days)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PastDueDebt__c.field-meta.xml
<CustomField>
    <fullName>PastDueDebt__c</fullName>
    <label>Past Due Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DealingStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>OK</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Blocked</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>To be blocked</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Restricted</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Group Block</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Ignore Debt</label>
    </customValue>
    <masterLabel>Dealing Statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountsBlockedUpdate.cls
global class AccountsBlockedUpdate implements Database.Batchable<SObject> {
	global Set<String> accIdErpSet = new Set<String>();
    
    global AccountsBlockedUpdate(Set<String> accIdSet) {
        system.debug(accIdSet);
        accIdErpSet = accIdSet;
    }
    
    global Database.QueryLocator start(Database.BatchableContext context) {
		return Database.getQueryLocator('SELECT Id, ID_ERP__c, Name FROM Account WHERE Id_ERP__c not in :accIdErpSet AND (DealingStatus__c ='+'\'10\' OR '+'DealingStatus__c ='+'\'40\')' );
	}
    
    global void execute(Database.BatchableContext context, List<Account> scope) {
		system.debug(accIdErpSet);
        List<Account> accListToUpdate = new List<Account>();
        for (Account acc : scope) {
            acc.Balance__c = 0;
            acc.PastDueDebt__c = 0;
            acc.PastDueDebt15More__c = 0;
            acc.GroupPastDueDebt__c = 0;
            acc.GroupPastDueDebt15More__c = 0;  
            acc.DealingStatus__c = '0';
            accListToUpdate.add(acc);
        }
        update accListToUpdate;

	}
    
    global void finish(Database.BatchableContext context) {
		
	}
}