force-app/main/default/objects/Account/fields/BlockDate__c.field-meta.xml
<CustomField>
    <fullName>BlockDate__c</fullName>
    <label>Block Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DealingStatus__c.field-meta.xml
<CustomField>
    <fullName>DealingStatus__c</fullName>
    <label>Dealing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DealingStatuses</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PastDueDebt__c.field-meta.xml
<CustomField>
    <fullName>PastDueDebt__c</fullName>
    <label>Past Due Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/DealingStatuses.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>OK</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Blocked</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>To be blocked</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Restricted</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Group Block</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Ignore Debt</label>
    </customValue>
    <masterLabel>Dealing Statuses</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExperienceCloudShowToastEventController.cls
public with sharing class ExperienceCloudShowToastEventController {
    @AuraEnabled(cacheable=true)
    public static List<Account> getCustomerComunityUserAccount() {

        List<User> u = [SELECT Name, AccountId FROM User WHERE Id = :UserInfo.getUserId()];
        System.debug('accId = ' + u[0].AccountId);
        Id accountId = u[0].AccountId;
        return [SELECT Name, DealingStatus__c, PastDueDebt__c, CurrencyIsoCode, BlockDate__c FROM Account WHERE id =: accountId];
    }
}