force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerEnquiry__c/CustomerEnquiry__c.object-meta.xml
<CustomObject>
    <description>This object is used as an alternative to the Opportunity in Customer Communities.</description>
    <label>Customer Enquiry</label>
    <nameField>
        <displayFormat>{YYYY}-{00000}</displayFormat>
        <label>Enquiry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Enquiries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerEnquiry__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Enquiries</relationshipLabel>
    <relationshipName>Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Customer Enquiries</relationshipLabel>
    <relationshipName>Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Briefly describe your enquiry (what products do you need, amount, terms, etc.)</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/MeasurementUnit__c.field-meta.xml
<CustomField>
    <fullName>MeasurementUnit__c</fullName>
    <label>Measurement Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MeasurementUnits</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Customer Enquiries</relationshipLabel>
    <relationshipName>Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Customer Enquiries</relationshipLabel>
    <relationshipName>Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/SalesRepId__c.field-meta.xml
<CustomField>
    <fullName>SalesRepId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A contact person assigned for processing this enquiry</inlineHelpText>
    <label>Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <valueField>$User.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Customer_Enquiries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Draft&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/TotalQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantity__c</fullName>
    <label>Total Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerEnquiry__c/fields/TotalQuantity_t__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantity_t__c</fullName>
    <description>Total quantity of products in metric tons.</description>
    <inlineHelpText>Total quantity of products in metric tons.</inlineHelpText>
    <label>Total Quantity (t)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Number of the order in the IT-Enterprise system</description>
    <externalId>true</externalId>
    <inlineHelpText>Number of the order in the IT-Enterprise system</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/MeasurementUnits.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>34</fullName>
        <default>true</default>
        <label>t</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>m</label>
    </customValue>
    <customValue>
        <fullName>43</fullName>
        <label>pcs</label>
    </customValue>
    <customValue>
        <fullName>74</fullName>
        <label>ft</label>
    </customValue>
    <customValue>
        <fullName>962</fullName>
        <label>hour</label>
    </customValue>
    <description>Product measurement units.</description>
    <masterLabel>Measurement Units</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EnquiryDatatableController.cls
public without sharing class EnquiryDatatableController {

    @AuraEnabled(cacheable = true)
    public static List <CustomerEnquiry__c> getEnquiries() {
        try {
            String userId = UserInfo.getUserId();
            String idContactUser = [SELECT Contactid FROM User WHERE Id =: userId LIMIT 1].contactid;
            system.debug(idContactUser);
            String accId = [SELECT id, AccountId FROM Contact WHERE id =: idContactUser LIMIT 1].AccountId;
            List<Account> childAccounts = [SELECT Id FROM Account WHERE ParentId = :accId];
            Set<Id> accountIdSet = new Set<Id>{accId};

            if(!childAccounts.isEmpty()) {
                for(Account childAccount : childAccounts) {
                    accountIdSet.add(childAccount.Id);
                }
            }

            return [SELECT Name, AccountId__c, CreatedDate, Status__c, SalesRepId__c, SalesRepId__r.Name, CreatedBy.Name, OrderId__r.ITENumber__c, OpportunityId__r.StageName
                FROM CustomerEnquiry__c
                WHERE AccountId__c IN :accountIdSet
                ORDER BY CreatedDate desc
            ];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable = true)
    public static CustomerEnquiry__c getEnquiriyDetail(String enqId) {
        try {
            String userId = UserInfo.getUserId();
            String idContactUser = [SELECT Contactid FROM User WHERE Id =: userId LIMIT 1].contactid;
            String accId = [SELECT id, AccountId FROM Contact WHERE id =: idContactUser LIMIT 1].AccountId;
            List<Account> childAccounts = [SELECT Id FROM Account WHERE ParentId = :accId];
            Set<Id> accountIdSet = new Set<Id>{accId};

            if(!childAccounts.isEmpty()) {
                for(Account childAccount : childAccounts) {
                    accountIdSet.add(childAccount.Id);
                }
            }

            return [SELECT Name, AccountId__c, Country__r.Name, TotalQuantity__c, TotalQuantity_t__c, toLabel(MeasurementUnit__c), Description__c, CreatedDate, Status__c,
                SalesRepId__c, SalesRepId__r.Name, CreatedBy.Name, OrderId__r.ITENumber__c, OpportunityId__r.StageName, RecordType.DeveloperName, RecordTypeId
                FROM CustomerEnquiry__c
                WHERE AccountId__c IN :accountIdSet
                AND id =: enqId
                ORDER BY CreatedDate desc
            ];

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable = false)
    public static List < ContentDocumentLink > getEnquiryFiles(String enqId) {
        try {
            String userId = UserInfo.getUserId();
            List <ContentDocument> conDoc = [SELECT Title, id, ContentModifiedDate, OwnerId, ContentSize FROM ContentDocument WHERE OwnerId =: userId];
            List <ContentDocumentLink> conLink = [SELECT ContentDocumentId, ContentDocument.Title,
                ContentDocument.Owner.Name,
                ContentDocument.ContentModifiedDate,
                ContentDocument.ContentSize, LinkedEntityId
                FROM ContentDocumentLink
                WHERE LinkedEntityId in
                (SELECT Id FROM CustomerEnquiry__c WHERE id =: enqId) //reclamation Id
                AND ContentDocumentId in: conDoc
            ];
            
            return conLink;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static String viewFile(String cdl) {
        try {
            Id contentDocId = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE id =: cdl LIMIT 1].ContentDocumentId;
            List <ContentVersion> cv = [SELECT id, PathOnClient, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId =: contentDocId];

            ContentDistribution cd = new ContentDistribution();
            cd.ContentVersionId = cv[0].Id;
            cd.PreferencesNotifyOnVisit = false;
            cd.Name = cv[0].PathOnClient;
            cd.PreferencesAllowViewInBrowser = true;
            insert cd;

            return [SELECT DistributionPublicUrl FROM ContentDistribution WHERE Id =: cd.Id].DistributionPublicUrl;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled
    public static String generatePdf(String selectedEnquiries) {
        try {
            PageReference pdfPage = Page.siteEnquiryDatatablePDF;
            pdfPage.getParameters().put('Ids', selectedEnquiries);
            Blob outletListBlob = pdfPage.getContentAsPDF();


            ContentVersion cv = new ContentVersion();
            cv.Title = 'Enquiry Document';
            cv.PathOnClient = 'EnquiryDocument.pdf';
            cv.VersionData = outletListBlob;
            insert cv;


            ContentDistribution cdl = new ContentDistribution();
            cdl.ContentVersionId = cv.Id;
            cdl.PreferencesNotifyOnVisit = false;
            cdl.Name = cv.PathOnClient;
            cdl.PreferencesAllowViewInBrowser = true;
            insert cdl;

            return [SELECT DistributionPublicUrl FROM ContentDistribution WHERE Id =: cdl.Id].DistributionPublicUrl;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void attachFilesToOpportunity(String enqId) {


        String userId = UserInfo.getUserId();
        List <ContentDocumentLink> linksFile = new List < ContentDocumentLink > ();
        String oppId = [SELECT OpportunityId__c FROM CustomerEnquiry__c WHERE Id =: enqId].OpportunityId__c;
        List <ContentDocument> conDoc = [SELECT Title, id, ContentModifiedDate, OwnerId, ContentSize FROM ContentDocument WHERE OwnerId =: userId];

        List <ContentDocumentLink> conLink = [SELECT ContentDocumentId, ContentDocument.Title,
            ContentDocument.Owner.Name,
            ContentDocument.ContentModifiedDate,
            ContentDocument.ContentSize, LinkedEntityId
            FROM ContentDocumentLink
            WHERE LinkedEntityId in
            (SELECT Id FROM CustomerEnquiry__c WHERE id =: enqId)
            AND ContentDocumentId in: conDoc
        ];

        for(ContentDocumentLink c: conLink) {
            ContentDocumentLink cdl = new ContentDocumentLink(); // Content Document Link to share the file with Opportunity(Parent) record
            cdl.LinkedEntityId = oppId; // Opportunity ID
            cdl.ContentDocumentId = c.ContentDocumentId; //Content Dcoument ID
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            linksFile.add(cdl);
        }
        insert linksFile;
    }

    public static void FakeCoverageMethod() {
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}