force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/A2Code__c.field-meta.xml
<CustomField>
    <fullName>A2Code__c</fullName>
    <description>Country code according to ISO A2 codes for countries</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A2 codes for countries</inlineHelpText>
    <label>A2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/A3Code__c.field-meta.xml
<CustomField>
    <fullName>A3Code__c</fullName>
    <description>Country code according to ISO A3 codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A3 codes for countries.</inlineHelpText>
    <label>A3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/NumCode__c.field-meta.xml
<CustomField>
    <fullName>NumCode__c</fullName>
    <description>Country code according to ISO numeric codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO numeric codes for countries.</inlineHelpText>
    <label>Numeric Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Number of the order in the IT-Enterprise system</description>
    <externalId>true</externalId>
    <inlineHelpText>Number of the order in the IT-Enterprise system</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>Number of the related order item in the IT-Enterprise system.</description>
    <inlineHelpText>Number of the related order item in the IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ProductStandard__c.field-meta.xml
<CustomField>
    <fullName>ProductStandard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Technical standard that defines requirements to the product</description>
    <inlineHelpText>Technical standard that defines requirements to the product</inlineHelpText>
    <label>Product Standard</label>
    <referenceTo>ProductStandard__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop that will produce this product</description>
    <inlineHelpText>Production shop that will produce this product</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SteelGrade__c.field-meta.xml
<CustomField>
    <fullName>SteelGrade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Steel grade</description>
    <inlineHelpText>Steel grade</inlineHelpText>
    <label>Steel Grade</label>
    <referenceTo>SteelGrade__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ProductStandard__c.field-meta.xml
<CustomField>
    <fullName>ProductStandard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Standard</label>
    <referenceTo>ProductStandard__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop</description>
    <inlineHelpText>Production shop</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <description>Production plants</description>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Shop__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in ERP system</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in ERP system</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TubeEnds__c/TubeEnds__c.object-meta.xml
<CustomObject>
    <description>Tube ends</description>
    <label>Tube Ends</label>
    <nameField>
        <label>Tube Ends Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tubes Ends</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TubeEnds__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&quot;PE&quot;</defaultValue>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NU</fullName>
            </value>
            <value>
                <fullName>EU</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>STD</fullName>
            </value>
            <value>
                <fullName>NO CROPPING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UserID_ERP__c/UserID_ERP__c.object-meta.xml
<CustomObject>
    <description>A user&apos;s actual or old ID code in ERP system. List of particular user&apos;s IDs is used for integration purposes, because user&apos;s ID in ERP system can change on occasions.</description>
    <label>User ID in ERP</label>
    <nameField>
        <label>User ID in ERP</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User IDs in ERP</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/UserID_ERP__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_ID_ERP_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Tube</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel</fullName>
    </customValue>
    <customValue>
        <fullName>Tyre</fullName>
    </customValue>
    <customValue>
        <fullName>Axle</fullName>
    </customValue>
    <customValue>
        <fullName>Wheel set</fullName>
    </customValue>
    <customValue>
        <fullName>Centre</fullName>
    </customValue>
    <customValue>
        <fullName>Cookware</fullName>
    </customValue>
    <description>Our product types</description>
    <masterLabel>Product Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERPMessageHandlerOrderItemStageTest.cls
@isTest
public class ERPMessageHandlerOrderItemStageTest  extends BaseTest {

      
    @isTest static void updateOppOrderRecordsTest(){
      
		
        String receivedBody = ' {"Metadata": {"MsgType": "ERP-SF_OrderItemStage","MsgTypeVersion": 0.0,"MsgTimestamp": "2022-02-13T12:48:06.8509695+02:00","PartNumber": 1,"TotalParts": 1},"Data": { "Undoc": 1335452,"Npp": 1,"Stage": "_12"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
    
        req.requestURI = '/ERPtoSF/v1/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(receivedBody);
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();       
        ERPtoSF.postCST();
        Test.stopTest();
        
       
    }
    
    @isTest static void cancelOpportunityTest(){
      
		
        String receivedBody = ' {"Metadata": {"MsgType": "ERP-SF_OrderItemStage","MsgTypeVersion": 0.0,"MsgTimestamp": "2022-02-13T12:48:06.8509695+02:00","PartNumber": 1,"TotalParts": 1},"Data": { "Undoc": 1335452,"Npp": 1,"Stage": "_5"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
    
        req.requestURI = '/ERPtoSF/v1/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(receivedBody);
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();       
        ERPtoSF.postCST();
        Test.stopTest();
        
       
    }
    
    @isTest static void updateOppOrderRecordsUnknownStageTest(){
       
		
        String receivedBody = ' {"Metadata": {"MsgType": "ERP-SF_OrderItemStage","MsgTypeVersion": 0.0,"MsgTimestamp": "2022-02-13T12:48:06.8509695+02:00","PartNumber": 1,"TotalParts": 1},"Data": { "Undoc": 1335452,"Npp": 1,"Stage": "_56"}}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
    
        req.requestURI = '/ERPtoSF/v1/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueOf(receivedBody);
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();       
        ERPtoSF.postCST();
        Test.stopTest();
        
      
    }
    
   
    
    @testSetup static void testSetup() {
        List<Product2> prList = new List<Product2>();
            for(Integer i=0; i<3; i++){
                Product2 pr = t.newProducts('test'+i, '000')[0];
                if(i==0){
                    pr.Type__c = 'Tube';
                    pr.Family='OCTG';
                }
                else{
                    pr.Type__c = 'Wheel';
                }
                
                prList.add(pr);
            }
            insert prList;
            
            Account acc = t.newAccounts('Test Account')[0];
            insert acc;
            
           Id pricebookId = Test.getStandardPricebookId();
            
                // Insert Product
        Product2 p = new Product2();
        p.Name = ' Test Product ';
        p.Description='Test Product Entry 1';
        p.productCode = 'ABC';
        p.isActive = true;
        insert p;           
            // Insert PricebookEntry
    
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = p.Id;
        standardPrice.UnitPrice = 1;
        standardPrice.IsActive = true;
        standardPrice.UseStandardPrice = false;
        insert standardPrice ;
            
         Order orderTest = new Order(
                    AccountId = acc.Id,
                    EffectiveDate = system.today(),
                    EndDate = system.today() + 4,
                    Status = 'Draft',
                    Pricebook2Id =  pricebookId,
                    ID_ERP__c = '12312331',
                    ITENumber__c = '34324234'
            );
            insert orderTest;    
       
            Country__c country = new Country__c(Name = 'test', A2Code__c = '15', A3Code__c = '25', NumCode__c = '0');
        insert country;
    
        Shop__c shop_n_s = new Shop__c(Id_ERP__c = '0', Name = 'Not specified');
        insert shop_n_s;
    
        User newUser = t.newUser('john@acme.com');
        insert newUser;
    
        UserID_ERP__c user_id_in_erp = new UserID_ERP__c(Name = '54124', User__c = newUser.Id);
        insert user_id_in_erp;
    
        Account testAccount = t.newAccounts('Test Account') [0];
        testAccount.ID_ERP__c = '22449';
        insert testAccount;
    
        ProductStandard__c qStan = new ProductStandard__c();
        insert qStan;
    
        SteelGrade__c sGrade = new SteelGrade__c(ShortName__c = 'sg1');
        insert sGrade;
    
        TubeEnds__c tubeEnds = new TubeEnds__c(ShortName__c = 'EUE',Id_ERP__C='Г');
        insert tubeEnds;
    
        Plant__c plant = new Plant__c(FullName__c = 'Plant Full Name');
        insert plant;
        
        Shop__c shop = new Shop__c(Plant__c = plant.Id);
        insert shop;
        
        TubeOD__c tubeOD = new TubeOD__c(ID_ERP__c = '0H');
        insert tubeOD;
        
        TubeWT__c tubeWT = new TubeWT__c(ID_ERP__c = '2B');
        insert tubeWT;
        
        Opportunity testOpp = t.newOpportunities('Test', testAccount.Id, 'Qualification', Date.today()) [0];
        testOpp.ID_ERP__c = '1335452';
        
        insert testOpp;
                   
        List<Product2> prodList = new List<Product2>();
        Product2 testProd1 = t.newProducts('Test product', '0000') [0];
        testProd1.ID_ERP__c = 'tt';
        //testProd1.Family = 'OCTG';
        prodList.add(testProd1);
        Product2 testProd2 = t.newProducts('Test product2', '0001') [0];
        testProd2.ID_ERP__c = 'tq';
        //testProd2.Family = 'OCTG';
        prodList.add(testProd2);
        insert prodList;
    
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        PricebookEntry testPriceBookEntry1 = new PricebookEntry(
                                                                Pricebook2Id = pricebookId,
                                                                Product2Id = testProd1.Id,
                                                                UnitPrice = 100.00,
                                                                IsActive = true
        );
        pbeList.add(testPriceBookEntry1);
        PricebookEntry testPriceBookEntry2 = new PricebookEntry(
                                                                Pricebook2Id = pricebookId,
                                                                Product2Id = testProd2.Id,
                                                                UnitPrice = 200.00,
                                                                IsActive = true
        );
        pbeList.add(testPriceBookEntry2);
        insert pbeList;
    
        List<OpportunityLineItem> oplineItems = new List<OpportunityLineItem>();
    
        OpportunityLineItem testOppProd1 = t.newOpportunityProducts(testPriceBookEntry1.Id, testOpp.Id) [0];
        testOppProd1.Quantity = 3;
        testOppProd1.InquiryQuantity__c = 3;
        testOppProd1.InquiryUnit__c = '34';
        
        testOppProd1.NPP_ERP__c = '1';
        testOppProd1.ProductType__c = 'Tube';
        testOppProd1.TotalPrice = testPriceBookEntry1.UnitPrice;
        testOppProd1.SteelGrade__c = sGrade.Id;
        testOppProd1.TubeEnds__c = tubeEnds.Id;
        testOppProd1.Shop__c = shop.Id;
        testOppProd1.TubeOD__c = tubeOD.Id;
        //testOppProd1.ID_ERP__c = '12345';
       
	
		insert testOppProd1;
        OpportunityLineItem getInsertedOppItem = [SELECT ID_ERP__c FROM OpportunityLineItem WHERE id=:testOppProd1.id LIMIT 1];
        
        OrderItem i = new OrderItem();
            i.OrderId = orderTest.id;
            i.Quantity = 24;
            i.UnitPrice = 240;
            i.Product2id = p.id;
            i.PricebookEntryId=standardPrice.id;
        	i.ID_ERP__c = getInsertedOppItem.ID_ERP__c;
        insert i; 

	}
    
    static { BaseTest.t = new ERPMessageHandlerOrderItemStageTest(); }
    static BaseTest t { get { return BaseTest.t; } }
}