force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/BusinessDivision__c.field-meta.xml
<CustomField>
    <fullName>BusinessDivision__c</fullName>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessDivisions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/BusinessDivisions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pipes</fullName>
        <label>Pipe Products</label>
    </customValue>
    <customValue>
        <fullName>Railway</fullName>
        <label>Railway Products</label>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
        <label>Steel Products</label>
    </customValue>
    <customValue>
        <fullName>PRD</fullName>
        <label>Product &amp; Resource Dept.</label>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>IT Department</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>TOP</fullName>
        <label>Top Management</label>
    </customValue>
    <customValue>
        <fullName>DVM</fullName>
        <label>ДніпроВторМет</label>
    </customValue>
    <masterLabel>Business Divisions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomNewEnquiryControllerTest.cls
@isTest
public class CustomNewEnquiryControllerTest {
    
    public static String PROFILE_NAME = 'Customer Community User (Custom)';
    public static String PROFILE_NAME_ADMINISTRATOR = 'System Administrator';
    public static String COUNTRY_NAME = 'Andorra';
    public static String COUNTRY_A2CODE = 'AD';
    public static String COUNTRY_A3CODE = 'AND';
    public static String COUNTRY_NUMCODE = '20';
    
    @isTest
    static void testGetCustomerEnquiryRecTypes() {
        
        Test.startTest();
        List<CustomNewEnquiryController.RecordTypesWrapper> testRecTypesInfo = CustomNewEnquiryController.getCustomerEnquiryRecTypes();
        Test.stopTest();
        
        System.assert(testRecTypesInfo != null, 'Record Types List is NULL!');
        System.assert(!testRecTypesInfo.isEmpty(), 'Record Types List is EMPTY!');
    }
    
    @isTest
    static void testGetContactMailingCountry() {
                        
        User testUserAdmin = CustomNewEnquiryControllerTestFactory.createTestUserAdministrator(PROFILE_NAME_ADMINISTRATOR);
        insert testUserAdmin;
        
        System.runAs(testUserAdmin) {
            Country__c userContactCountry = CustomNewEnquiryControllerTestFactory.createUserContactCountry(COUNTRY_NAME, COUNTRY_A2CODE, COUNTRY_A3CODE, COUNTRY_NUMCODE);
            insert userContactCountry;
            
            Account userAccountQueried = CustomNewEnquiryControllerTestFactory.createUserAccount();
            
            Contact userContact = CustomNewEnquiryControllerTestFactory.createUserContact(userAccountQueried.Id, COUNTRY_NAME);
            insert userContact;
                               
        
            User testUser = CustomNewEnquiryControllerTestFactory.createTestUser(PROFILE_NAME, userContact.Id);
            testUser.ManagerId = testUserAdmin.id;
            insert testUser;
        
            Test.startTest();
            CustomNewEnquiryController.PrepolutateWrapper testPrepolutatedFieldValues = CustomNewEnquiryController.getContactMailingCountry(testUser.id);
            Test.stopTest();
            
            System.assertEquals(userContactCountry.Id, testPrepolutatedFieldValues.mailingCountryId, 'Incorrect Mailing Country ID');
            System.assertEquals(userAccountQueried.OwnerId, testPrepolutatedFieldValues.managerId, 'Incorrect Manager ID');
        }  
    }

    @isTest
    static void testGetBusinessDivision() {
                        
        User testUserAdmin = CustomNewEnquiryControllerTestFactory.createTestUserAdministrator(PROFILE_NAME_ADMINISTRATOR);
        insert testUserAdmin;
        
        System.runAs(testUserAdmin) {
            Country__c userContactCountry = CustomNewEnquiryControllerTestFactory.createUserContactCountry(COUNTRY_NAME, COUNTRY_A2CODE, COUNTRY_A3CODE, COUNTRY_NUMCODE);
            insert userContactCountry;
            
            Account userAccountQueried = CustomNewEnquiryControllerTestFactory.createUserAccount();
            
            Contact userContact = CustomNewEnquiryControllerTestFactory.createUserContact(userAccountQueried.Id, COUNTRY_NAME);
            insert userContact;

            AccountContactRelation acr = [SELECT Id FROM AccountContactRelation WHERE AccountId = :userAccountQueried.Id AND ContactId = :userContact.Id];
            acr.BusinessDivision__c = 'Pipes';
            update acr;
                               
            User testUser = CustomNewEnquiryControllerTestFactory.createTestUser(PROFILE_NAME, userContact.Id);
            testUser.ManagerId = testUserAdmin.id;
            insert testUser;
        
            Test.startTest();
            CustomNewEnquiryController.BusinessDivisionWrapper testBusinessDivisionWrapper = CustomNewEnquiryController.getBusinessDivision(testUser.id);
            Test.stopTest();
            
            System.assertEquals('Pipes', testBusinessDivisionWrapper.businessDivision, 'Incorrect Business Division');
            System.assertEquals(false, testBusinessDivisionWrapper.allDivisions, 'Incorrect All Divisions');
        }  
    }
    
}