force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related user in the ERP system (used for integration purposes)</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related user in the ERP system (used for integration purposes)</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/A2Code__c.field-meta.xml
<CustomField>
    <fullName>A2Code__c</fullName>
    <description>Country code according to ISO A2 codes for countries</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A2 codes for countries</inlineHelpText>
    <label>A2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/A3Code__c.field-meta.xml
<CustomField>
    <fullName>A3Code__c</fullName>
    <description>Country code according to ISO A3 codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A3 codes for countries.</inlineHelpText>
    <label>A3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/NumCode__c.field-meta.xml
<CustomField>
    <fullName>NumCode__c</fullName>
    <description>Country code according to ISO numeric codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO numeric codes for countries.</inlineHelpText>
    <label>Numeric Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/BusinesDivision__c.field-meta.xml
<CustomField>
    <fullName>BusinesDivision__c</fullName>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessDivisions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/LoginERP__c.field-meta.xml
<CustomField>
    <fullName>LoginERP__c</fullName>
    <description>User&apos;s login in the ERP system</description>
    <externalId>true</externalId>
    <label>Login in ERP</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/SalesDivision__c.field-meta.xml
<CustomField>
    <fullName>SalesDivision__c</fullName>
    <description>Sales division that user belongs to</description>
    <inlineHelpText>Sales division that user belongs to</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinesDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesDivisions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/BusinessDivisions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pipes</fullName>
        <label>Pipe Products</label>
    </customValue>
    <customValue>
        <fullName>Railway</fullName>
        <label>Railway Products</label>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
        <label>Steel Products</label>
    </customValue>
    <customValue>
        <fullName>PRD</fullName>
        <label>Product &amp; Resource Dept.</label>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>IT Department</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>TOP</fullName>
        <label>Top Management</label>
    </customValue>
    <customValue>
        <fullName>DVM</fullName>
        <label>ДніпроВторМет</label>
    </customValue>
    <masterLabel>Business Divisions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesDivisions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>SFAdmins</fullName>
        <label>Salesforce Admins</label>
    </customValue>
    <description>Sales divisions in our company</description>
    <masterLabel>Sales Divisions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomNewEnquiryControllerTestFactory.cls
@isTest
public with sharing class CustomNewEnquiryControllerTestFactory {
    public static Integer RANDOM_INT = Integer.valueOf(Math.rint(math.random()*1000000));
    
    public static Country__c createUserContactCountry(String countryName, String countryA2Code, String countryA3Code, String countryNumCode){
        
        Country__c userContactCountry = new Country__c(Name=countryName, A2Code__c=countryA2Code, A3Code__c=countryA3Code, NumCode__c=countryNumCode);
        return userContactCountry;
    }
    
    public static Account createUserAccount() {
        
        Account userAccount = new Account(Name = 'TestUserAccount' + String.valueOf(RANDOM_INT));
        insert userAccount;
        
        Account userAccountQueried = [SELECT Id, OwnerId FROM Account WHERE Id =: userAccount.Id LIMIT 1];
        return userAccountQueried;
    }
    
    public static Contact createUserContact(Id userAccountId, String userContactCountry) {
        
        Contact userContact = new Contact(AccountId=userAccountId, LastName='Test', MailingCountry=userContactCountry);
        return userContact;
    }    
	
    public static User createTestUser(String profileName, Id userContactId) {
        
        String testUserName = 'CustomNewEnquiryControllerTest' + String.valueOf(RANDOM_INT) + '@test.com';
        
        Profile p = [SELECT Id FROM Profile WHERE Name=:profileName];
        
        User testUser = New User(Alias='testAli', ContactId=userContactId, IsActive = true,  
                                 Email='testEmail@test.com', EmailEncodingKey='ISO-8859-1',
                                 LastName='testLastName', LanguageLocaleKey='en_US', LocaleSidKey='en_US', BusinesDivision__c = 'Pipes',
                                 ProfileId=p.Id, TimeZoneSidKey='America/New_York', Username=testUserName, SalesDivision__c = '00004');
		
        return testUser;
	}
    
    public static User createTestUserAdministrator(String profileName) {
        
        String testUserName = 'CustomNewEnquiryControllerTest' + String.valueOf(RANDOM_INT+1) + '@test.com';
        
        Profile p = [SELECT Id FROM Profile WHERE Name=:profileName];
        UserRole role = [Select Id, DeveloperName From UserRole Where DeveloperName = 'CEO' Limit 1];
        
        User testUser = New User(Alias='testAli', IsActive = true,  
                                 Email='testEmail@test.com', EmailEncodingKey='ISO-8859-1', UserRoleId = role.Id,
                                 LastName='testLastName', LanguageLocaleKey='en_US', LocaleSidKey='en_US', BusinesDivision__c = 'Pipes',
                                 ProfileId=p.Id, TimeZoneSidKey='America/New_York', Username=testUserName, SalesDivision__c = '00004',ID_ERP__c = 'TESTBO',                                
                                 EmployeeNumber = 'TESTBO',
                                 LoginERP__c = 'TESTBO');
		
        return testUser;
	}
}