force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/NumCode__c.field-meta.xml
<CustomField>
    <fullName>NumCode__c</fullName>
    <description>Country code according to ISO numeric codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO numeric codes for countries.</inlineHelpText>
    <label>Numeric Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/AssignedBOS__c.field-meta.xml
<CustomField>
    <fullName>AssignedBOS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned back office specialist</description>
    <inlineHelpText>Assigned back office specialist</inlineHelpText>
    <label>Assigned BO specialist</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>User.Profile.UserType</field>
            <operation>notEqual</operation>
            <value>CSPLitePortal</value>
        </filterItems>
        <filterItems>
            <field>User.SalesDivision__c</field>
            <operation>equals</operation>
            <valueField>$Source.MarketSegment__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.SalesDivision__c</field>
            <operation>equals</operation>
            <valueField>$Source.CrossMarketSegment__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities_AssignedBOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/AssignedBOS__c.field-meta.xml
<CustomField>
    <fullName>AssignedBOS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned BO Specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>New object for Regions from IT ERP</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/AssignedBOS__c.field-meta.xml
<CustomField>
    <fullName>AssignedBOS__c</fullName>
    <description>Assigned back office specialist.</description>
    <inlineHelpText>Assigned back office specialist. If selected, then it will be automatically selected by default in new opportunities of this user.</inlineHelpText>
    <label>Assigned BO Specialist</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Department</field>
            <operation>contains</operation>
            <value>Sales Support Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <relationshipName>SalesManagers</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>4</fullName>
        <label>Africa</label>
    </customValue>
    <customValue>
        <fullName>16</fullName>
        <label>Azerbaijan</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>Belarus</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>Brazil</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>Canada</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>Kazakhstan</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>Latin America</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>Middle East</label>
    </customValue>
    <customValue>
        <fullName>19</fullName>
        <label>Other CIS</label>
    </customValue>
    <customValue>
        <fullName>1</fullName>
        <label>Rest of the world</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>Russia</label>
    </customValue>
    <customValue>
        <fullName>17</fullName>
        <label>Turkmenistan</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>USA</label>
    </customValue>
    <customValue>
        <fullName>18</fullName>
        <label>Uzbekistan</label>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <label>Not specified</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Custom Union</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>India</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>Europe w/o Baltics</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>CIS &amp; Baltics</label>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityCsvQuickImport.cls
public with sharing class OpportunityCsvQuickImport {

    public class ImportError {
        public Integer rowNum;
        public String accountErp;
        public String ownerErp;
        public String assignedBosErp;
        public String countryNumCode;
        public String recordTypeDevName;
        public String opportunityName;
        public String message;

        public ImportError(
            Integer rowNum,
            String accountErp,
            String ownerErp,
            String assignedBosErp,
            String countryNumCode,
            String recordTypeDevName,
            String opportunityName,
            String message
        ) {
            this.rowNum = rowNum;
            this.accountErp = accountErp;
            this.ownerErp = ownerErp;
            this.assignedBosErp = assignedBosErp;
            this.countryNumCode = countryNumCode;
            this.recordTypeDevName = recordTypeDevName;
            this.opportunityName = opportunityName;
            this.message = message;
        }
    }

    public class ImportResult {
        public Integer totalRows = 0;
        public Integer successCount = 0;
        public Integer errorCount = 0;
        public List<ImportError> errors = new List<ImportError>();
    }

    public static ImportResult importFromLatestFileByTitle(String fileTitle, Boolean dryRun) {
        ContentVersion cv = [
            SELECT Id, Title, VersionData
            FROM ContentVersion
            WHERE Title = :fileTitle
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        String csvText = cv.VersionData.toString();
        return importFromCsv(csvText, dryRun);
    }

    public static ImportResult importFromCsv(String csvText, Boolean dryRun) {
        ImportResult result = new ImportResult();

        if (String.isBlank(csvText)) {
            throw new IllegalArgumentException('CSV is empty');
        }

        List<String> lines = csvText.replace('\r\n', '\n').replace('\r', '\n').split('\n');
        if (lines.isEmpty()) {
            throw new IllegalArgumentException('CSV is empty');
        }

        List<String> headers = parseCsvLine(lines[0]);
        Map<String, Integer> headerIndex = new Map<String, Integer>();
        for (Integer i = 0; i < headers.size(); i++) {
            headerIndex.put(headers[i].trim(), i);
        }

        List<Map<String, String>> rows = new List<Map<String, String>>();

        Set<String> accountErpIds = new Set<String>();
        Set<String> userErpIds = new Set<String>();
        Set<String> countryNumCodes = new Set<String>();
        Set<String> recordTypeNames = new Set<String>();

        for (Integer i = 1; i < lines.size(); i++) {
            String line = lines[i];
            if (String.isBlank(line)) {
                continue;
            }

            List<String> cols = parseCsvLine(line);
            Map<String, String> row = new Map<String, String>();

            for (String h : headerIndex.keySet()) {
                Integer idx = headerIndex.get(h);
                row.put(h, idx < cols.size() ? cols[idx].trim() : null);
            }

            rows.add(row);

            if (!String.isBlank(row.get('AccountId'))) {
                accountErpIds.add(row.get('AccountId'));
            }
            if (!String.isBlank(row.get('Owner'))) {
                userErpIds.add(row.get('Owner'));
            }
            if (!String.isBlank(row.get('AssignedBOS'))) {
                userErpIds.add(row.get('AssignedBOS'));
            }
            if (!String.isBlank(row.get('Country'))) {
                countryNumCodes.add(row.get('Country'));
            }
            if (!String.isBlank(row.get('RecordType'))) {
                recordTypeNames.add(row.get('RecordType'));
            }
        }

        result.totalRows = rows.size();

        Map<String, Account> accByErp = new Map<String, Account>();
        if (!accountErpIds.isEmpty()) {
            for (Account a : [
                SELECT Id, ID_ERP__c
                FROM Account
                WHERE ID_ERP__c IN :accountErpIds
            ]) {
                accByErp.put(a.ID_ERP__c, a);
            }
        }

        Map<String, User> userByErp = new Map<String, User>();
        if (!userErpIds.isEmpty()) {
            for (User u : [
                SELECT Id, ID_ERP__c
                FROM User
                WHERE ID_ERP__c IN :userErpIds
            ]) {
                userByErp.put(u.ID_ERP__c, u);
            }
        }

        Map<String, Country__c> countryByNumCode = new Map<String, Country__c>();
        if (!countryNumCodes.isEmpty()) {
            for (Country__c c : [
                SELECT Id, NumCode__c
                FROM Country__c
                WHERE NumCode__c IN :countryNumCodes
            ]) {
                countryByNumCode.put(c.NumCode__c, c);
            }
        }

        Map<String, Id> rtByDevName = new Map<String, Id>();
        if (!recordTypeNames.isEmpty()) {
            for (RecordType rt : [
                SELECT Id, DeveloperName
                FROM RecordType
                WHERE SObjectType = 'Opportunity'
                AND DeveloperName IN :recordTypeNames
                AND IsActive = true
            ]) {
                rtByDevName.put(rt.DeveloperName, rt.Id);
            }
        }

        List<Opportunity> oppsToInsert = new List<Opportunity>();
        List<Integer> sourceRowNums = new List<Integer>();
        List<Map<String, String>> sourceRowsForInsert = new List<Map<String, String>>();

        for (Integer i = 0; i < rows.size(); i++) {
            Integer rowNum = i + 2;
            Map<String, String> row = rows[i];

            try {
                Opportunity opp = new Opportunity();

                String accountErp = row.get('AccountId');
                if (String.isBlank(accountErp) || !accByErp.containsKey(accountErp)) {
                    throw new IllegalArgumentException('Account not found: ' + accountErp);
                }
                opp.AccountId = accByErp.get(accountErp).Id;

                String ownerErp = row.get('Owner');
                if (String.isBlank(ownerErp) || !userByErp.containsKey(ownerErp)) {
                    throw new IllegalArgumentException('Owner not found: ' + ownerErp);
                }
                opp.OwnerId = userByErp.get(ownerErp).Id;

                String bosErp = row.get('AssignedBOS');
                if (!String.isBlank(bosErp)) {
                    if (!userByErp.containsKey(bosErp)) {
                        throw new IllegalArgumentException('AssignedBOS not found: ' + bosErp);
                    }
                    opp.AssignedBOS__c = userByErp.get(bosErp).Id;
                }

                String countryNum = row.get('Country');
                if (!String.isBlank(countryNum)) {
                    if (!countryByNumCode.containsKey(countryNum)) {
                        throw new IllegalArgumentException('Country not found: ' + countryNum);
                    }
                    opp.Country__c = countryByNumCode.get(countryNum).Id;
                }

                String recordTypeDevName = row.get('RecordType');
                if (String.isBlank(recordTypeDevName) || !rtByDevName.containsKey(recordTypeDevName)) {
                    throw new IllegalArgumentException('RecordType not found: ' + recordTypeDevName);
                }
                opp.RecordTypeId = rtByDevName.get(recordTypeDevName);

                if (!String.isBlank(row.get('MarketSegment'))) {
                    opp.MarketSegment__c = row.get('MarketSegment');
                }

                if (!String.isBlank(row.get('Region'))) {
                    opp.Region__c = row.get('Region');
                }

                if (!String.isBlank(row.get('Name'))) {
                    opp.Name = row.get('Name');
                } else {
                    opp.Name = 'Imported Opportunity ' + rowNum;
                }

                if (!String.isBlank(row.get('StageName'))) {
                    opp.StageName = row.get('StageName');
                } else {
                    opp.StageName = 'Prospecting';
                }

                if (!String.isBlank(row.get('CloseDate'))) {
                    opp.CloseDate = Date.valueOf(row.get('CloseDate'));
                } else {
                    opp.CloseDate = Date.today();
                }

                oppsToInsert.add(opp);
                sourceRowNums.add(rowNum);
                sourceRowsForInsert.add(row);

            } catch (Exception e) {
                addError(result, rowNum, row, e.getMessage());
            }
        }

        if (!oppsToInsert.isEmpty()) {
            if (!dryRun) {
                Database.SaveResult[] srList = Database.insert(oppsToInsert, false);

                for (Integer i = 0; i < srList.size(); i++) {
                    if (srList[i].isSuccess()) {
                        result.successCount++;
                    } else {
                        result.errorCount++;
                        Map<String, String> sourceRow = sourceRowsForInsert[i];
                        for (Database.Error err : srList[i].getErrors()) {
                            addError(result, sourceRowNums[i], sourceRow, err.getMessage());
                        }
                    }
                }
            } else {
                System.debug('DRY RUN DATA:');
                System.debug(JSON.serializePretty(oppsToInsert));
                result.successCount = oppsToInsert.size();
            }
        }

        return result;
    }

    public static String buildErrorsCsv(ImportResult result) {
        List<String> lines = new List<String>();

        lines.add('RowNum,AccountId,Owner,AssignedBOS,Country,RecordType,Name,Message');

        if (result == null || result.errors == null || result.errors.isEmpty()) {
            return String.join(lines, '\n');
        }

        for (ImportError err : result.errors) {
            lines.add(
                csvCell(String.valueOf(err.rowNum)) + ',' +
                csvCell(err.accountErp) + ',' +
                csvCell(err.ownerErp) + ',' +
                csvCell(err.assignedBosErp) + ',' +
                csvCell(err.countryNumCode) + ',' +
                csvCell(err.recordTypeDevName) + ',' +
                csvCell(err.opportunityName) + ',' +
                csvCell(err.message)
            );
        }

        return String.join(lines, '\n');
    }

    public static Id saveErrorsCsvAsFile(String fileTitle, ImportResult result) {
        String csv = buildErrorsCsv(result);

        ContentVersion cv = new ContentVersion();
        cv.Title = fileTitle;
        cv.PathOnClient = fileTitle + '.csv';
        cv.VersionData = Blob.valueOf(csv);
        insert cv;

        return cv.Id;
    }

    private static void addError(
        ImportResult result,
        Integer rowNum,
        Map<String, String> row,
        String message
    ) {
        result.errorCount++;
        result.errors.add(new ImportError(
            rowNum,
            getRowValue(row, 'AccountId'),
            getRowValue(row, 'Owner'),
            getRowValue(row, 'AssignedBOS'),
            getRowValue(row, 'Country'),
            getRowValue(row, 'RecordType'),
            getRowValue(row, 'Name'),
            message
        ));
    }

    private static String getRowValue(Map<String, String> row, String key) {
        if (row == null || !row.containsKey(key)) {
            return null;
        }
        return row.get(key);
    }

    private static String csvCell(String value) {
        if (value == null) {
            value = '';
        }

        String escaped = value.replace('"', '""');
        return '"' + escaped + '"';
    }

    private static List<String> parseCsvLine(String line) {
        List<String> result = new List<String>();
        if (line == null) {
            return result;
        }

        String current = '';
        Boolean inQuotes = false;

        for (Integer i = 0; i < line.length(); i++) {
            String ch = line.substring(i, i + 1);

            if (ch == '"') {
                if (inQuotes && i + 1 < line.length() && line.substring(i + 1, i + 2) == '"') {
                    current += '"';
                    i++;
                } else {
                    inQuotes = !inQuotes;
                }
            } else if (ch == ',' && !inQuotes) {
                result.add(current);
                current = '';
            } else {
                current += ch;
            }
        }

        result.add(current);
        return result;
    }
}