force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>IF(FIND(&apos;,&apos;,BillingCountry)&gt;0, UPPER(MID(BillingCountry,1,FIND(&apos;,&apos;,BillingCountry)-1)), UPPER(BillingCountry))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <description>Invoice payment terms and conditions for the customer</description>
    <inlineHelpText>invoice payment terms and conditions for the customer</inlineHelpText>
    <label>Payment Terms (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClientLead__c/ClientLead__c.object-meta.xml
<CustomObject>
    <label>Client Lead</label>
    <nameField>
        <label>Potential Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client_Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClientLead__c/fields/BusinessDivision__c.field-meta.xml
<CustomField>
    <fullName>BusinessDivision__c</fullName>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pipes</fullName>
                <label>Pipe Products</label>
            </value>
            <value>
                <fullName>Railway</fullName>
                <label>Railway Products</label>
            </value>
            <value>
                <fullName>Steel</fullName>
                <label>Steel Products</label>
            </value>
            <value>
                <fullName>PRD</fullName>
                <label>Product &amp; Resource Dept.</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
                <label>IT Department</label>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>TOP</fullName>
                <label>Top Management</label>
            </value>
            <value>
                <fullName>DVM</fullName>
                <label>Recycled Scrap</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClientLead__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Client_Leads</relationshipLabel>
    <relationshipName>Client_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClientLead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contacted</fullName>
                <default>true</default>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClientLead__c/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinessDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00002</fullName>
                <label>MENA</label>
            </value>
            <value>
                <fullName>00001</fullName>
                <label>Americas</label>
            </value>
            <value>
                <fullName>00004</fullName>
                <label>Europe</label>
            </value>
            <value>
                <fullName>00010</fullName>
                <label>CIS</label>
            </value>
            <value>
                <fullName>00011</fullName>
                <label>Ukraine</label>
            </value>
            <value>
                <fullName>00006</fullName>
                <label>KLW</label>
            </value>
            <value>
                <fullName>00016</fullName>
                <label>Customs Union</label>
            </value>
            <value>
                <fullName>00020</fullName>
                <label>ETA</label>
            </value>
            <value>
                <fullName>00021</fullName>
                <label>Machinery</label>
            </value>
            <value>
                <fullName>00019</fullName>
                <label>Vallourec</label>
            </value>
            <value>
                <fullName>00005</fullName>
                <label>IPS</label>
            </value>
            <value>
                <fullName>00100</fullName>
                <label>Steel</label>
            </value>
            <value>
                <fullName>00099</fullName>
                <label>Recycled Scrap</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related user in the ERP system (used for integration purposes)</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related user in the ERP system (used for integration purposes)</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client Lead</label>
    <referenceTo>ClientLead__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lead_Contact.recordType-meta.xml
<RecordType>
    <fullName>Lead_Contact</fullName>
    <active>true</active>
    <label>Lead Contact</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>List of world countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/A2Code__c.field-meta.xml
<CustomField>
    <fullName>A2Code__c</fullName>
    <description>Country code according to ISO A2 codes for countries</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A2 codes for countries</inlineHelpText>
    <label>A2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/A3Code__c.field-meta.xml
<CustomField>
    <fullName>A3Code__c</fullName>
    <description>Country code according to ISO A3 codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO A3 codes for countries.</inlineHelpText>
    <label>A3 Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <formula>NumCode__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID in ERP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/fields/NumCode__c.field-meta.xml
<CustomField>
    <fullName>NumCode__c</fullName>
    <description>Country code according to ISO numeric codes for countries.</description>
    <externalId>true</externalId>
    <inlineHelpText>Country code according to ISO numeric codes for countries.</inlineHelpText>
    <label>Numeric Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country__c/fields/SysName__c.field-meta.xml
<CustomField>
    <fullName>SysName__c</fullName>
    <label>System Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DeliveryTerms__c/DeliveryTerms__c.object-meta.xml
<CustomObject>
    <label>Delivery Terms</label>
    <nameField>
        <label>Delivery Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Terms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country that products should be delivered to</description>
    <inlineHelpText>Country that products should be delivered to</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>ClientLead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities_Lead_Rel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payment terms for the opportunity</description>
    <inlineHelpText>Payment terms for the opportunity</inlineHelpText>
    <label>Payment Terms</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>PaymentTerms__c.Obsolete__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>PaymentTerms__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/New_Client_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>New_Client_Enquiry</fullName>
    <active>true</active>
    <businessProcess>RFP</businessProcess>
    <description>New Client`s Enquiry</description>
    <label>New Client`s Enquiry</label>
</RecordType>

force-app/main/default/objects/PaymentTerms__c/PaymentTerms__c.object-meta.xml
<CustomObject>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SegmentAccount__c/SegmentAccount__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Segments Accounts</label>
</CustomObject>

force-app/main/default/objects/SegmentAccount__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PIA</fullName>
        <default>true</default>
        <label>PIA</label>
    </customValue>
    <customValue>
        <fullName>Net 7</fullName>
    </customValue>
    <customValue>
        <fullName>Net 10</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Letter of credit</fullName>
    </customValue>
    <description>Invoice payment terms and conditions</description>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadConvertionTest.cls
@IsTest
private class LeadConvertionTest {

    // Хелпер: зібрати валідний 18-символьний Id для Account (префікс "001")
    private static Id fakeAccountId(Integer n) {
        String kp = Account.SObjectType.getDescribe().getKeyPrefix(); // "001"
        String num = String.valueOf(n);
        while (num.length() < 12) num = '0' + num;
        return (Id)(kp + num + 'AAA');
    }

    @IsTest
    static void test_convert_success_contacts_and_maybe_opps() {
        // вмикаємо гачки
        LeadConvertion.bypassSegmentCheck = true;
        LeadConvertion.bypassLicenseCheck = true;

        try {
            insert new Country__c(Name='UA test', SysName__c='Ukraine', A2Code__c='UA', A3Code__c='UKR', NumCode__c='804');
            insert new DeliveryTerms__c(Name='DT', ID_ERP__c='008');
            insert new PaymentTerms__c(Name='PT', ID_ERP__c='C33');

            ClientLead__c lead = new ClientLead__c(
                Name='Lead X',
                BusinessDivision__c = 'Pipes',  // Валідне значення з picklist
                MarketSegment__c = '00001'       // Ukraine
            );
            insert lead;

            // Очищаємо кеш, щоб LeadRepository знайшов щойно створений Lead
            LeadRepository.clearCache();

            Id rtOppEnquiry  = RecordTypeCache.getId(Opportunity.SObjectType, 'New_Client_Enquiry');
            Id rtContactLead = RecordTypeCache.getId(Contact.SObjectType,     'Lead_Contact');

            Opportunity o = new Opportunity(
                Name='Enquiry',
                StageName='Prospecting',
                CloseDate=Date.today().addDays(30),
                Lead__c=lead.Id,
                RecordTypeId=rtOppEnquiry
            );
            insert o;

            List<Contact> contacts = new List<Contact>{
                new Contact(LastName='C1', Lead__c=lead.Id, RecordTypeId=rtContactLead),
                new Contact(LastName='C2', Lead__c=lead.Id, RecordTypeId=rtContactLead)
            };
            insert contacts;

            String payload = JSON.serialize(new Map<String, Object>{
                'Data' => new Map<String, Object>{
                    'OrderType'     => 'Tubes',
                    'OrderCurrency' => 'USD',
                    'Header' => new Map<String, Object>{
                        'ID_SF'            => o.Id,
                        'Account'          => new Map<String,Object>{ 'Name'=>'Test Acc', 'Id'=>'ERP-1', 'CountryId'=>804, 'Address'=>'Addr' },
                        'BusinessSegmentId'=> '00011',
                        'CountryId'        => 804,
                        'PaymentTerms'     => new Map<String,Object>{ 'Id'=>'C33', 'Name'=>'PT' },
                        'DeliveryTerms'    => new Map<String,Object>{ 'Id'=>'008', 'Name'=>'DT' },
                        'SalesRep'         => new Map<String,Object>{ 'UserId'=>'ANY' }
                    }
                }
            });

            Test.startTest();
            LeadConvertion.LeadConvertResult res = LeadConvertion.convertLead(payload);
            Test.stopTest();

            System.assertNotEquals(null, res);
            System.assert(res.accResult, 'Account should be created');

            List<Contact> updated = [SELECT Id, AccountId, RecordTypeId FROM Contact WHERE Id IN :contacts];
            System.assertEquals(2, updated.size());
            System.assertNotEquals(null, updated[0].AccountId);

            if (rtOppEnquiry != null) {
                System.assert(res.oppResult, 'Opps should be updated when Enquiry RT exists');
                Opportunity o2 = [SELECT Id, AccountId, Status__c, RecordTypeId FROM Opportunity WHERE Id=:o.Id];
                System.assertEquals('Opportunity', o2.Status__c);
                System.assertNotEquals(null, o2.AccountId);
            } else {
                System.assertEquals(false, res.oppResult);
            }

            if (res.accResult && res.oppResult && res.contResult) {
                ClientLead__c leadAfter = [SELECT Id, LeadStage__c FROM ClientLead__c WHERE Id=:lead.Id];
                System.assertEquals('Converted', leadAfter.LeadStage__c);
                System.assert(res.leadConverted);
            }
        } finally {
            // скидаємо гачки
            LeadConvertion.bypassSegmentCheck = false;
            LeadConvertion.bypassLicenseCheck = false;
            LeadConvertion.testDuplicates = null;
        }
    }

    @IsTest
    static void test_convert_duplicates_early_exit() {
        ClientLead__c lead = new ClientLead__c(
            Name='Lead D',
            BusinessDivision__c = 'Pipes',  // Валідне значення з picklist
            MarketSegment__c = '00011'       // Ukraine
        );
        insert lead;

        // Очищаємо кеш, щоб LeadRepository знайшов щойно створений Lead
        LeadRepository.clearCache();

        Opportunity o = new Opportunity(
            Name='Head D',
            StageName='Prospecting',
            CloseDate=Date.today().addDays(10),
            Lead__c=lead.Id
        );
        insert o;

        // підставляємо “знайдені” дублікати
        String mrJson = JSON.serialize(new Map<String,Object>{
            'account1Id' => (String)fakeAccountId(1),
            'account2Id' => (String)fakeAccountId(2),
            'matchIndex' => 0.92
        });
        StringUtilsEx.MatchResult mr =
            (StringUtilsEx.MatchResult) JSON.deserialize(mrJson, StringUtilsEx.MatchResult.class);
        LeadConvertion.testDuplicates = new List<StringUtilsEx.MatchResult>{ mr };

        try {
            String payload = JSON.serialize(new Map<String, Object>{
                'Data' => new Map<String, Object>{
                    'OrderType'     => 'Wheels',
                    'OrderCurrency' => 'EUR',
                    'Header' => new Map<String, Object>{
                        'ID_SF'            => o.Id,
                        'Account'          => new Map<String,Object>{ 'Name'=>'Dup Acc', 'Id'=>'ERP-X', 'CountryId'=>804, 'Address'=>'Addr' },
                        'BusinessSegmentId'=> '00099',
                        'CountryId'        => 804,
                        'PaymentTerms'     => new Map<String,Object>{ 'Id'=>'C99', 'Name'=>'PT' },
                        'DeliveryTerms'    => new Map<String,Object>{ 'Id'=>'009', 'Name'=>'DT' },
                        'SalesRep'         => new Map<String,Object>{ 'UserId'=>'ANY' }
                    }
                }
            });

            Test.startTest();
            LeadConvertion.LeadConvertResult res = LeadConvertion.convertLead(payload);
            Test.stopTest();

            System.assertNotEquals(null, res);
            System.assertEquals(false, res.accResult);
            System.assertEquals(false, res.oppResult);
            System.assertEquals(false, res.contResult);
            System.assertEquals(false, res.leadConverted);
        } finally {
            LeadConvertion.testDuplicates = null; // скидаємо
        }
    }

    @IsTest
    static void test_getSegmVirtAcc_found() {
        // Створюємо віртуальний акаунт
        Account virtualAcc = new Account(
            Name = 'Virtual Account Europe',
            ID_ERP__c = 'VIRT_EU_001',
            Type = 'Virtual'
        );
        insert virtualAcc;

        // Створюємо SegmentAccount, що посилається на цей акаунт через ID_ERP__c
        SegmentAccount__c segAcc = new SegmentAccount__c(
            Name = 'EUROPE',
            ID_ERP__c = 'VIRT_EU_001'
        );
        insert segAcc;

        // Очищаємо кеш AccountRepository, щоб він завантажив наш тестовий акаунт
        AccountRepository.clearCache();

        Test.startTest();
        Map<String, Id> result = LeadConvertion.getSegmVirtAcc();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Map не має бути null');
        System.assert(result.containsKey('EUROPE'), 'Map має містити ключ EUROPE');
        System.assertEquals(virtualAcc.Id, result.get('EUROPE'), 'Id акаунта має співпадати');
    }

    @IsTest
    static void test_getSegmVirtAcc_notFound() {
        // Створюємо SegmentAccount БЕЗ відповідного Account
        SegmentAccount__c segAcc = new SegmentAccount__c(
            Name = 'AMERICA',
            ID_ERP__c = 'VIRT_AM_999'
        );
        insert segAcc;

        // Очищаємо кеш
        AccountRepository.clearCache();

        Test.startTest();
        Map<String, Id> result = LeadConvertion.getSegmVirtAcc();
        Test.stopTest();

        System.assertNotEquals(null, result, 'Map не має бути null');
        System.assertEquals(false, result.containsKey('AMERICA'), 'Map не має містити AMERICA, бо акаунт не знайдено');
    }

    @IsTest
    static void test_getVirtAccIdBySegm_found() {
        // Створюємо віртуальний акаунт
        Account virtualAcc = new Account(
            Name = 'Virtual Account CIS',
            ID_ERP__c = 'VIRT_CIS_001',
            Type = 'Virtual'
        );
        insert virtualAcc;

        // Створюємо SegmentAccount
        SegmentAccount__c segAcc = new SegmentAccount__c(
            Name = 'CIS',
            ID_ERP__c = 'VIRT_CIS_001'
        );
        insert segAcc;

        // Очищаємо кеш
        AccountRepository.clearCache();

        Test.startTest();
        Id result = LeadConvertion.getVirtAccIdBySegm('CIS');
        Test.stopTest();

        System.assertNotEquals(null, result, 'Id не має бути null');
        System.assertEquals(virtualAcc.Id, result, 'Id має співпадати з віртуальним акаунтом');
    }

    @IsTest
    static void test_getVirtAccIdBySegm_notFound() {
        Test.startTest();
        Id result = LeadConvertion.getVirtAccIdBySegm('UNKNOWN_SEGMENT');
        Test.stopTest();

        System.assertEquals(null, result, 'Для невідомого сегменту має повертатися null');
    }
}