force-app/main/default/objects/Account/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsVirtual__c.field-meta.xml
<CustomField>
    <fullName>IsVirtual__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Virtual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <description>Invoice payment terms and conditions for the customer</description>
    <inlineHelpText>invoice payment terms and conditions for the customer</inlineHelpText>
    <label>Payment Terms (not use)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryTerms__c/DeliveryTerms__c.object-meta.xml
<CustomObject>
    <label>Delivery Terms</label>
    <nameField>
        <label>Delivery Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Delivery Terms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/HttpStatus__mdt/HttpStatus__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type generated from CSV: C:\Users\aleksandr.novikov\CMDT_Tools\httpStatus.csv</description>
    <label>HttpStatus</label>
    <pluralLabel>HttpStatuss</pluralLabel>
</CustomObject>

force-app/main/default/objects/HttpStatus__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HttpStatus__mdt/fields/Status__c.field-meta.xml
<CustomField xmlns='http://soap.sforce.com/2006/04/metadata'>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

force-app/main/default/objects/IgnoredAccount__mdt/IgnoredAccount__mdt.object-meta.xml
<CustomObject>
    <label>Ignored Account</label>
    <pluralLabel>Ignored Accounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/IgnoredAccount__mdt/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketSegment__mdt/MarketSegment__mdt.object-meta.xml
<CustomObject>
    <description>Market Segments</description>
    <label>Market Segment</label>
    <pluralLabel>Market Segments</pluralLabel>
</CustomObject>

force-app/main/default/objects/MarketSegment__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Code</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/DeliveryTerms__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Terms</label>
    <referenceTo>DeliveryTerms__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <referenceTo>PaymentTerms__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemStage__mdt/OrderItemStage__mdt.object-meta.xml
<CustomObject>
    <description>Order Item Stages in IT-Enterprise</description>
    <label>Order Item Stage</label>
    <pluralLabel>Order Item Stages</pluralLabel>
</CustomObject>

force-app/main/default/objects/OrderItemStage__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemStage__mdt/fields/StatusSF__c.field-meta.xml
<CustomField>
    <fullName>StatusSF__c</fullName>
    <label>StatusSF</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PaymentTerms__c/PaymentTerms__c.object-meta.xml
<CustomObject>
    <label>Payment Terms</label>
    <nameField>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Terms</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerms__c/fields/Obsolete__c.field-meta.xml
<CustomField>
    <fullName>Obsolete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, the record does not appear in picklists.</inlineHelpText>
    <label>Obsolete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/BusinesDivision__c.field-meta.xml
<CustomField>
    <fullName>BusinesDivision__c</fullName>
    <label>Business Division</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BusinessDivisions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/LoginERP__c.field-meta.xml
<CustomField>
    <fullName>LoginERP__c</fullName>
    <description>User&apos;s login in the ERP system</description>
    <externalId>true</externalId>
    <label>Login in ERP</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/SalesDivision__c.field-meta.xml
<CustomField>
    <fullName>SalesDivision__c</fullName>
    <description>Sales division that user belongs to</description>
    <inlineHelpText>Sales division that user belongs to</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BusinesDivision__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>SalesDivisions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/UID_ERP__c.field-meta.xml
<CustomField>
    <fullName>UID_ERP__c</fullName>
    <label>ERP UID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Type__c</fullName>
    <formula>IF(OR(LEFT(Profile.Name,13)=&apos;Sales Manager&apos;, Username=&apos;denis.morozov@nterpipe.biz&apos;),&apos;SALES MANAGERS&apos;, 
  IF(LEFT(Profile.Name,8)=&apos;Customer&apos;,&apos;CUSTOMER COMMUNITY&apos;,
    IF(LEFT(Profile.Name,12)=&apos;Chatter Free&apos;,&apos;BACK OFFICE&apos;, 
	  IF(TEXT(SalesDivision__c)=&apos;SFAdmins&apos;, &apos;SYSADMIN&apos;,
	    IF(LEFT(Profile.Name,5)=&apos;Quota&apos;, &apos;QUOTA APPROVERS&apos;,&apos;OTHER USERS&apos;)
	  )
	)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User`s Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/BusinessDivisions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Pipes</fullName>
        <label>Pipe Products</label>
    </customValue>
    <customValue>
        <fullName>Railway</fullName>
        <label>Railway Products</label>
    </customValue>
    <customValue>
        <fullName>Steel</fullName>
        <label>Steel Products</label>
    </customValue>
    <customValue>
        <fullName>PRD</fullName>
        <label>Product &amp; Resource Dept.</label>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>IT Department</label>
    </customValue>
    <customValue>
        <fullName>Customer</fullName>
    </customValue>
    <customValue>
        <fullName>TOP</fullName>
        <label>Top Management</label>
    </customValue>
    <customValue>
        <fullName>DVM</fullName>
        <label>ДніпроВторМет</label>
    </customValue>
    <masterLabel>Business Divisions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PaymentTerms.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PIA</fullName>
        <default>true</default>
        <label>PIA</label>
    </customValue>
    <customValue>
        <fullName>Net 7</fullName>
    </customValue>
    <customValue>
        <fullName>Net 10</fullName>
    </customValue>
    <customValue>
        <fullName>Net 30</fullName>
    </customValue>
    <customValue>
        <fullName>Net 60</fullName>
    </customValue>
    <customValue>
        <fullName>Net 90</fullName>
    </customValue>
    <customValue>
        <fullName>Letter of credit</fullName>
    </customValue>
    <description>Invoice payment terms and conditions</description>
    <masterLabel>Payment Terms</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SalesDivisions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>SFAdmins</fullName>
        <label>Salesforce Admins</label>
    </customValue>
    <description>Sales divisions in our company</description>
    <masterLabel>Sales Divisions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERPMessageUtils.cls
public with sharing class ERPMessageUtils {
    //--- Статична мапа HTTP статусів
    public static Map<Integer, String> httpStatus = new Map<Integer, String>();
    static {
        for(HttpStatus__mdt hs : [SELECT 
                                    Code__c,Status__c
                                FROM HttpStatus__mdt 
                                ORDER BY Code__c ]) {
            httpStatus.put(Integer.valueOf(hs.Code__c), hs.Status__c);                    
        }
    }
    
    public static List<OrderItemStage__mdt> oisList = [
                                        SELECT 
                                          Code__c, StatusSF__c 
                                        FROM OrderItemStage__mdt];
    //--- Статична мапа статусів OrderItems                                    
    public static Map<String, String> itemStatusMap = new Map<String, String>();
    static {
        for(OrderItemStage__mdt m : oisList) {
            itemStatusMap.put(m.Code__c, m.StatusSF__c);
        }
    }   
    //--- Чи статус позиції - це Placed?
    public static boolean checkIfPlaced(String apiName){
        return itemStatusMap.containsKey(apiName);
    }    
    /*** Кеш- репо юзерів */
    public static List<User> usrList = [
        SELECT
        Id, Name, Username, Email, BusinesDivision__c, SalesDivision__c, 
        LoginERP__c, UID_ERP__c, ID_ERP__c, User_Type__c
        FROM User
        WHERE IsActive=true AND User_Type__c IN ('SALES MANAGERS','BACK OFFICE') 
        AND SalesDivision__c!=null AND LoginERP__c!=null        
    ];
    //--- Мапи юзерів, ключ LoginERP__c
    public static Map<String, User> mapSalesUsersByLogin = new Map<String, User>();
    public static Map<String, User> mapBOUsersByLogin = new Map<String, User>();
    //--- Мапи юзерів, ключ LoginERP__c
    public static Map<String, User> mapSalesUsersByIdErp = new Map<String, User>();
    public static Map<String, User> mapBOUsersByIdErp = new Map<String, User>();

    static {
        for(User usr : usrList) {
            if(usr.User_Type__c=='SALES MANAGERS') {
                mapSalesUsersByLogin.put(usr.LoginERP__c, usr);
                mapSalesUsersByIdErp.put(usr.ID_ERP__c, usr);
            } else { // BACK OFFICE
                mapBOUsersByLogin.put(usr.LoginERP__c, usr);
                mapBOUsersByIdErp.put(usr.ID_ERP__c, usr);                
            }
        }
    }
    //========= Хелпери кеша юзерів ===========
    public static User getSaleUserByLogin(String erpLogin) {
        if(String.isBlank(erpLogin)) return new User();
        if(mapSalesUsersByLogin.containsKey(erpLogin)) {
            return mapSalesUsersByLogin.get(erpLogin);
        } 
       return new User();
    }

    public static User getSaleUserByIdErp(String IdErp) {
        if(String.isBlank(IdErp)) return new User();
        if(mapSalesUsersByIdErp.containsKey(IdErp)) {
            return mapSalesUsersByIdErp.get(IdErp);
        } 
       return new User();
    }  

    public static User getBOUserByLogin(String erpLogin) {
        if(String.isBlank(erpLogin)) return new User();
        if(mapBOUsersByLogin.containsKey(erpLogin)) {
            return mapBOUsersByLogin.get(erpLogin);
        } 
       return new User();
    }

    public static User getBOUserByIdErp(String IdErp) {
        if(String.isBlank(IdErp)) return new User();
        if(mapBOUsersByIdErp.containsKey(IdErp)) {
            return mapBOUsersByIdErp.get(IdErp);
        } 
       return new User();
    }

    //--- Статична мапа MarketSegment
    public static Map<String, String> mapSegments = new Map<String, String>();
    public static List<MarketSegment__mdt> mdtMS = [SELECT
                                  Code__c, DeveloperName
                                FROM MarketSegment__mdt];
    static {
        for(MarketSegment__mdt ms : mdtMS) {
            mapSegments.put(ms.Code__c, ms.DeveloperName);
        }
    }

    //--- Ігнор-акаунти
    public static List<IgnoredAccount__mdt> ignAccList =
        [SELECT ID_ERP__c FROM IgnoredAccount__mdt];
    //--- Ignired accounts - static Set
    public static Set<String> ignoredAccSet = new Set<String>();
    static {
        for (IgnoredAccount__mdt ign : IgnoredAccount__mdt.getAll().values()) {
            if (String.isNotBlank(ign.ID_ERP__c)) ignoredAccSet.add(ign.ID_ERP__c.trim());
        }
    }

    //--- Мапа відповідності JSON.BusinessDivision => Picklist.BusinessDivision
    public static Map<String, String> mapBusinessDivision = new Map<String, String>();
    static {
        mapBusinessDivision.put('Tubes','Pipes');
        mapBusinessDivision.put('Wheels','Railway');
    }

    //--- Кеш Delivery Terms
    public static Map<String, DeliveryTerms__c> mapDelivTerms;
    static {
        mapDelivTerms = new Map<String, DeliveryTerms__c>();
        for(DeliveryTerms__c d : [SELECT Id,ID_ERP__c,Name FROM DeliveryTerms__c]) {
            mapDelivTerms.put(d.ID_ERP__c,d);
        }
    } 
    //--- Helper
    public static DeliveryTerms__c getDelivTermByIdErp(String idErp) {
        DeliveryTerms__c resMap = new DeliveryTerms__c();
        if(mapDelivTerms.containsKey(idErp)) {
            resMap = mapDelivTerms.get(idErp);
        }
        return resMap;
    }     
    //--- Кеш Payment Terms
    public static Map<String, PaymentTerms__c> mapPayTerms;
    static {
        mapPayTerms = new Map<String, PaymentTerms__c>();
        for(PaymentTerms__c p : [SELECT Id,ID_ERP__c,Name FROM PaymentTerms__c
                                WHERE Obsolete__c=false]) {
            mapPayTerms.put(p.ID_ERP__c, p);
        }
    }
    //--- Helper
    public static PaymentTerms__c getPayTermByIdErp(String idErp) {
        PaymentTerms__c res = new PaymentTerms__c();
        if(mapPayTerms.containsKey(idErp)) {
            res = mapPayTerms.get(idErp);
        }
        return res;
    }    

    public static Boolean isIgnoredAccount(String idErp) {
        return (String.isBlank(idErp)) ||
               (ignoredAccSet.contains(idErp));
    }

    // Статична мапа віртуальних акаунтів (для лідів)
    public static Map<String, Id> virtAccMap;
    public static List<Account> virtAccList = [
        SELECT Id, ID_ERP__c,  Name, BillingCountry, BillingCountryCode
        FROM Account WHERE IsVirtual__c=true
    ];

    static {
        virtAccMap = new Map<String, Id>();
        for(Account acc: virtAccList) {
            virtAccMap.put(acc.ID_ERP__c, acc.Id);
        }
    }

    public static Boolean isAccVirtual(String erpId) {
        return (String.isBlank(erpId)) ||
               (virtAccMap.containsKey(erpId));
    }
}