force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Controlling_Question__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Controlling Question</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Questionnaire__c</field>
            <operation>equals</operation>
            <valueField>Question__c.Questionnaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Dependent Questions</relationshipLabel>
    <relationshipName>Dependent_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Questionnaire__c</field>
            <operation>equals</operation>
            <valueField>Section__c.Questionnaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Questionaire Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Controlling_Question__c.field-meta.xml
<CustomField>
    <fullName>Controlling_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Controlling Question</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Questionnaire__c</field>
            <operation>equals</operation>
            <valueField>Question__c.Questionnaire__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuestionnaireClonerTest.cls
@isTest
public class QuestionnaireClonerTest {

    @isTest static void testCloneQuestionnaireWithQuestions() {
        // Create and insert a test Questionnaire__c record
        Questionnaire__c testQuestionnaire = new Questionnaire__c(
            Name = 'Test Questionnaire'
            // Set other necessary fields
        );
        insert testQuestionnaire;

        // Create and insert test Section__c records
        Section__c testSection = new Section__c(
            Name = 'Test Section',
            Questionnaire__c = testQuestionnaire.Id
            // Set other necessary fields
        );
        insert testSection;

        // Create and insert test Question__c records
        Question__c testQuestion = new Question__c(
            Name = 'Test Question',
            Questionnaire__c = testQuestionnaire.Id,
            Section__c = testSection.Id
            // Set other necessary fields
        );
        insert testQuestion;

        Question__c secondQuestion = new Question__c(
            Name = 'Second Question',
            Questionnaire__c = testQuestionnaire.Id,
            Section__c = testSection.Id,
            Controlling_Question__c = testQuestion.Id,
            Value__c = 'Test Value'
        );
        insert secondQuestion;

        Test.startTest();
        // Call the method to test
        Id clonedQuestionnaireId = QuestionnaireCloner.cloneQuestionnaireWithQuestions(testQuestionnaire.Id);
        Test.stopTest();

        // Assert that the Questionnaire__c was cloned
        Questionnaire__c clonedQuestionnaire = [SELECT Id, Name FROM Questionnaire__c WHERE Id = :clonedQuestionnaireId];
        System.assertNotEquals(null, clonedQuestionnaire, 'The cloned questionnaire should not be null.');
        System.assertEquals('Test Questionnaire - Cloned', clonedQuestionnaire.Name, 'The name of the cloned questionnaire is incorrect.');

        // Assert that related Section__c and Question__c records were cloned
        List<Section__c> clonedSections = [SELECT Id, Questionnaire__c FROM Section__c WHERE Questionnaire__c = :clonedQuestionnaireId];
        System.assertNotEquals(0, clonedSections.size(), 'Cloned sections should exist.');

        List<Question__c> clonedQuestions = [SELECT Id, Questionnaire__c FROM Question__c WHERE Questionnaire__c = :clonedQuestionnaireId];
        System.assertNotEquals(0, clonedQuestions.size(), 'Cloned questions should exist.');
    }
}