force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteFamilyLink__c/RouteFamilyLink__c.object-meta.xml
<CustomObject>
    <label>Route Family Link</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Route Family Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes Families Link</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RouteFamilyLink__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Routes Families Link</relationshipLabel>
    <relationshipName>Routes_Families_Link</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RouteFamilyLink__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Routes Families Link</relationshipLabel>
    <relationshipName>Routes_Families_Link</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ERPMessageHandlerRouteFamily.cls
public with sharing class ERPMessageHandlerRouteFamily {

    public static MessageProcessingResult processMessage(ERPMessageParser.ErpToSfMessage_RouteFamilies parsedMessage) {
        MessageProcessingResult res = new MessageProcessingResult();
        res.MessageType = parsedMessage.metadata.MsgType;

        try {
            String operationMode = String.valueOf(parsedMessage.data.Mode);
            Map<String, RouteFamilyLink__c> routeFamilyMap = getRouteFamilyMap();

            switch on operationMode {
                when 'MERGE' {
                    modifyRoutesFamilies(parsedMessage, routeFamilyMap);
                    deleteRoutesFamilies(parsedMessage, routeFamilyMap, false);
                } when 'MODIFY' {
                    modifyRoutesFamilies(parsedMessage, routeFamilyMap);
                } when 'DELETE' {
                    deleteRoutesFamilies(parsedMessage, routeFamilyMap, true);
                } when else {
                    throw new ExecutionException('Unsupported mode: ' + operationMode);
                }
            }

            return res;

        } catch (Exception e) {
            res.error = e.getMessage();
            return res;
        }
    }

    private static void modifyRoutesFamilies(ERPMessageParser.ErpToSfMessage_RouteFamilies parsedMessage, Map<String, RouteFamilyLink__c> routeFamilyMap) {
        Map<Decimal, Id> routeMap = getRouteMap();
        Map<Decimal, Id> familyMap = getFamilyMap();
        List<RouteFamilyLink__c> routeFamilyToInsertList = new List<RouteFamilyLink__c>();

        for (ERPMessageParser.RouteFamilyItem routeFamilyItem : parsedMessage.data.Items) {
            for(ERPMessageParser.FamilyItem familyItem : routeFamilyItem.Families) {
                RouteFamilyLink__c routeFamilyToInsert = new RouteFamilyLink__c();
                if(routeFamilyMap.get(routeFamilyItem.Route.RouteId + '' + familyItem.FamilyId) == null) {
                    routeFamilyToInsert.Route__c = routeMap.get(routeFamilyItem.Route.RouteId);
                    routeFamilyToInsert.Family__c = familyMap.get(familyItem.FamilyId);
                    routeFamilyToInsertList.add(routeFamilyToInsert);
                }
            }
        }
        insert routeFamilyToInsertList;
    }

    private static void deleteRoutesFamilies(ERPMessageParser.ErpToSfMessage_RouteFamilies parsedMessage, Map<String, RouteFamilyLink__c> routeFamilyMap, Boolean isDeleteMode) {
        List<String> routeFamilyERPIdList = new List<String>();
        List<RouteFamilyLink__c> routeFamilyToDeleteList = new List<RouteFamilyLink__c>();

        for(ERPMessageParser.RouteFamilyItem routeFamilyItem : parsedMessage.data.Items) {
            for(ERPMessageParser.FamilyItem familyItem : routeFamilyItem.Families) {
                if(isDeleteMode && routeFamilyMap.get(routeFamilyItem.Route.RouteId + '' + familyItem.FamilyId) != null) {
                    routeFamilyToDeleteList.add(routeFamilyMap.get(routeFamilyItem.Route.RouteId + '' + familyItem.FamilyId));
                } else if(!isDeleteMode) {
                    routeFamilyERPIdList.add(routeFamilyItem.Route.RouteId + '' + familyItem.FamilyId);
                }
            }
        }

        if(!isDeleteMode) {
            for(RouteFamilyLink__c routeFamily : routeFamilyMap.values()) {
                if(!routeFamilyERPIdList.contains(routeFamily.Route__r.ID_ERP__c + '' + routeFamily.Family__r.ID_ERP__c)) {
                    routeFamilyToDeleteList.add(routeFamily);
                } 
            }
        }

        delete routeFamilyToDeleteList;
    }

    private static Map<String, RouteFamilyLink__c> getRouteFamilyMap() {
        Map<String, RouteFamilyLink__c> routeFamilyMap = new Map<String, RouteFamilyLink__c>();
        List<RouteFamilyLink__c> routeFamilyList = [SELECT Id, Family__c, Family__r.ID_ERP__c, Route__c, Route__r.ID_ERP__c FROM RouteFamilyLink__c];

        for(RouteFamilyLink__c routeFamily : routeFamilyList) {
            routeFamilyMap.put(routeFamily.Route__r.ID_ERP__c + '' + routeFamily.Family__r.ID_ERP__c, routeFamily);
        }

        return routeFamilyMap;
    }

    private static Map<Decimal, Id> getRouteMap() {
        Map<Decimal, ID> routeMap = new Map<Decimal, Id>();
        List<Route__c> routeList = [SELECT Id, ID_ERP__c FROM Route__c];

        for(Route__c route : routeList) {
            routeMap.put(route.ID_ERP__c, route.Id);
        }

        return routeMap;
    }

    private static Map<Decimal, Id> getFamilyMap() {
        Map<Decimal, Id> familyMap = new Map<Decimal, Id>();
        List<Family__c> familyList = [SELECT Id, ID_ERP__c FROM Family__c];

        for(Family__c family : familyList) {
            familyMap.put(family.ID_ERP__c, family.Id);
        }

        return familyMap;
    }

    public static Blob generateResponseBody(Map<Integer, String> statusCodesMap, Integer statusCode, String error, MessageProcessingResult mpRes) {
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeNumberField('Status Code', statusCode);
            gen.writeStringField('Status', statusCodesMap.get(statusCode));
            gen.writeStringField('Processed message type', mpRes.MessageType);
            if (error != NULL) {
                gen.writeStringField('Error Message', error);
            }
            gen.writeEndObject();
            
            String res = gen.getAsString();
            System.debug('Response body text generated: ' + res);
            return Blob.valueOf(res);
        }

    public class MessageProcessingResult {
        public String MessageType;		
        public String error;
    } 

    public class ExecutionException extends Exception {
    }
}