force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QBA_Families__c/QBA_Families__c.object-meta.xml
<CustomObject>
    <description>Quotes/Budget-Families Link Table</description>
    <label>Quotes Families</label>
    <nameField>
        <displayFormat>QF-{000000}</displayFormat>
        <label>Quotes Families Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes Families</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QBA_Families__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quotes Families</relationshipLabel>
    <relationshipName>Quotes_Families</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QBA_Families__c/fields/QuotesBudgetAll__c.field-meta.xml
<CustomField>
    <fullName>QuotesBudgetAll__c</fullName>
    <label>Quotes Budget All</label>
    <referenceTo>Route_Quota__c</referenceTo>
    <relationshipLabel>Quotes Families</relationshipLabel>
    <relationshipName>Quotes_Families</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/QuotesStructure__c.object-meta.xml
<CustomObject>
    <label>Quotes Structure</label>
    <nameField>
        <displayFormat>QS-{000000}</displayFormat>
        <label>QSName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes Structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotesStructure__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quotes Structures</relationshipLabel>
    <relationshipName>Quotes_Structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>MarketSegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/QuoteStructureDetail__c.object-meta.xml
<CustomObject>
    <label>Quote Structure Detail</label>
    <nameField>
        <label>Route Family</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Structure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteStructureDetail__c/fields/DateBegin__c.field-meta.xml
<CustomField>
    <fullName>DateBegin__c</fullName>
    <label>Date Begin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/DateEnd__c.field-meta.xml
<CustomField>
    <fullName>DateEnd__c</fullName>
    <label>Date End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Quota__c/Route_Quota__c.object-meta.xml
<CustomObject>
    <label>Quotes Budget All</label>
    <nameField>
        <label>Families Names</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes Budget All</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Quota__c/fields/Budget_pcs__c.field-meta.xml
<CustomField>
    <fullName>Budget_pcs__c</fullName>
    <label>Budget (pcs)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Quota__c/fields/Budget_t__c.field-meta.xml
<CustomField>
    <fullName>Budget_t__c</fullName>
    <label>Budget (t)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Quota__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Quota__c/fields/Quote_pcs__c.field-meta.xml
<CustomField>
    <fullName>Quote_pcs__c</fullName>
    <label>Quote (pcs)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Route_Quota__c/fields/Quote_t__c.field-meta.xml
<CustomField>
    <fullName>Quote_t__c</fullName>
    <label>Quote (t)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/RouteQuotesH__c.object-meta.xml
<CustomObject>
    <label>Route Quotas Hierarchy</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Quotas Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RouteQuotesH__c/fields/Budget_pcs__c.field-meta.xml
<CustomField>
    <fullName>Budget_pcs__c</fullName>
    <label>Budget (pcs)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/DateEnd__c.field-meta.xml
<CustomField>
    <fullName>DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>RouteQuotesH__c</referenceTo>
    <relationshipName>Route_Quotes_Hierarchy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Parent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/Quote_pcs__c.field-meta.xml
<CustomField>
    <fullName>Quote_pcs__c</fullName>
    <label>Quote (pcs)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/Quote_t__c.field-meta.xml
<CustomField>
    <fullName>Quote_t__c</fullName>
    <label>Quote (t)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesRelated__c/RouteQuotesRelated__c.object-meta.xml
<CustomObject>
    <label>Route Quotes Related</label>
    <nameField>
        <label>Route Quote</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Quotes Related</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RouteQuotesRelated__c/fields/Budget_pcs__c.field-meta.xml
<CustomField>
    <fullName>Budget_pcs__c</fullName>
    <label>Budget (pcs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesRelated__c/fields/Budget_t__c.field-meta.xml
<CustomField>
    <fullName>Budget_t__c</fullName>
    <label>Budget (t)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesRelated__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RouteQuotesRelated__c/fields/Quote_pcs__c.field-meta.xml
<CustomField>
    <fullName>Quote_pcs__c</fullName>
    <label>Quote (pcs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RouteQuotesHierarchyQueueableTest.cls
@isTest
public class RouteQuotesHierarchyQueueableTest {
    private static final Integer CURRENT_YEAR = Date.today().year();
    private static final Integer PREVIOUS_MONTH = Date.today().addMonths(-1).month();
    
    @testSetup
    static void setup() {
        List<Route_Quota__c> routeQuotas = new List<Route_Quota__c>();
        for (Integer i = 0; i < 3; i++) {
            Integer month = PREVIOUS_MONTH + i > 12 ? PREVIOUS_MONTH + i - 12 : PREVIOUS_MONTH + i;
            Integer year = PREVIOUS_MONTH == 11 && month == 1 ? CURRENT_YEAR + 1 : CURRENT_YEAR;
            Route_Quota__c routeQuota = new Route_Quota__c(
                DateBegin__c = Date.newInstance(year, month, 1),
                DateEnd__c = Date.newInstance(year, month, 31),
                MarketSegment__c = '0000' + (4 + i),
                Budget_t__c = 220,
                Budget_pcs__c = 0,
                Quote_t__c = 630,
                Quote_pcs__c = 0,
                Margin__c = 545000
            );
            routeQuotas.add(routeQuota);
        }
        insert routeQuotas;

        Family__c family = new Family__c(Name = 'Цех1. Нарезные');
        insert family;
        
        List<QBA_Families__c> qbaFamilies = new List<QBA_Families__c>();
        for (Route_Quota__c routeQuota : routeQuotas) {
            QBA_Families__c qbaFamily = new QBA_Families__c(
                QuotesBudgetAll__c = routeQuota.Id,
                Family__c = family.Id
            );
            qbaFamilies.add(qbaFamily);
        }
        insert qbaFamilies;

        List<QuotesStructure__c> quotesStructures = new List<QuotesStructure__c>();
        for (Route_Quota__c routeQuota : routeQuotas) {
            QuotesStructure__c quotesStructure = new QuotesStructure__c(
                DateBegin__c = routeQuota.DateBegin__c,
                DateEnd__c = routeQuota.DateEnd__c,
                MarketSegment__c = routeQuota.MarketSegment__c,
                Family__c = family.Id,
                Percent__c = 100
            );
            quotesStructures.add(quotesStructure);
        }
        insert quotesStructures;
    }

    @isTest
    static void testRouteQuotesHierarchyQueueable() {
        Test.startTest();
        RouteQuotesHierarchyQueueable job = new RouteQuotesHierarchyQueueable(false);
        ID jobId = System.enqueueJob(job);
        Test.stopTest();

        List<RouteQuotesH__c> routeQuotesHierarchy = [SELECT Id FROM RouteQuotesH__c];
        System.assert(routeQuotesHierarchy.size() > 0, 'RouteQuotesH__c records should be created');

        List<RouteQuotesRelated__c> routeQuotesRelated = [SELECT Id FROM RouteQuotesRelated__c];
        System.assert(routeQuotesRelated.size() > 0, 'RouteQuotesRelated__c records should be created');

        List<QuoteStructureDetail__c> quoteStructDetails = [SELECT Id FROM QuoteStructureDetail__c];
        System.assert(quoteStructDetails.size() > 0, 'QuoteStructureDetail__c records should be created');

        List<RouteQuotesH__c> routeQuotesHierarchyWithoutParent = [SELECT Id FROM RouteQuotesH__c WHERE Parent__c = null AND ParentId__c != null];
        System.assertEquals(1, routeQuotesHierarchyWithoutParent.size(), 'There shoud be one record without active parent');
    }

    @isTest
    static void testRouteQuotesHierarchyQueueableOnUpdate() {
        RouteQuotesH__c allRoutesQuotesParent = new RouteQuotesH__c(Name = 'ALL ROUTES QUOTES', Level__c = 0);
        insert allRoutesQuotesParent;

        Test.startTest();
        RouteQuotesHierarchyQueueable job = new RouteQuotesHierarchyQueueable(true);
        ID jobId = System.enqueueJob(job);
        Test.stopTest();

        List<RouteQuotesH__c> routeQuotesHierarchy = [SELECT Id FROM RouteQuotesH__c WHERE DateBegin__c = :Date.newInstance(CURRENT_YEAR, PREVIOUS_MONTH, 1)];
        System.assert(routeQuotesHierarchy.size() == 0, 'RouteQuotesH__c with previous month should not be created');

        List<RouteQuotesRelated__c> routeQuotesRelated = [SELECT Id FROM RouteQuotesRelated__c WHERE DateBegin__c = :Date.newInstance(CURRENT_YEAR, PREVIOUS_MONTH, 1)];
        System.assert(routeQuotesRelated.size() == 0, 'RouteQuotesRelated__c with previous month should not be created');

        List<QuoteStructureDetail__c> quoteStructDetails = [SELECT Id FROM QuoteStructureDetail__c WHERE DateBegin__c = :Date.newInstance(CURRENT_YEAR, PREVIOUS_MONTH, 1)];
        System.assert(quoteStructDetails.size() == 0, 'QuoteStructureDetail__c with previous month should not be created');

    }
}