force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Group3__c/Group3__c.object-meta.xml
<CustomObject>
    <label>Group3</label>
    <nameField>
        <label>Group 3</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group3__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/QuotesStructure__c.object-meta.xml
<CustomObject>
    <label>Quotes Structure</label>
    <nameField>
        <displayFormat>QS-{000000}</displayFormat>
        <label>QSName</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes Structures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotesStructure__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quotes Structures</relationshipLabel>
    <relationshipName>Quotes_Structures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/fields/Group3__c.field-meta.xml
<CustomField>
    <fullName>Group3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Нове поле, Lookup на новий довідник з мовними варіантами. В робочій версії буде він</description>
    <inlineHelpText>Нове поле, Lookup на новий довідник з мовними варіантами. В робочій версії буде він</inlineHelpText>
    <label>Group3</label>
    <referenceTo>Group3__c</referenceTo>
    <relationshipLabel>Quotes Structures</relationshipLabel>
    <relationshipName>Quotes_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>MarketSegment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotesStructure__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Нове поле, Lookup на новий довідник з мовними варіантами. В робочій версії буде він</description>
    <inlineHelpText>Нове поле, Lookup на новий довідник з мовними варіантами. В робочій версії буде він</inlineHelpText>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Quotes Structures</relationshipLabel>
    <relationshipName>Quotes_Structures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>New object for Regions from IT ERP</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERPMessageHandlerStructQuotaTest.cls
@IsTest
public class ERPMessageHandlerStructQuotaTest {

    @TestSetup
    static void makeDate() {
        Family__c family = new Family__c(Name = 'Family Name', ID_ERP__c = 1);
        insert family;

        Group3__c group3 = new Group3__c(Name = 'Group Name', ID_ERP__c = 1);
        insert group3;

        Region__c region = new Region__c(Name = 'Region Name', ID_ERP__c = 1);
        insert region;

        QuotesStructure__c structQuota1 = new QuotesStructure__c(ID_ERP__c = '1', Group3__c = group3.Id, Region__c = region.Id, Family__c = family.Id, MarketSegment__c = '00001', DateBegin__c = date.newinstance(2024, 9, 1), DateEnd__c = date.newinstance(2024, 9, 30));
        QuotesStructure__c structQuota11 = new QuotesStructure__c(ID_ERP__c = '11', Group3__c = group3.Id, Region__c = region.Id, Family__c = family.Id, MarketSegment__c = '00001', DateBegin__c = date.newinstance(2024, 6, 1), DateEnd__c = date.newinstance(2024, 6, 30));
        insert new List<QuotesStructure__c>{structQuota1, structQuota11};
    }

    @IsTest
    static void testMergeStructQuotas() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('MERGE', 1, 1);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(10, upsertedStructQuotas.size(), 'There should be 10 Route Quotas records  - оne record should be deleted');
    }

    @IsTest
    static void testMergePartialStructQuotas() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('MERGE_PARTIAL', 1, 1);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(11, upsertedStructQuotas.size(), 'There should be 11 Route Quotas records');
    }

    @IsTest
    static void testModifyStructQuotas() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('MODIFY', 1, 1);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(11, upsertedStructQuotas.size(), 'There should be 11 Route Quotas records');
    }

    @IsTest
    static void testMergeStructQuotasBulk() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('MERGE', 3, 1);
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage2 = createMockERPMessage('MERGE', 3, 21);
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage3 = createMockERPMessage('MERGE', 3, 31);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        ERPMessageHandlerStructQuota.MessageProcessingResult result2 = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage2);
        ERPMessageHandlerStructQuota.MessageProcessingResult result3 = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage3);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(30, upsertedStructQuotas.size(), 'There should be 10 Route Quotas records  - оne record should be deleted');
    }

    @IsTest
    static void testMergePartialStructQuotasBulk() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('MERGE_PARTIAL', 2, 1);
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage2 = createMockERPMessage('MERGE_PARTIAL', 2, 21);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        ERPMessageHandlerStructQuota.MessageProcessingResult result2 = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage2);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(21, upsertedStructQuotas.size(), 'There should be 11 Route Quotas records');
    }

    @IsTest
    static void testDeleteStructQuotas() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('DELETE', 1, 1);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c];

        Assert.areEqual(1, upsertedStructQuotas.size(), 'There should be 1 record');
    }

    @IsTest
    static void testUnsupportedMode() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessage('Insert', 1, 1);

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        Assert.isTrue(result.error.contains('Unsupported mode'), 'Result should not be null');
    }

    @IsTest
    static void testStructQuotasWithoutFamily() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockParsedMessage = createMockERPMessageWithoutFamily();

        Test.startTest();
        ERPMessageHandlerStructQuota.MessageProcessingResult result = ERPMessageHandlerStructQuota.processMessage(mockParsedMessage);
        Test.stopTest();

        List<QuotesStructure__c> upsertedStructQuotas = [SELECT Id FROM QuotesStructure__c WHERE ID_ERP__c = '2'];

        Assert.areEqual(0, upsertedStructQuotas.size(), 'The record with ID 2 should not be created');
    }

    @isTest 
    static void testGenerateResponseBody() {
        Map<Integer, String> statusCodesMap = new Map<Integer, String>{
            200 => 'OK',
            400 => 'Bad Request'
        };
        ERPMessageHandlerStructQuota.MessageProcessingResult mpRes = new ERPMessageHandlerStructQuota.MessageProcessingResult();
        mpRes.MessageType = 'ERP-SF_StructQuota';

        Blob responseBody = ERPMessageHandlerStructQuota.generateResponseBody(statusCodesMap, 200, null, mpRes);
        String responseString = responseBody.toString();
        Assert.isTrue(responseString.contains('ERP-SF_StructQuota'), 'Response should contain the processed message type.');

        Blob errorResponseBody = ERPMessageHandlerStructQuota.generateResponseBody(statusCodesMap, 400, 'An error occurred', mpRes);
        String errorResponseString = errorResponseBody.toString();
        Assert.isTrue(errorResponseString.contains('An error occurred'), 'Response should contain the error message.');
    }

    private static ERPMessageParser.ErpToSfMessage_StructQuota createMockERPMessage(String mode, Integer totalParts, Integer startNumber) {
        ERPMessageParser.ErpToSfMessage_StructQuota mockMessage = new ERPMessageParser.ErpToSfMessage_StructQuota();

        // Mock Metadata
        mockMessage.Metadata = new ERPMessageParser.MessageMetadata();
        mockMessage.Metadata.MsgType = 'TestType';
        mockMessage.Metadata.msgTimestamp = (DateTime)JSON.deserialize('"2024-09-01T00:00:00"', DateTime.class);
        mockMessage.Metadata.totalParts = totalParts;

        // Mock StructQuotaData
        ERPMessageParser.Options options = new ERPMessageParser.Options();
        options.DATEFROM = (DateTime)JSON.deserialize('"2024-09-01T00:00:00"', DateTime.class);
        options.DATETO = (DateTime)JSON.deserialize('"2024-09-30T00:00:00"', DateTime.class);
        
        ERPMessageParser.Partial partial = new ERPMessageParser.Partial();
        partial.Type = 'PERIOD';
        partial.Options = options;

        ERPMessageParser.StructQuotaData structQuotaData = new ERPMessageParser.StructQuotaData();
        structQuotaData.Mode = mode;
        structQuotaData.Partial = partial;

        // Mock Items

        ERPMessageParser.FamilyItem familyItem = new ERPMessageParser.FamilyItem();
        familyItem.FamilyId = 1;

        ERPMessageParser.StructQuotaConfigItem structConfigItem = new ERPMessageParser.StructQuotaConfigItem();
        structConfigItem.SegmentCode = '00001';

        List<ERPMessageParser.StructQuotaItem> ItemList = new List<ERPMessageParser.StructQuotaItem>();
        for(Integer i = startNumber; i < startNumber + 10; i++) {
            ERPMessageParser.StructQuotaItem item = new ERPMessageParser.StructQuotaItem();
            item.RowId = i;
            item.DateFrom = (DateTime)JSON.deserialize('"2024-09-01T00:00:00"', DateTime.class);
            item.DateTo = (DateTime)JSON.deserialize('"2024-09-30T00:00:00"', DateTime.class);
            item.Qty_percent = 26.65;
            item.Qty_add_pcs = 0.0000;
            item.Qty_add_t = 0.0000;
            item.Region = 1;
            item.Grp3 = 1;
            item.SaleKdk = '1';
            item.Family = familyItem;
            item.StructConfig = structConfigItem;
            ItemList.add(Item);
        }

        structQuotaData.Items = ItemList;
        mockMessage.data = structQuotaData;

        return mockMessage;
    }

    private static ERPMessageParser.ErpToSfMessage_StructQuota createMockERPMessageWithoutFamily() {
        ERPMessageParser.ErpToSfMessage_StructQuota mockMessage = new ERPMessageParser.ErpToSfMessage_StructQuota();

        // Mock Metadata
        mockMessage.Metadata = new ERPMessageParser.MessageMetadata();
        mockMessage.Metadata.MsgType = 'TestType';
        mockMessage.Metadata.msgTimestamp = (DateTime)JSON.deserialize('"2024-09-01T00:00:00"', DateTime.class);
        mockMessage.Metadata.totalParts = 1;

        // Mock StructQuotaData
        ERPMessageParser.Options options = new ERPMessageParser.Options();
        options.DATEFROM = (DateTime)JSON.deserialize('"2024-09-01T00:00:00"', DateTime.class);
        options.DATETO = (DateTime)JSON.deserialize('"2024-09-30T00:00:00"', DateTime.class);
        
        ERPMessageParser.Partial partial = new ERPMessageParser.Partial();
        partial.Type = 'PERIOD';
        partial.Options = options;

        ERPMessageParser.StructQuotaData structQuotaData = new ERPMessageParser.StructQuotaData();
        structQuotaData.Mode = 'MODIFY';
        structQuotaData.Partial = partial;

        ERPMessageParser.StructQuotaItem item = new ERPMessageParser.StructQuotaItem();
        item.RowId = 2;
        List<ERPMessageParser.StructQuotaItem> ItemList = new List<ERPMessageParser.StructQuotaItem>{item};

        structQuotaData.Items = ItemList;
        mockMessage.data = structQuotaData;

        return mockMessage;
    }
}