force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Group3__c/Group3__c.object-meta.xml
<CustomObject>
    <label>Group3</label>
    <nameField>
        <label>Group 3</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group3__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/QuoteRequestDetail__c.object-meta.xml
<CustomObject>
    <label>Quota Request Detail</label>
    <nameField>
        <label>Family ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Add_Qty_pcs__c.field-meta.xml
<CustomField>
    <fullName>Add_Qty_pcs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Add Qty (pcs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AddQty (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Group3__c.field-meta.xml
<CustomField>
    <fullName>Group3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group3</label>
    <referenceTo>Group3__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/QuoteRequestHeader__c.field-meta.xml
<CustomField>
    <fullName>QuoteRequestHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Request Header</label>
    <referenceTo>QuoteRequestHeader__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/QuoteStructureDetail__c.field-meta.xml
<CustomField>
    <fullName>QuoteStructureDetail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Structure Detail</label>
    <referenceTo>QuoteStructureDetail__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/RoutesQuotesH__c.field-meta.xml
<CustomField>
    <fullName>RoutesQuotesH__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Quotes Hierarchy</label>
    <referenceTo>RouteQuotesH__c</referenceTo>
    <relationshipLabel>Quote Request Details</relationshipLabel>
    <relationshipName>Quota_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestHeader__c/QuoteRequestHeader__c.object-meta.xml
<CustomObject>
    <label>Quota Request Header</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas Request Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteRequestHeader__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <label>Add Qty (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestHeader__c/fields/Quote_t__c.field-meta.xml
<CustomField>
    <fullName>Quote_t__c</fullName>
    <label>Quote (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/QuoteStructureDetail__c.object-meta.xml
<CustomObject>
    <label>Quote Structure Detail</label>
    <nameField>
        <label>Route Family</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Structure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Add_Qty_pcs__c.field-meta.xml
<CustomField>
    <fullName>Add_Qty_pcs__c</fullName>
    <label>Add Qty (pcs)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AddQty (t)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/DateBegin__c.field-meta.xml
<CustomField>
    <fullName>DateBegin__c</fullName>
    <label>Date Begin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Group3__c.field-meta.xml
<CustomField>
    <fullName>Group3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group3</label>
    <referenceTo>Group3__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/RoutesQuotesH__c.field-meta.xml
<CustomField>
    <fullName>RoutesQuotesH__c</fullName>
    <label>Route Quotes Hierarchy</label>
    <referenceTo>RouteQuotesH__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quota_Structure_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>New object for Regions from IT ERP</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SendAdjustmentQuotaRequest.cls
public class SendAdjustmentQuotaRequest {

    @InvocableMethod
    public static void SendQuotaRequest(List<Id> quotaRequestHeaderIdList) {
        List<QuoteRequestDetail__c> quotaRequestDetailList = [SELECT Id, MarketSegment__c, Family__r.ID_ERP__c, Region__r.ID_ERP__c, Quote_t__c,
                                                                     Manager__r.ID_ERP__c, Group3__r.ID_ERP__c, DateBegin__c, Percent__c, 
                                                                     AddQty_t__c, Add_Qty_pcs__c, RoutesQuotesH__c, QuoteStructureDetail__c,
                                                                     QuoteStructureDetail__r.ID_ERP__c
                                                              FROM QuoteRequestDetail__c 
                                                              WHERE QuoteRequestHeader__c = :quotaRequestHeaderIdList.get(0)];

        String data = getJSONData(quotaRequestDetailList);
        System.enqueueJob(new SendAdjustmentQuotaCalloutJob(data, quotaRequestDetailList));
    }

    public static String getJSONData(List<QuoteRequestDetail__c> quotaRequestDetailList) {
        JSONGenerator jsonToSend = JSON.createGenerator(true);

		jsonToSend.writeStartArray();
		
		for (QuoteRequestDetail__c quotaRequestDetail : quotaRequestDetailList) {
			jsonToSend.writeStartObject();
			jsonToSend.writeObjectField('SegmentCode', quotaRequestDetail.MarketSegment__c);
			jsonToSend.writeObjectField('FamilyId', quotaRequestDetail.Family__r?.ID_ERP__c);
			jsonToSend.writeObjectField('DateFrom', quotaRequestDetail.DateBegin__c);
			jsonToSend.writeObjectField('Quota_percent', quotaRequestDetail.Percent__c);
			jsonToSend.writeObjectField('Quota_add_t', quotaRequestDetail.AddQty_t__c);
			jsonToSend.writeObjectField('Quota_add_pcs', quotaRequestDetail.Add_Qty_pcs__c);

            if(quotaRequestDetail.Region__r?.ID_ERP__c != null) {
                jsonToSend.writeObjectField('RegionId', quotaRequestDetail.Region__r.ID_ERP__c);
            } else {
                jsonToSend.writeNullField('RegionId');
            }

            if(quotaRequestDetail.Manager__r?.ID_ERP__c != null) {
                jsonToSend.writeObjectField('SaleKdk', quotaRequestDetail.Manager__r.ID_ERP__c);
            } else {
                jsonToSend.writeNullField('SaleKdk');
            }

            if(quotaRequestDetail.Group3__r?.ID_ERP__c != null) {
                jsonToSend.writeObjectField('Grp3Id', quotaRequestDetail.Group3__r.ID_ERP__c);
            } else {
                jsonToSend.writeNullField('Grp3Id');
            }

			jsonToSend.writeEndObject();
		}

		jsonToSend.writeEndArray();

		System.debug('JSON to send - ' + jsonToSend.getAsString());

		return jsonToSend.getAsString();
	}
}