force-app/main/default/objects/SalesBudget__c/SalesBudget__c.object-meta.xml
<CustomObject>
    <label>Sales Budget</label>
    <nameField>
        <label>Sales Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>Sales budget ID in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>Sales budget ID in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/SalesBudgetRecord__c.object-meta.xml
<CustomObject>
    <label>Sales Budget Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Budget Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudgetRecord__c/fields/ExchangeTimestamp__c.field-meta.xml
<CustomField>
    <fullName>ExchangeTimestamp__c</fullName>
    <description>Timestamp of the message received from ERP when the record was imported.</description>
    <label>Exchange Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesBudget__c.field-meta.xml
<CustomField>
    <fullName>SalesBudget__c</fullName>
    <label>Sales Budget</label>
    <referenceTo>SalesBudget__c</referenceTo>
    <relationshipLabel>Sales Budget Records</relationshipLabel>
    <relationshipName>Sales_Budget_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/SalesBudgetCleaning.cls
global class SalesBudgetCleaning implements Database.Batchable<SObject> {

    private final String budgetId;
    private final Long messageTimeStamp;
    private Integer recordsDeleted = 0;

    global SalesBudgetCleaning(String budId, Long msgTS) {
        budgetId = budId;
        messageTimeStamp = msgTS;
    }

    global Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator('SELECT Id FROM SalesBudgetRecord__c WHERE SalesBudget__r.ID_ERP__c  = :budgetId AND ExchangeTimestamp__c < :messageTimestamp');
    }

    global void execute(Database.BatchableContext context, List<SObject> scope) {
        Database.delete(scope, false);
        recordsDeleted += scope.size();
    }

    global void finish(Database.BatchableContext context) {
        // Send an email with execution information
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new List<String>{'v.rybak@polytech.software'});
        email.setSubject('SalesBudgetCleaning Batch Job Completed');
        email.setPlainTextBody('The SalesBudgetCleaning batch job has completed. ' + recordsDeleted + ' records were deleted.');
        Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{email});
    }

}