force-app/main/default/objects/Excel_Import_Setting__mdt/Excel_Import_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Excel Import Setting</label>
    <pluralLabel>Excel Import Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Excel_Import_Setting__mdt/fields/Required_Fields__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields__c</fullName>
    <label>Required Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Excel_Import_Setting__mdt/fields/Sheet_Columns__c.field-meta.xml
<CustomField>
    <fullName>Sheet_Columns__c</fullName>
    <label>Sheet Columns</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Excel_Import_Setting__mdt/fields/Sheet_Name__c.field-meta.xml
<CustomField>
    <fullName>Sheet_Name__c</fullName>
    <label>Sheet Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/excelImportController.cls
/**
 * Created by volodymyr on 31.07.21.
 */

public with sharing class excelImportController {
    @AuraEnabled(cacheable=true)
    public static List<Excel_Import_Setting__mdt> getImportSettings() {
       return [SELECT Object_Name__c,Sheet_Columns__c,Sheet_Name__c , Required_Fields__c FROM Excel_Import_Setting__mdt];
        }
    // @AuraEnabled
    // public static string deleteExsistingRecords(String q){
    //         DeleteImportDataBatch deleteRecords = new DeleteImportDataBatch(q);
	// 		database.executeBatch(deleteRecords, 200);
    //         return 'Success';
    // }
    @AuraEnabled 
    public static String insertRecords(List<sObject> records) {        	
            ExcelImportBatch db = new ExcelImportBatch(records);
			database.executeBatch(db, 2000);

       		return 'Success';
    }
}