force-app/main/default/objects/DrawingVersion__c/DrawingVersion__c.object-meta.xml
<CustomObject>
    <label>Drawing Version</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drawings Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Number of the order in the IT-Enterprise system</description>
    <externalId>true</externalId>
    <inlineHelpText>Number of the order in the IT-Enterprise system</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop</description>
    <inlineHelpText>Production shop</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <default>true</default>
                <label>Confirmed by mill</label>
            </value>
            <value>
                <fullName>Produced</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItemGeneral__c/OrderItemGeneral__c.object-meta.xml
<CustomObject>
    <label>Order Item: General Info</label>
    <nameField>
        <label>ITE Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Item: General Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemGeneral__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Item: General Info</relationshipLabel>
    <relationshipName>Order_Item_General_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemGeneral__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Order_Items_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemGeneral__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Item: General Info</relationshipLabel>
    <relationshipName>Order_Item_General_Info</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemGeneral__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>TEXT(OrderProduct__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoKLW__c/OrderItemProductInfoKLW__c.object-meta.xml
<CustomObject>
    <label>Order Item: Product Info (KLW)</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items: Product Info (KLW)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemProductInfoKLW__c/fields/DrawingVersion__c.field-meta.xml
<CustomField>
    <fullName>DrawingVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawing</label>
    <referenceTo>DrawingVersion__c</referenceTo>
    <relationshipLabel>Order Items: Product Info (KLW)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_KLW</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoKLW__c/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <formula>BLANKVALUE(OrderProduct__r.ITENumber__c, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ITE Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoKLW__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Items: Product Info (KLW)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_KLW</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoKLW__c/fields/SpecVersion__c.field-meta.xml
<CustomField>
    <fullName>SpecVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specification</label>
    <referenceTo>SpecVersion__c</referenceTo>
    <relationshipLabel>Order Items: Product Info (KLW)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_KLW</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoKLW__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OrderItemStage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoPipes__c/OrderItemProductInfoPipes__c.object-meta.xml
<CustomObject>
    <label>Order Item: Product Info (Pipes)</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items: Product Info (Pipes)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItemProductInfoPipes__c/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <formula>OrderProduct__r.ITENumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ITE Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoPipes__c/fields/OrderProduct__c.field-meta.xml
<CustomField>
    <fullName>OrderProduct__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Product</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Order Items: Product Info (Pipes)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_Pipes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoPipes__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items: Product Info (Pipes)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_Pipes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItemProductInfoPipes__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Order Items: Product Info (Pipes)</relationshipLabel>
    <relationshipName>Order_Items_Product_Info_Pipes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SpecVersion__c/SpecVersion__c.object-meta.xml
<CustomObject>
    <label>Specification Version</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specification Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SpecVersion__c/fields/DrawingVersion__c.field-meta.xml
<CustomField>
    <fullName>DrawingVersion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawing</label>
    <referenceTo>DrawingVersion__c</referenceTo>
    <relationshipLabel>Specification Versions</relationshipLabel>
    <relationshipName>Specification_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/OrderItemStage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Drafting</fullName>
    </customValue>
    <customValue>
        <fullName>Processing</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Produced</fullName>
    </customValue>
    <customValue>
        <fullName>Dispatched</fullName>
    </customValue>
    <customValue>
        <fullName>Shipped</fullName>
    </customValue>
    <customValue>
        <fullName>Placed</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Hold</fullName>
    </customValue>
    <masterLabel>Order Item Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderItemChildServiceTest.cls
@IsTest
private class OrderItemChildServiceTest {

    @TestSetup
    static void setup() {
        // Create test Account
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        // Create test Opportunity
        Opportunity testOpp = new Opportunity(
                Name = 'Test Opportunity',
                AccountId = testAccount.Id,
                StageName = 'Prospecting',
                CloseDate = Date.today().addDays(30)
        );
        insert testOpp;

        // Create test Product
        Product2 testProduct = new Product2(
                Name = 'Test Product',
                IsActive = true
        );
        insert testProduct;

        // Get Standard Pricebook
        Id pricebookId = Test.getStandardPricebookId();

        // Create PricebookEntry
        PricebookEntry testPbe = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = testProduct.Id,
                UnitPrice = 100,
                IsActive = true
        );
        insert testPbe;
    }

    @IsTest
    static void testSafeTrim_NullString() {
        String result = OrderItemChildService.safeTrim(null, 10);
        System.assertEquals(null, result, 'Should return null for null input');
    }

    @IsTest
    static void testSafeTrim_EmptyString() {
        String result = OrderItemChildService.safeTrim('', 10);
        System.assertEquals(null, result, 'Should return null for empty string');
    }

    @IsTest
    static void testSafeTrim_BlankString() {
        String result = OrderItemChildService.safeTrim('   ', 10);
        System.assertEquals(null, result, 'Should return null for blank string');
    }

    @IsTest
    static void testSafeTrim_StringShorterThanMax() {
        String result = OrderItemChildService.safeTrim('test', 10);
        System.assertEquals('test', result, 'Should return original string when shorter than max');
    }

    @IsTest
    static void testSafeTrim_StringLongerThanMax() {
        String result = OrderItemChildService.safeTrim('this is a long string', 10);
        System.assertEquals('this is a ', result, 'Should truncate string to max length');
    }

    @IsTest
    static void testFillChildRecords_NullOrderItems() {
        Test.startTest();
        OrderItemChildService.fillChildRecords(null, null, null, null);
        Test.stopTest();

        // Should not throw exception - verify no records created
        List<OrderItemGeneral__c> generals = [SELECT Id FROM OrderItemGeneral__c];
        System.assertEquals(0, generals.size(), 'No records should be created for null input');
    }

    @IsTest
    static void testFillChildRecords_EmptyOrderItems() {
        Test.startTest();
        OrderItemChildService.fillChildRecords(new List<OrderItem>(), null, null, null);
        Test.stopTest();

        // Should not throw exception - verify no records created
        List<OrderItemGeneral__c> generals = [SELECT Id FROM OrderItemGeneral__c];
        System.assertEquals(0, generals.size(), 'No records should be created for empty list');
    }

    @IsTest
    static void testFillChildRecords_TubesInsert() {
        // Get test data
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Product2Id = :product.Id LIMIT 1];

        // Create Order with MarketSegment != '00006' (Tubes)
        Order testOrder = new Order(
                AccountId = opp.AccountId,
                OpportunityId = opp.Id,
                EffectiveDate = Date.today(),
                Status = 'Draft',
                Pricebook2Id = pbe.Pricebook2Id,
                MarketSegment__c = '00001'
        );
        insert testOrder;

        // Create OrderItem
        OrderItem testOI = new OrderItem(
                OrderId = testOrder.Id,
                Product2Id = product.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 10,
                UnitPrice = 100,
                ITENumber__c = 'ITE-001'
        );
        insert testOI;

        Test.startTest();
        OrderItemChildService.fillChildRecords(
                new List<OrderItem>{testOI},
                new Map<Id, Order>{testOrder.Id => testOrder},
                new Map<Id, SpecVersion__c>(),
                new Map<Id, DrawingVersion__c>()
        );
        Test.stopTest();

        // Verify General record created
        List<OrderItemGeneral__c> generals = [
                SELECT Id, OrderProduct__c, Shop__c, Name, Product__c
                FROM OrderItemGeneral__c
                WHERE OrderProduct__c = :testOI.Id
        ];
        System.assertEquals(1, generals.size(), 'Should create one OrderItemGeneral__c');
        System.assertEquals(testOI.Id, generals[0].OrderProduct__c, 'Should link to OrderItem');
        System.assertEquals('ITE-001', generals[0].Name, 'Should set Name from ITENumber__c');
        System.assertEquals(product.Id, generals[0].Product__c, 'Should set Product__c');

        // Verify Pipes record created
        List<OrderItemProductInfoPipes__c> pipes = [
                SELECT Id, OrderProduct__c, Name
                FROM OrderItemProductInfoPipes__c
                WHERE OrderProduct__c = :testOI.Id
        ];
        System.assertEquals(1, pipes.size(), 'Should create one OrderItemProductInfoPipes__c');
        System.assertEquals(testOI.Id, pipes[0].OrderProduct__c, 'Should link to OrderItem');
        System.assertEquals('ITE-001', pipes[0].Name, 'Should set Name');

        // Verify no KLW record created
        List<OrderItemProductInfoKLW__c> klws = [
                SELECT Id FROM OrderItemProductInfoKLW__c WHERE OrderProduct__c = :testOI.Id
        ];
        System.assertEquals(0, klws.size(), 'Should not create OrderItemProductInfoKLW__c for tubes');
    }

    @IsTest
    static void testFillChildRecords_MultipleOrderItems() {
        // Get test data
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity LIMIT 1];
        Product2 product = [SELECT Id FROM Product2 LIMIT 1];
        PricebookEntry pbe = [SELECT Id, Pricebook2Id FROM PricebookEntry WHERE Product2Id = :product.Id LIMIT 1];

        // Create Orders
        Order tubesOrder = new Order(
                AccountId = opp.AccountId,
                OpportunityId = opp.Id,
                EffectiveDate = Date.today(),
                Status = 'Draft',
                Pricebook2Id = pbe.Pricebook2Id,
                MarketSegment__c = '00001'
        );
        Order klwOrder = new Order(
                AccountId = opp.AccountId,
                OpportunityId = opp.Id,
                EffectiveDate = Date.today(),
                Status = 'Draft',
                Pricebook2Id = pbe.Pricebook2Id,
                MarketSegment__c = '00006'
        );
        insert new List<Order>{tubesOrder, klwOrder};

        // Create OrderItems
        OrderItem tubesOI = new OrderItem(
                OrderId = tubesOrder.Id,
                Product2Id = product.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 10,
                UnitPrice = 100,
                ITENumber__c = 'TUBE-001'
        );
        OrderItem klwOI = new OrderItem(
                OrderId = klwOrder.Id,
                Product2Id = product.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 20,
                UnitPrice = 150,
                ITENumber__c = 'KLW-001',
                Stage__c = 'Confirmed'
        );
        insert new List<OrderItem>{tubesOI, klwOI};

        Test.startTest();
        OrderItemChildService.fillChildRecords(
                new List<OrderItem>{tubesOI, klwOI},
                new Map<Id, Order>{tubesOrder.Id => tubesOrder, klwOrder.Id => klwOrder},
                new Map<Id, SpecVersion__c>(),
                new Map<Id, DrawingVersion__c>()
        );
        Test.stopTest();

        // Verify 2 General records created
        List<OrderItemGeneral__c> generals = [SELECT Id FROM OrderItemGeneral__c];
        System.assertEquals(2, generals.size(), 'Should create two OrderItemGeneral__c records');

        // Verify 1 Pipes and 1 KLW record created
        List<OrderItemProductInfoPipes__c> pipes = [SELECT Id FROM OrderItemProductInfoPipes__c];
        System.assertEquals(1, pipes.size(), 'Should create one Pipes record');

        List<OrderItemProductInfoKLW__c> klws = [SELECT Id FROM OrderItemProductInfoKLW__c];
        System.assertEquals(1, klws.size(), 'Should create one KLW record');
    }
}