force-app/main/default/objects/Reclamation__c/Reclamation__c.object-meta.xml
<CustomObject>
    <label>Reclamation</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reclamations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reclamation__c/fields/ERP_Number__c.field-meta.xml
<CustomField>
    <fullName>ERP_Number__c</fullName>
    <label>ERP Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/No_Refund__c.field-meta.xml
<CustomField>
    <fullName>No_Refund__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Refund</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reclamation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Sended</fullName>
            </value>
            <value>
                <fullName>_1</fullName>
                <label>Registered</label>
            </value>
            <value>
                <fullName>_2</fullName>
                <label>Is being considered</label>
            </value>
            <value>
                <fullName>_8</fullName>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>_9</fullName>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>_5</fullName>
                <label>Director decision</label>
            </value>
            <value>
                <fullName>Accepted_PendingCompensation</fullName>
                <label>Accepted  (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially_PendingCompensation</fullName>
                <label>Accepted partially (pending compensation)</label>
            </value>
            <value>
                <fullName>AcceptedPartially</fullName>
                <label>Accepted partially</label>
            </value>
            <value>
                <fullName>OnHold</fullName>
                <label>On Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteReclamationDatatablePDFController.cls
public without sharing class SiteReclamationDatatablePDFController {
    public List<Reclamation__c> reclamationsList{get;set;}

    public SiteReclamationDatatablePDFController() {
        system.debug(ApexPages.currentPage().getUrl());
        System.debug(ApexPages.currentPage().getParameters());
        String reclamationIds = ApexPages.currentPage().getParameters().get('Ids');
        System.debug(reclamationIds);
        List<Id> ids =(List<id>)  JSON.deserialize(reclamationIds, List<id>.class);
        System.debug(ids);
        this.reclamationsList = [SELECT id, ERP_Number__c, CreatedDate, toLabel(Status__c), Comment__c, Owner.Name, No_Refund__c FROM Reclamation__c
                                WHERE id in: ids];       
        System.debug(this.reclamationsList);                              
    }

    
}