force-app/main/default/objects/Opportunity/fields/AssignedBOS__c.field-meta.xml
<CustomField>
    <fullName>AssignedBOS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned back office specialist</description>
    <inlineHelpText>Assigned back office specialist</inlineHelpText>
    <label>Assigned BO specialist</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>User.Profile.UserType</field>
            <operation>notEqual</operation>
            <value>CSPLitePortal</value>
        </filterItems>
        <filterItems>
            <field>User.SalesDivision__c</field>
            <operation>equals</operation>
            <valueField>$Source.MarketSegment__c</valueField>
        </filterItems>
        <filterItems>
            <field>User.SalesDivision__c</field>
            <operation>equals</operation>
            <valueField>$Source.CrossMarketSegment__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities_AssignedBOS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cancel_reason__c.field-meta.xml
<CustomField>
    <fullName>Cancel_reason__c</fullName>
    <label>Cancel reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Out of product range/size</fullName>
            </value>
            <value>
                <fullName>Out of steel grade</fullName>
            </value>
            <value>
                <fullName>Out of standard</fullName>
            </value>
            <value>
                <fullName>Out of shipment conditions</fullName>
            </value>
            <value>
                <fullName>Client refusal</fullName>
            </value>
            <value>
                <fullName>Price not agreed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/AssignedBOS__c.field-meta.xml
<CustomField>
    <fullName>AssignedBOS__c</fullName>
    <description>Assigned back office specialist.</description>
    <inlineHelpText>Assigned back office specialist. If selected, then it will be automatically selected by default in new opportunities of this user.</inlineHelpText>
    <label>Assigned BO Specialist</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$User.Department</field>
            <operation>contains</operation>
            <value>Sales Support Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <relationshipName>SalesManagers</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SendPostFromFlowCancelledOpp.cls
public class SendPostFromFlowCancelledOpp {
	
    @InvocableMethod
   public static void sendPost(List<String> idCancelledProduct) {
    system.debug(idCancelledProduct);
    Opportunity assignedBOCancelledOpportunity =  [SELECT AssignedBOS__c,Cancel_reason__c,id, MarketSegment__c FROM Opportunity WHERE id=:idCancelledProduct[0] LIMIT 1] ;
    String userIdBO = assignedBOCancelledOpportunity.AssignedBOS__c;
    List<String> toAddressesList = new List<String>();

    if(assignedBOCancelledOpportunity.MarketSegment__c == '00004') {
        toAddressesList = Label.Emails_for_Cancelled_Opportunity.split(';');
    }
    
    String assignedBosId = userIdBO;
    String urlProduction = system.label.OrganizationURL;
    system.debug(userIdBO);  
    
    
    String createMessage =  createMessageEmail(assignedBOCancelledOpportunity,urlProduction,idCancelledProduct[0]);  
    FeedItem post2 = new FeedItem();
    post2.ParentId = assignedBosId;
    post2.Body = createMessage;  
       
       if(assignedBosId!=null){
           insert post2; 
       }
         
  	Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();    
    message.optOutPolicy = 'FILTER';
    message.subject = 'Cancelled opportunity';
    message.htmlbody = createMessage; 
       try{                  
           User assignedBosEmail  = [SELECT Email FROM USER WHERE id=:assignedBosId limit 1];
           toAddressesList.add(assignedBosEmail.Email);            
           message.toAddresses = toAddressesList;   
           Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
           Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
       } catch (exception e){
           system.debug(e.getMessage());
       }
   }
    
    public static String createMessageEmail(Opportunity oppToCancel, String urlProduction, String idCancelledProduct){
        String createdMessage;        
        createdMessage = 'Request for cancell opportunity. Reason - ' +oppToCancel.Cancel_reason__c +'. Link: '+ urlProduction+ '/'+idCancelledProduct;
        return createdMessage;
    }
}