force-app/main/default/objects/Opportunity/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Number of the order in the IT-Enterprise system</description>
    <externalId>true</externalId>
    <inlineHelpText>Number of the order in the IT-Enterprise system</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <description>Market segment where the products are being sold</description>
    <inlineHelpText>Market segment where the products are being sold</inlineHelpText>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Balance_t__c.field-meta.xml
<CustomField>
    <fullName>Balance_t__c</fullName>
    <label>Balance t</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CDD__c.field-meta.xml
<CustomField>
    <fullName>CDD__c</fullName>
    <description>Critical Date of Dispatch (the last date when the mill has to dispatch the products from the shop).</description>
    <inlineHelpText>Critical Date of Dispatch (the last date when the mill has to dispatch the products from the shop).</inlineHelpText>
    <label>CDD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/FinalCDD__c.field-meta.xml
<CustomField>
    <fullName>FinalCDD__c</fullName>
    <formula>IF(ISBLANK(ConfirmedCDD__c), CDD__c, ConfirmedCDD__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final CDD</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>Number of the related order item in the IT-Enterprise system.</description>
    <inlineHelpText>Number of the related order item in the IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quota_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Date__c</fullName>
    <label>Quota Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/QuotaType__c.field-meta.xml
<CustomField>
    <fullName>QuotaType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The type of quota that the item is related to.</description>
    <inlineHelpText>The type of production shop quota that the item is related to.</inlineHelpText>
    <label>Quota Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>QuotaType__c.Shop__c</field>
            <operation>equals</operation>
            <valueField>$Source.Shop__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>OpportunityProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop that will produce this product</description>
    <inlineHelpText>Production shop that will produce this product</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage of the current opportunity item</description>
    <inlineHelpText>Stage of the current opportunity item</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Commercial Dept</label>
            </value>
            <value>
                <fullName>Processing</fullName>
                <label>Tech &amp; Fin Evaluation</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
                <label>Confirmed by mill</label>
            </value>
            <value>
                <fullName>Produced</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
                <label>Delivered acc. INCOTERMS</label>
            </value>
            <value>
                <fullName>Placed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/ITENumber__c.field-meta.xml
<CustomField>
    <fullName>ITENumber__c</fullName>
    <description>The order number in IT-Enterprise system.</description>
    <externalId>true</externalId>
    <inlineHelpText>The order number in IT-Enterprise system.</inlineHelpText>
    <label>ITE Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Production_Quota__c/Production_Quota__c.object-meta.xml
<CustomObject>
    <label>Production Quota</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Production Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Quota__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Quota_Type__c.field-meta.xml
<CustomField>
    <fullName>Quota_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotaType__c/QuotaType__c.object-meta.xml
<CustomObject>
    <description>Type of quota that is defined by production shop for particular sales manager</description>
    <label>Quota Type</label>
    <nameField>
        <label>Quota Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotas Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotaType__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop that the quota relates to</description>
    <inlineHelpText>Production shop that the quota relates to</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Quotas Types</relationshipLabel>
    <relationshipName>QuotasTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunitiesWithoutOrderBatch.cls
global class OpportunitiesWithoutOrderBatch implements Database.Batchable<SObject> {
	global String oppIdsWihoutOrder; 
    
    global Database.QueryLocator start(Database.BatchableContext context) {		              
        return Database.getQueryLocator('SELECT id, Sales_Manager__c,Product__c,Market_Segment__c,Quota_Type__c,Shop__c,Period__c FROM Production_Quota__c' );
	}
    
    global void execute(Database.BatchableContext context, List<Production_Quota__c> scope) {       
        
        
        for(Production_Quota__c prodQuota : scope){                                 
        Set<Id> opportunityIds = new Set<Id>();  
        Set<Id> oppWithoutOrder = new Set<Id>();  
       
       
              
        String sbrQuotaType = prodQuota.Quota_Type__c;
        String sbrMarketSegment = prodQuota.Market_Segment__c;
        String sbrSaleManager = prodQuota.Sales_Manager__c;
        String sbrProduct = prodQuota.Product__c;
        String sbrShop = prodQuota.Shop__c;
        Date startPeriod = prodQuota.Period__c;
        Date endPeriod = startPeriod.addMonths(1);
        List<OpportunityLineItem> oppItemList = new List<OpportunityLineItem>();
              
        try{                  
        oppItemList = [SELECT Id, Opportunity.StageName, Opportunity.Id, QuotaType__c, Name, OpportunityId, CDD__c, FinalCDD__c, Quota_Date__c, CreatedDate, Product2Id, Quantity, Shop__c,
                                                 ITENumber__c,Balance_t__c
                                                 FROM OpportunityLineItem 
                                                 WHERE Product2Id=:sbrProduct 
                                                 AND Opportunity.OwnerId =:sbrSaleManager 
                                                 AND Opportunity.MarketSegment__c =:sbrMarketSegment
                                                 AND QuotaType__c =:sbrQuotaType
                                                 AND Shop__c =:sbrShop
                                                 AND FinalCDD__c != NULL
                                                 AND ((FinalCDD__c > :startPeriod OR FinalCDD__c = :startPeriod) AND FinalCDD__c < :endPeriod)  
                       							 AND Opportunity.StageName = 'Closed Won'	
                       							 AND (Stage__c = 'Drafting' OR Stage__c = 'Processing' OR Stage__c = 'Confirmed' OR Stage__c = 'Placed')
                                                 ];
               
         } catch (Exception e){
            system.debug(e.getMessage());
        }
        
        Set<Id> idsForSearchOrders = new Set<Id>();
        Set<Id> idsValidatedOpportunities = new Set<Id>();
        if(oppItemList.size()>0){                        
            for(OpportunityLineItem oppItem : oppItemList ){
                idsForSearchOrders.add(oppItem.Opportunity.id);
            }       
        for(Id oppId:idsForSearchOrders){
            try{
                Order ordersNotClosed = [SELECT Opportunityid FROM Order WHERE Opportunityid = :oppId limit 1];
            } catch(Exception e){
                oppIdsWihoutOrder = oppId + '; ';
                system.debug(e.getMessage());
            }
             
        }                   
        } 
            }
        if(oppIdsWihoutOrder!=null){
            sendNotificationEmail('yayarik98@gmail.com',oppIdsWihoutOrder);
        }

	}
    
    global void finish(Database.BatchableContext context) {
		
	}
    
    global static void sendNotificationEmail(String email,String oppIds){
        
        List<String> orderOwnerEmails = new List<String>();
        orderOwnerEmails.add(email);
        String mailBody = oppIds;
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.toAddresses = orderOwnerEmails;
        message.optOutPolicy = 'FILTER';
        message.subject = 'Opportunities without orders';
        message.htmlbody = mailBody;
        Messaging.SingleEmailMessage[] messages =   new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        
    }
}