force-app/main/default/objects/Opportunity/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Anticipated difference between opportunity revenue and cost of production, calculated by finance department in price approval process.</description>
    <formula>IF(CountOfProductsWithoutMargin__c  = 0, MarginSum__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Anticipated difference between opportunity revenue and cost of production, calculated by finance department in price approval process.</inlineHelpText>
    <label>Total Margin (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Total Margin</label>
    <summarizedField>OrderItem.Margin__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <summarizedField>OrderItemProductInfoKLW__c.Inq_Total__c</summarizedField>
    <summaryForeignKey>OrderItemProductInfoKLW__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/SalesBudget__c.object-meta.xml
<CustomObject>
    <label>Sales Budget</label>
    <nameField>
        <label>Sales Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin (USD)</label>
    <summarizedField>SalesBudgetRecord__c.Margin__c</summarizedField>
    <summaryForeignKey>SalesBudgetRecord__c.SalesBudget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <formula>Case(Type__c,
					&apos;Y&apos;, Text(Year__c) + &apos;: Year Initial&apos;,
					&apos;HY1&apos;, Text(Year__c) + &apos;: First Half Year&apos;,
					&apos;HY2&apos;, Text(Year__c) + &apos;: Second Half Year&apos;,
					&apos;Q1&apos;, Text(Year__c) + &apos;: Q1 Corrected&apos;,
					&apos;Q2&apos;, Text(Year__c) + &apos;: Q2 Corrected&apos;,
					&apos;Q3&apos;, Text(Year__c) + &apos;: Q3 Corrected&apos;,
					&apos;Q4&apos;, Text(Year__c) + &apos;: Q4 Corrected&apos;,
					null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/ProductionAmount__c.field-meta.xml
<CustomField>
    <fullName>ProductionAmount__c</fullName>
    <label>Dispatched Amount (t)</label>
    <summarizedField>SalesBudgetRecord__c.ProductionAmount__c</summarizedField>
    <summaryForeignKey>SalesBudgetRecord__c.SalesBudget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue (USD)</label>
    <summarizedField>SalesBudgetRecord__c.Revenue__c</summarizedField>
    <summaryForeignKey>SalesBudgetRecord__c.SalesBudget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/SalesAmount__c.field-meta.xml
<CustomField>
    <fullName>SalesAmount__c</fullName>
    <label>Sales Amount (t)</label>
    <summarizedField>SalesBudgetRecord__c.SalesAmount__c</summarizedField>
    <summaryForeignKey>SalesBudgetRecord__c.SalesBudget__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Year Initial</label>
            </value>
            <value>
                <fullName>HY1</fullName>
                <label>Corrected HY1</label>
            </value>
            <value>
                <fullName>HY2</fullName>
                <label>Corrected HY2</label>
            </value>
            <value>
                <fullName>Q1</fullName>
                <label>Corrected Q1</label>
            </value>
            <value>
                <fullName>Q2</fullName>
                <label>Corrected Q2</label>
            </value>
            <value>
                <fullName>Q3</fullName>
                <label>Corrected Q3</label>
            </value>
            <value>
                <fullName>Q4</fullName>
                <label>Corrected Q4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/SalesBudgetRecord__c.object-meta.xml
<CustomObject>
    <label>Sales Budget Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Budget Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudgetRecord__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Margin on total amount of product</description>
    <inlineHelpText>Margin on total amount of product</inlineHelpText>
    <label>Margin (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/PeriodMonth__c.field-meta.xml
<CustomField>
    <fullName>PeriodMonth__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/PeriodQuarter__c.field-meta.xml
<CustomField>
    <fullName>PeriodQuarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Q1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Q2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Q3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Q4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/PeriodYear__c.field-meta.xml
<CustomField>
    <fullName>PeriodYear__c</fullName>
    <defaultValue>Year(DATEVALUE($System.OriginDateTime))</defaultValue>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/ProductionAmount__c.field-meta.xml
<CustomField>
    <fullName>ProductionAmount__c</fullName>
    <description>Amount of production in metric tons</description>
    <inlineHelpText>Amount of production in metric tons</inlineHelpText>
    <label>Dispatched Amount (t)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue (USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesAmount__c.field-meta.xml
<CustomField>
    <fullName>SalesAmount__c</fullName>
    <description>Amount of products that have been sold and shipped to the client</description>
    <inlineHelpText>Amount of products that have been sold and shipped to the client</inlineHelpText>
    <label>Sales Amount (t)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesBudget__c.field-meta.xml
<CustomField>
    <fullName>SalesBudget__c</fullName>
    <label>Sales Budget</label>
    <referenceTo>SalesBudget__c</referenceTo>
    <relationshipLabel>Sales Budget Records</relationshipLabel>
    <relationshipName>Sales_Budget_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesManager__c.field-meta.xml
<CustomField>
    <fullName>SalesManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesBudget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/SalesPlanFact__c.object-meta.xml
<CustomObject>
    <label>Sales Plan and Fact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plan and Fact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanFact__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/PeriodYear__c.field-meta.xml
<CustomField>
    <fullName>PeriodYear__c</fullName>
    <formula>YEAR(Period__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/ProductionAmount__c.field-meta.xml
<CustomField>
    <fullName>ProductionAmount__c</fullName>
    <label>Dispatched Amount (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/SalesAmount__c.field-meta.xml
<CustomField>
    <fullName>SalesAmount__c</fullName>
    <label>Sales Amount (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Budget</fullName>
                <color>#FFCC33</color>
                <label>Initial Budget</label>
            </value>
            <value>
                <fullName>Corrected Budget</fullName>
                <color>#DDDDDD</color>
                <label>Corrected Budget</label>
            </value>
            <value>
                <fullName>Actual Budget</fullName>
                <color>#78C953</color>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Plan</fullName>
                <color>#AFCADF</color>
                <label>Plan</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <color>#2F5D85</color>
                <label>Open Orders</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <color>#419249</color>
                <label>Open Orders &amp; Opps</label>
            </value>
            <value>
                <fullName>Fact</fullName>
                <color>#2F5D85</color>
                <label>Fact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Fact.recordType-meta.xml
<RecordType>
    <fullName>Fact</fullName>
    <active>true</active>
    <description>Actual production and sales data</description>
    <label>Fact</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <description>Open order</description>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Plan.recordType-meta.xml
<RecordType>
    <fullName>Plan</fullName>
    <active>true</active>
    <description>Production and sales plan data</description>
    <label>Plan</label>
</RecordType>

force-app/main/default/classes/SalesBudgetRecordTriggerHandlerTest.cls
@isTest 
private class SalesBudgetRecordTriggerHandlerTest {

	@isTest
	private static void testMonth() {
		SalesBudget__c sb = new SalesBudget__c();
		Integer year = Date.today().year();
		sb.Type__c = 'Y';
		sb.Year__c = year;
		sb.Name = year + ' - Initial';
		sb.Approved__c = true;
		insert sb;

		ID rtPlanMonthId = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'SalesBudgetRecord__c' And Name = 'Plan Month'].Id;
		SalesBudgetRecord__c sbr = new SalesBudgetRecord__c();
		sbr.RecordTypeId = rtPlanMonthId;
		sbr.SalesBudget__c = sb.Id;
		sbr.PeriodMonth__c = '05';
		sbr.PeriodYear__c = year;
		sbr.SalesManager__c = UserInfo.getUserId();
		sbr.ProductionAmount__c = 90;
		sbr.SalesAmount__c = 90;
		sbr.Revenue__c = 90000;
		sbr.Margin__c = 18000;
		insert sbr;
		
		Id sbrId = sbr.Id;

		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-05-01'), sbr.Period__c);

		sbr.PeriodMonth__c = '02';
		update sbr;
		
		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-02-01'), sbr.Period__c);
	}

	@isTest
	private static void testQuarter() {
		SalesBudget__c sb = new SalesBudget__c();
		Integer year = Date.today().year();
		sb.Type__c = 'Y';
		sb.Year__c = year;
		sb.Name = year + ' - Initial';
		sb.Approved__c = true;
		insert sb;

		ID rtPlanQuarterId = [SELECT Id, Name FROM RecordType WHERE SobjectType = 'SalesBudgetRecord__c' And Name = 'Plan Quarter'].Id;
		System.debug('--- Record Type ID: ' + rtPlanQuarterId);
		SalesBudgetRecord__c sbr = new SalesBudgetRecord__c();
		sbr.RecordTypeId = rtPlanQuarterId;
		sbr.SalesBudget__c = sb.Id;
		sbr.PeriodQuarter__c = '1';
		sbr.PeriodYear__c = year;
		sbr.SalesManager__c = UserInfo.getUserId();
		sbr.ProductionAmount__c = 90;
		sbr.SalesAmount__c = 90;
		sbr.Revenue__c = 90000;
		sbr.Margin__c = 18000;
		insert sbr;

		SalesPlanFact__c spfOpp = new SalesPlanFact__c();
		spfOpp.Type__c = 'Opportunity';
		SalesPlanFact__c spfOrder = new SalesPlanFact__c();
		spfOrder.Type__c = 'Order';
		SalesPlanFact__c spfPlan = new SalesPlanFact__c();
		spfPlan.Type__c = 'Plan';
		SalesPlanFact__c spfFact = new SalesPlanFact__c();
		spfFact.Type__c = 'Fact';

		insert new List<SalesPlanFact__c>{spfOpp, spfOrder, spfPlan, spfFact};

		Id sbrId = sbr.Id;

		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-01-01'), sbr.Period__c);

		sbr.PeriodQuarter__c = '2';
		update sbr;

		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-04-01'), sbr.Period__c);

		sbr.PeriodQuarter__c = '3';
		update sbr;

		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-07-01'), sbr.Period__c);

		sbr.PeriodQuarter__c = '4';
		update sbr;

		sbr = [Select Id, Period__c from SalesBudgetRecord__c where Id = :sbrId];
		System.assertEquals(Date.valueOf(year + '-10-01'), sbr.Period__c);
	}
}