force-app/main/default/objects/FamiliesTypes__c/FamiliesTypes__c.object-meta.xml
<CustomObject>
    <label>Family Type</label>
    <nameField>
        <label>Family Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/FamilyType__c.field-meta.xml
<CustomField>
    <fullName>FamilyType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Type</label>
    <referenceTo>FamiliesTypes__c</referenceTo>
    <relationshipLabel>Families</relationshipLabel>
    <relationshipName>Families</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Group3__c/Group3__c.object-meta.xml
<CustomObject>
    <label>Group3</label>
    <nameField>
        <label>Group 3</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group3</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Group3__c/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <externalId>true</externalId>
    <label>ID in ERP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/QuoteRequestDetail__c.object-meta.xml
<CustomObject>
    <label>Quota Request Detail</label>
    <nameField>
        <label>Family ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteRequestDetail__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AddQty (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/FamilyType__c.field-meta.xml
<CustomField>
    <fullName>FamilyType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Type</label>
    <referenceTo>FamiliesTypes__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Group3__c.field-meta.xml
<CustomField>
    <fullName>Group3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group3</label>
    <referenceTo>Group3__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/QuoteRequestHeader__c.field-meta.xml
<CustomField>
    <fullName>QuoteRequestHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Request Header</label>
    <referenceTo>QuoteRequestHeader__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/QuoteStructureDetail__c.field-meta.xml
<CustomField>
    <fullName>QuoteStructureDetail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Structure Detail</label>
    <referenceTo>QuoteStructureDetail__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestDetail__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipName>Quote_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteRequestHeader__c/QuoteRequestHeader__c.object-meta.xml
<CustomObject>
    <label>Quota Request Header</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotas Request Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteRequestHeader__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <label>Add Qty (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteRequestHeader__c/fields/Quote_t__c.field-meta.xml
<CustomField>
    <fullName>Quote_t__c</fullName>
    <label>Quote (t)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteSegmentStruct__c/QuoteSegmentStruct__c.object-meta.xml
<CustomObject>
    <description>Quotes Segment Structure (by Managers, Groups, Regions)</description>
    <label>Quote Segment Structure</label>
    <nameField>
        <displayFormat>QSS-{00000000}</displayFormat>
        <label>QuoteSegmStruct</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes Segment Structure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSegmentStruct__c/fields/Group3Struct__c.field-meta.xml
<CustomField>
    <fullName>Group3Struct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Group 3 Structure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteSegmentStruct__c/fields/ManagerStruct__c.field-meta.xml
<CustomField>
    <fullName>ManagerStruct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manager Structure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteSegmentStruct__c/fields/RegionStruct__c.field-meta.xml
<CustomField>
    <fullName>RegionStruct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Region Structure</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/QuoteStructureDetail__c.object-meta.xml
<CustomObject>
    <label>Quote Structure Detail</label>
    <nameField>
        <label>Route Family</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Structure Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteStructureDetail__c/fields/AddQty_t__c.field-meta.xml
<CustomField>
    <fullName>AddQty_t__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AddQty (t)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family</label>
    <referenceTo>Family__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/FamilyType__c.field-meta.xml
<CustomField>
    <fullName>FamilyType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Family Type</label>
    <referenceTo>FamiliesTypes__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Group3__c.field-meta.xml
<CustomField>
    <fullName>Group3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Group3</label>
    <referenceTo>Group3__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteStructureDetail__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Quote Structure Detail</relationshipLabel>
    <relationshipName>Quote_Structure_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>New object for Regions from IT ERP</description>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotaApprovalProcessController.cls
public without sharing class QuotaApprovalProcessController {

    private final static Map<String, String> MarkenSegmentMap = new Map<String, String> {
        '00002' => 'MENA',
        '00001' => 'Americas',
        '00004' => 'Europe',
        '00010' => 'CIS',
        '00011' => 'Ukraine',
        '00006' => 'KLW',
        '00100' => 'Steel',
        '00016' => 'Customs Union',
        '00005' => 'IPS',
        '00020' => 'ETA',
        '00021' => 'Machinery',
        '00008' => 'Передел',
        '00007' => 'Оседание',
        '00012' => 'Сплавы',
        '00013' => 'NMD'
    };

    @AuraEnabled
    public static List<QuoteRequestDetailWrapper> getQuotaDetails(String urlString) {
        List<QuoteRequestDetailWrapper> QuoteRequestDetailWrapperList = new List<QuoteRequestDetailWrapper>();
        String paramsString = urlString.substringAfter('&');

        if(String.isBlank(paramsString)) {
            return QuoteRequestDetailWrapperList;
        }

        String decryptedParamsString = CryptoUtils.getCryptoDecodedURLString(paramsString);
        String headerId = decryptedParamsString.split('&').get(0).split('=').get(1);

        List<QuoteRequestDetail__c> quoteStructDetailList = [SELECT Id, FamilyType__r.Name, Family__r.ID_ERP__c, Family__r.Name, 
                                                                    MarketSegment__c, Manager__r.Name, Group3__r.Name, Region__r.Name, 
                                                                    Percent__c, Quote_t__c, AddQty_t__c, QuoteStructureDetail__r.Percent__c,
                                                                    QuoteStructureDetail__r.Quote_t__c, QuoteStructureDetail__r.AddQty_t__c,
                                                                    QuoteRequestHeader__r.DateFrom__c, QuoteRequestHeader__r.DateTo__c,
                                                                    QuoteRequestHeader__r.Name, QuoteRequestHeader__r.CreatedDate, 
                                                                    QuoteRequestHeader__r.CreatedBy.Name
                                                             FROM QuoteRequestDetail__c 
                                                             WHERE QuoteRequestHeader__c = :headerId
                                                             ORDER BY FamilyType__r.Name ASC
        ];

        for (QuoteRequestDetail__c quoteStructDetail : quoteStructDetailList) {            
            QuoteRequestDetailWrapper QuoteRequestDetailWrapper = new QuoteRequestDetailWrapper(quoteStructDetail);
            QuoteRequestDetailWrapperList.add(QuoteRequestDetailWrapper);
        }

        return QuoteRequestDetailWrapperList;
    }

    @AuraEnabled(cacheable=true)
    public static List<QuoteSegmentStruct__c> getQuoteSegmentStruct(String marketSegment) {
        List<QuoteSegmentStruct__c> quoteStructDetailList = [SELECT Id, ManagerStruct__c, Group3Struct__c, RegionStruct__c
                                                             FROM QuoteSegmentStruct__c 
                                                             WHERE MarketSegment__c = :marketSegment 
                                                             AND Is_Active__c = true];

        return quoteStructDetailList;
    }

    @AuraEnabled
    public static Boolean isApprovalRequestPending(String urlString) {
        String paramsString = urlString.substringAfter('&');

        String decryptedParamsString = CryptoUtils.getCryptoDecodedURLString(paramsString);
        String headerId = decryptedParamsString.split('&').get(0).split('=').get(1);

        List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :headerId LIMIT 1];
        
        if(workItems.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    @AuraEnabled
    public static String approveOrRejectRequest(String urlString, Boolean isApproved) {
        List<QuoteRequestDetailWrapper> QuoteRequestDetailWrapperList = new List<QuoteRequestDetailWrapper>();
        String paramsString = urlString.substringAfter('&');

        String decryptedParamsString = CryptoUtils.getCryptoDecodedURLString(paramsString);
        String headerId = decryptedParamsString.split('&').get(0).split('=').get(1);
        String userId = decryptedParamsString.split('&').get(1).split('=').get(1);

        User user = [SELECT Id, Name FROM User WHERE Id = :userId LIMIT 1];
        List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstance.TargetObjectId = :headerId LIMIT 1];
        ProcessInstanceWorkitem workItem = workItems.get(0);

        List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setWorkitemId(workItem.Id);
        if(isApproved) {
            req.setAction('Approve');
            req.setComments('Approved by ' + user.Name);
        } else {
            req.setAction('Reject');
            req.setComments('Rejected by ' + user.Name);
        }

        requests.add(req);
        Approval.ProcessResult[] processResults = Approval.process(requests);

        return 'Запит на коригування успішно ' + (isApproved ? 'узгоджено' : 'відхилено');
    }

    public class QuoteRequestDetailWrapper {
        @AuraEnabled public Id quoteStructDetailId {get; set;}
        @AuraEnabled public String familyType {get; set;}
        @AuraEnabled public String familyId {get; set;}
        @AuraEnabled public String family {get; set;}
        @AuraEnabled public String marketSegment {get; set;}
        @AuraEnabled public String marketSegmentName {get; set;}
        @AuraEnabled public String manager {get; set;}
        @AuraEnabled public String group3 {get; set;}
        @AuraEnabled public String region {get; set;}
        @AuraEnabled public Decimal percent {get; set;}
        @AuraEnabled public Decimal quoteT {get; set;}
        @AuraEnabled public Decimal addQty {get; set;}
        @AuraEnabled public Decimal percentOld {get; set;}
        @AuraEnabled public Decimal quoteTOld {get; set;}
        @AuraEnabled public Decimal addQtyOld {get; set;}
        @AuraEnabled public Date dateFrom {get; set;}
        @AuraEnabled public Date dateTo {get; set;}
        @AuraEnabled public String requestNumber {get; set;}
        @AuraEnabled public Datetime createdDate {get; set;}
        @AuraEnabled public String createdBy {get; set;}
        @AuraEnabled public Boolean isPercentEquals {get; set;}
        @AuraEnabled public Boolean isQuoteTEquals {get; set;}
        @AuraEnabled public Boolean isAddQtyEquals {get; set;}

        public QuoteRequestDetailWrapper(QuoteRequestDetail__c quoteStructDetail) {

            this.quoteStructDetailId = quoteStructDetail.Id;
            this.familyType = quoteStructDetail.FamilyType__r.Name;
            this.familyId = String.valueOf(quoteStructDetail.Family__r.ID_ERP__c);
            this.family = quoteStructDetail.Family__r.Name;
            this.marketSegment = quoteStructDetail.MarketSegment__c;
            this.marketSegmentName = MarkenSegmentMap.get(marketSegment);
            this.manager = quoteStructDetail.Manager__r.Name;
            this.group3 = quoteStructDetail.Group3__r.Name;
            this.region = quoteStructDetail.Region__r.Name;
            this.percent = quoteStructDetail.Percent__c;
            this.quoteT = quoteStructDetail.Quote_t__c;
            this.addQty = quoteStructDetail.AddQty_t__c != null ? quoteStructDetail.AddQty_t__c : 0;
            this.percentOld = quoteStructDetail.QuoteStructureDetail__r.Percent__c;
            this.quoteTOld = quoteStructDetail.QuoteStructureDetail__r.Quote_t__c;
            this.addQtyOld = quoteStructDetail.QuoteStructureDetail__r.AddQty_t__c != null ? quoteStructDetail.QuoteStructureDetail__r.AddQty_t__c : 0;
            this.dateFrom = quoteStructDetail.QuoteRequestHeader__r.DateFrom__c;
            this.dateTo = quoteStructDetail.QuoteRequestHeader__r.DateTo__c;
            this.requestNumber = quoteStructDetail.QuoteRequestHeader__r.Name;
            this.createdDate = quoteStructDetail.QuoteRequestHeader__r.CreatedDate;
            this.createdBy = quoteStructDetail.QuoteRequestHeader__r.CreatedBy.Name;
            this.isPercentEquals = quoteStructDetail.Percent__c?.setScale(2) == quoteStructDetail.QuoteStructureDetail__r.Percent__c?.setScale(2);
            this.isQuoteTEquals = quoteStructDetail.Quote_t__c?.setScale(2) == quoteStructDetail.QuoteStructureDetail__r.Quote_t__c?.setScale(2);
            this.isAddQtyEquals = quoteStructDetail.AddQty_t__c?.setScale(2) == quoteStructDetail.QuoteStructureDetail__r.AddQty_t__c?.setScale(2) || 
                                  (quoteStructDetail.AddQty_t__c == null && quoteStructDetail.QuoteStructureDetail__r.AddQty_t__c == 0) || 
                                  (quoteStructDetail.AddQty_t__c == 0 && quoteStructDetail.QuoteStructureDetail__r.AddQty_t__c == null);
        }
    }

    public static void FakeCoverageMethod() {
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}