force-app/main/default/objects/Contact/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related user in the ERP system (used for integration purposes)</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related user in the ERP system (used for integration purposes)</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Credentials__c/Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Credentials</label>
</CustomObject>

force-app/main/default/objects/Credentials__c/fields/User_Login__c.field-meta.xml
<CustomField>
    <fullName>User_Login__c</fullName>
    <label>User Login</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/User_Password__c.field-meta.xml
<CustomField>
    <fullName>User_Password__c</fullName>
    <label>User Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/InvoiceOrderDebt__c.object-meta.xml
<CustomObject>
    <label>Invoice Order Debt</label>
    <nameField>
        <label>Invoice</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Order Debts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Order Debts</relationshipLabel>
    <relationshipName>Invoice_Order_Debts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/DaysOverdue__c.field-meta.xml
<CustomField>
    <fullName>DaysOverdue__c</fullName>
    <description>Днів протермінування</description>
    <label>Days overdue</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>Дата настання зобов&apos;язень</description>
    <label>Due date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/InternalAccount__c.field-meta.xml
<CustomField>
    <fullName>InternalAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Внітрішні аккаунти Інтерпайп в Сейлсфорс</description>
    <label>Internal Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice Order Debts (Internal Account)</relationshipLabel>
    <relationshipName>Invoice_Order_Debts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <description>Сума в валюті документу</description>
    <label>Net amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Invoice Order Debts</relationshipLabel>
    <relationshipName>Invoice_Order_Debts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/OutstandingDebt__c.field-meta.xml
<CustomField>
    <fullName>OutstandingDebt__c</fullName>
    <description>Залишок у валюті дкументу</description>
    <label>Debt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceOrderDebt__c/fields/VATAmount__c.field-meta.xml
<CustomField>
    <fullName>VATAmount__c</fullName>
    <description>Сума ПДВ у валюті документу</description>
    <label>VAT amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/AdditionalNumber__c.field-meta.xml
<CustomField>
    <fullName>AdditionalNumber__c</fullName>
    <externalId>true</externalId>
    <label>Additional Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/MarketSegment__c.field-meta.xml
<CustomField>
    <fullName>MarketSegment__c</fullName>
    <label>Market Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prod_Type__c.field-meta.xml
<CustomField>
    <fullName>Prod_Type__c</fullName>
    <formula>IF(ISPICKVAL(MarketSegment__c, &apos;00006&apos;), &apos;WHEELS&apos;, &apos;TUBES&apos; )</formula>
    <label>Prod. Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/ID_ERP__c.field-meta.xml
<CustomField>
    <fullName>ID_ERP__c</fullName>
    <description>ID code of the related record in the ERP system.</description>
    <externalId>true</externalId>
    <inlineHelpText>ID code of the related record in the ERP system.</inlineHelpText>
    <label>ID in ERP</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/MarketSegments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00001</fullName>
        <label>Americas</label>
    </customValue>
    <customValue>
        <fullName>00002</fullName>
        <label>MENA</label>
    </customValue>
    <customValue>
        <fullName>00004</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>00010</fullName>
        <label>CIS</label>
    </customValue>
    <customValue>
        <fullName>00011</fullName>
        <label>Ukraine</label>
    </customValue>
    <customValue>
        <fullName>00006</fullName>
        <label>KLW</label>
    </customValue>
    <customValue>
        <fullName>00016</fullName>
        <label>Customs Union</label>
    </customValue>
    <customValue>
        <fullName>00019</fullName>
        <label>Vallourec</label>
    </customValue>
    <customValue>
        <fullName>00005</fullName>
        <label>IPS</label>
    </customValue>
    <customValue>
        <fullName>00020</fullName>
        <label>ETA</label>
    </customValue>
    <customValue>
        <fullName>00021</fullName>
        <label>Machinery</label>
    </customValue>
    <customValue>
        <fullName>00100</fullName>
        <label>Steel</label>
    </customValue>
    <customValue>
        <fullName>00008</fullName>
        <label>Передел</label>
    </customValue>
    <customValue>
        <fullName>00007</fullName>
        <label>Оседание</label>
    </customValue>
    <customValue>
        <fullName>00012</fullName>
        <label>Сплавы</label>
    </customValue>
    <customValue>
        <fullName>00013</fullName>
        <label>NMD</label>
    </customValue>
    <customValue>
        <fullName>00014</fullName>
        <label>Сторонние организации</label>
    </customValue>
    <customValue>
        <fullName>00017</fullName>
        <label>Опытные/Освоение</label>
    </customValue>
    <customValue>
        <fullName>00018</fullName>
        <label>Изоляция</label>
    </customValue>
    <customValue>
        <fullName>00022</fullName>
        <label>ФЭС прочее</label>
    </customValue>
    <description>Market segments defined by our company</description>
    <masterLabel>Market Segments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SiteInvoiceController.cls
public without sharing class SiteInvoiceController {
    @AuraEnabled(cacheable=true)
    public static List<InvoiceOrderDebt__c> getInvoices(){
        try {
            String userId = UserInfo.getUserId();
            String idContactUser = [SELECT Contactid FROM User WHERE Id=:userId LIMIT 1].contactid;
            String accId = [SELECT id, AccountId FROM Contact WHERE id =:idContactUser LIMIT 1].AccountId;
            List<Account> childAccounts = [SELECT Id FROM Account WHERE ParentId = :accId];
            Set<Id> accountIdSet = new Set<Id>{accId};

            if(!childAccounts.isEmpty()) {
                for(Account childAccount : childAccounts) {
                    accountIdSet.add(childAccount.Id);
                }
            }

            return [SELECT id, Account__r.MarketSegment__c,Account__r.ID_ERP__c,InternalAccount__r.ID_ERP__c, Order__r.AdditionalNumber__c, Name,InvoiceDate__c, DueDate__c,
                    DaysOverdue__c,CurrencyIsoCode,NetAmount__c,VATAmount__c,OutstandingDebt__c, Contract__c, Order__r.Prod_Type__c
                    FROM InvoiceOrderDebt__c WHERE Account__c IN :accountIdSet ORDER BY DaysOverdue__c desc];
                    
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    @AuraEnabled(cacheable=true)
    public static String getAccountMarketSegment(){
        try {
            String userId = UserInfo.getUserId();
            String idContactUser = [SELECT Contactid FROM User WHERE Id=:userId LIMIT 1].contactid;
            
            return [SELECT id, Account.MarketSegment__c FROM Contact WHERE id =:idContactUser LIMIT 1].Account.MarketSegment__c;
                    
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, Object> requestForInvoicePDF (String org, String orgK, String ndmInvoice) {
        List<Object> response = new List<Object>();

        // Attempt to parse the org and orgK strings to integers
        Integer orgInt;
        Integer orgKInt;
        try {
            orgInt = Integer.valueOf(org);
            orgKInt = Integer.valueOf(orgK);
        } catch (System.TypeException e) {
            System.debug('Error parsing org or orgK to Integer: ' + e.getMessage());
        }

        Map<String, Object> dataMap = new Map<String, Object>{
            'ORG' => orgInt,
            'ORG_K' => orgKInt,
            'NDM_INVOCE' => ndmInvoice
        };
        String reqText = JSON.serialize(dataMap);

        System.debug(reqText);

        String res = makeCalloutDetailPDF(reqText);
        // String res = '{"ORG":13585,"ORG_NAME":"Artigiantubi Srl.","ORG_K":17642,"ORG_K_NAME":"INTERPIPE EUROPE SA","NDM_INVOCE":"PSI24/03800","DDM":"/Date(1709337600514)/","CONTENTS":"JVc"}';
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(res);
        System.debug('responseMap' + responseMap);

        return responseMap;
    }



    public static String makeCalloutDetailPDF(string jsonString){
       
        SFToERP.WebServiceSoap ERPhandler = new SFToERP.WebServiceSoap();
        String login = Credentials__c.getOrgDefaults().User_Login__c;
        String password = Credentials__c.getOrgDefaults().User_Password__c;
        String response = ERPhandler.LoginEx(login, password);
        ERPRequestParser.LoginResponse requestObject = (ERPRequestParser.LoginResponse) System.JSON.deserialize(response, ERPRequestParser.LoginResponse.class);
     
        String calc = '_SF_GET_PDF_INVOICE';
        String ticket = requestObject.Ticket;
        String arg = jsonString;
        ERPRequestParser.ExecuteResponceCertificate idResponse = null;
        try{
            String erpResult = ERPhandler.ExecuteEx(calc, arg, ticket);
            system.debug(arg);
            system.debug(arg.remove('\\'));
            system.debug(json.serializePretty(arg));
            
            String processed = erpResult.remove('\\');
            System.debug(processed);                              
            return processed;
        } catch(CalloutException callfail) {
            String errorMessage = callfail.getMessage() + '\n' + callfail.getStackTraceString();       
            system.debug(errorMessage); 
            //sendEmail('Call invalid for json order');
            AuraHandledException e = new AuraHandledException('Call invalid for json Inv PDF');
        e.setMessage('Call invalid for json Inv PDF');
        system.debug(e);
        throw e;
        } catch(System.JSONException jsfailed) {
            String errorMessage = jsfailed.getMessage() + '\n' + jsfailed.getStackTraceString();
            system.debug(errorMessage);
            throw new AuraHandledException(Label.InvalidJSONReceived);
        } 
    }

    public static void FakeCoverageMethod() {
        Integer i=0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}