force-app/main/default/objects/RouteQuotesH__c/RouteQuotesH__c.object-meta.xml
<CustomObject>
    <label>Route Quotas Hierarchy</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Quotas Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RouteQuotesH__c/fields/DateEnd__c.field-meta.xml
<CustomField>
    <fullName>DateEnd__c</fullName>
    <label>DateEnd</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>RouteQuotesH__c</referenceTo>
    <relationshipName>Route_Quotes_Hierarchy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RouteQuotesH__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Parent Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RouteQuotesHierarchyVisibilityTest.cls
@IsTest
public class RouteQuotesHierarchyVisibilityTest {

    @TestSetup
    static void setup() {
        RouteQuotesH__c allRoutesQuotesParent = new RouteQuotesH__c(Name = 'ALL ROUTES QUOTES', Level__c = 0);
        insert allRoutesQuotesParent;

        List<RouteQuotesH__c> routeQuotesHList = new List<RouteQuotesH__c>();

        routeQuotesHList.add(new RouteQuotesH__c(
            DateBegin__c = Date.today().toStartOfMonth().addMonths(-1),
            DateEnd__c = Date.today().toStartOfMonth().addDays(-1),
            Parent__c = allRoutesQuotesParent.Id,
            Level__c = 1
        ));

        routeQuotesHList.add(new RouteQuotesH__c(
            DateBegin__c = Date.today().toStartOfMonth(),
            DateEnd__c = Date.today().toStartOfMonth().addMonths(1).addDays(-1),
            Parent__c = allRoutesQuotesParent.Id,
            Level__c = 1
        ));

        routeQuotesHList.add(new RouteQuotesH__c(
            DateBegin__c = Date.today().toStartOfMonth().addMonths(4),
            DateEnd__c = Date.today().toStartOfMonth().addMonths(5).addDays(-1),
            ParentId__c = allRoutesQuotesParent.Id,
            Level__c = 1
        ));

        insert routeQuotesHList;
    }

    @IsTest
    static void testCheckHierarchyVisibility() {

        Test.startTest();
        RouteQuotesHierarchyVisibilitySched scheduler = new RouteQuotesHierarchyVisibilitySched();
        scheduler.execute(null);
        Test.stopTest();

        RouteQuotesH__c prevRouteQuotesH = [SELECT Id, Parent__c, ParentId__c FROM RouteQuotesH__c WHERE DateBegin__c = :Date.today().toStartOfMonth().addMonths(-1)];
        RouteQuotesH__c currentRouteQuotesH = [SELECT Id, Parent__c, ParentId__c FROM RouteQuotesH__c WHERE DateBegin__c = :Date.today().toStartOfMonth()];
        RouteQuotesH__c nextRouteQuotesH = [SELECT Id, Parent__c, ParentId__c FROM RouteQuotesH__c WHERE DateBegin__c = :Date.today().toStartOfMonth().addMonths(4)];

        System.assert(prevRouteQuotesH.Parent__c == null);
        System.assert(prevRouteQuotesH.ParentId__c != null);
        System.assert(currentRouteQuotesH.Parent__c != null);
        System.assert(currentRouteQuotesH.ParentId__c == null);
        System.assert(nextRouteQuotesH.Parent__c != null);
        System.assert(nextRouteQuotesH.ParentId__c == null);
    }

}