force-app/main/default/objects/Production_Quota__c/Production_Quota__c.object-meta.xml
<CustomObject>
    <label>Production Quota</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Production Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Quota__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Production_Amount_t__c.field-meta.xml
<CustomField>
    <fullName>Production_Amount_t__c</fullName>
    <label>Production Amount (t)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Quota_Type__c.field-meta.xml
<CustomField>
    <fullName>Quota_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Production Quotas</relationshipLabel>
    <relationshipName>Production_Quotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotaType__c/QuotaType__c.object-meta.xml
<CustomObject>
    <description>Type of quota that is defined by production shop for particular sales manager</description>
    <label>Quota Type</label>
    <nameField>
        <label>Quota Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotas Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotaType__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Production shop that the quota relates to</description>
    <inlineHelpText>Production shop that the quota relates to</inlineHelpText>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipLabel>Quotas Types</relationshipLabel>
    <relationshipName>QuotasTypes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/SalesBudgetRecord__c.object-meta.xml
<CustomObject>
    <label>Sales Budget Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Budget Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudgetRecord__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>SalesBudget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/Production_Amount__c.field-meta.xml
<CustomField>
    <fullName>Production_Amount__c</fullName>
    <label>Production Amount (t)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/QuotaType__c.field-meta.xml
<CustomField>
    <fullName>QuotaType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Type</label>
    <referenceTo>QuotaType__c</referenceTo>
    <relationshipName>SalesBudget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesManager__c.field-meta.xml
<CustomField>
    <fullName>SalesManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesBudget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/fields/Shop__c.field-meta.xml
<CustomField>
    <fullName>Shop__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shop</label>
    <referenceTo>Shop__c</referenceTo>
    <relationshipName>SalesBudget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shop__c/Shop__c.object-meta.xml
<CustomObject>
    <description>Our production shop</description>
    <label>Shop</label>
    <nameField>
        <label>Shop Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shops</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductionQuoteFromSalBudgetBatch.cls
global class ProductionQuoteFromSalBudgetBatch implements Database.Batchable<SObject> {
	       
    global Database.QueryLocator start(Database.BatchableContext context) {		              
        return Database.getQueryLocator('SELECT id, QuotaType__c,MarketSegment__c,Period__c,Production_Amount__c,SalesManager__c,Product__c,Shop__c FROM SalesBudgetRecord__c WHERE Period__c>2022-03-01 and Period__c<2022-07-01 and CreatedDate>2021-12-30T21:21:55.000+0000' );
	}
    
    global void execute(Database.BatchableContext context, List<SalesBudgetRecord__c> scope) {
        List<Production_Quota__c> productionQuotaToInsert = new List<Production_Quota__c>();
        
        for(SalesBudgetRecord__c sbr:scope){
            String sbrQuotaType = sbr.QuotaType__c;
            String sbrMarketSegment = sbr.MarketSegment__c;
            Date sbrPeriod = sbr.Period__c;
            Decimal sbrProductionAmount = sbr.Production_Amount__c;
            String sbrSaleManager = sbr.SalesManager__c;
            String sbrProduct = sbr.Product__c;
            
            
            Production_Quota__c pq = new Production_Quota__c();
            pq.Quota_Type__c = sbrQuotaType;
            pq.Market_Segment__c = sbrMarketSegment;
            pq.Period__c = sbrPeriod;
            pq.Production_Amount_t__c = sbrProductionAmount;
            pq.Sales_Manager__c = sbrSaleManager;
            pq.Product__c = sbrProduct; 
            pq.Shop__c = sbr.Shop__c;
            productionQuotaToInsert.add(pq);
        }
       // SalesBudgetRecord__c sbr = scope[0];     
        insert productionQuotaToInsert;
	}
    
    global void finish(Database.BatchableContext context) {
        system.debug('ProductionQuoteFromSalBudgetBatch finish');
		
	}
}