force-app/main/default/objects/Production_Quota__c/Production_Quota__c.object-meta.xml
<CustomObject>
    <label>Production Quota</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Production Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Production_Quota__c/fields/Production_Amount_t__c.field-meta.xml
<CustomField>
    <fullName>Production_Amount_t__c</fullName>
    <label>Production Amount (t)</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/fields/Quota_Mt__c.field-meta.xml
<CustomField>
    <fullName>Quota_Mt__c</fullName>
    <label>Quota Mt</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CopyProductionAmountinQuotasTest.cls
@isTest
private with sharing class CopyProductionAmountinQuotasTest {
 
static testmethod void test() {
 
    List<Production_Quota__c> pqList = new List<Production_Quota__c>();
    for (Integer i=0;i<200;i++) {
    Production_Quota__c pq = new Production_Quota__c(Production_Amount_t__c = 1 + i);
    pqList.add(pq);
    }
    insert pqList;
    
    Test.startTest();
    CopyProductionAmountinQuotas c = new CopyProductionAmountinQuotas();
    Database.executeBatch(c);
    Test.stopTest();

    List<Production_Quota__c> pqUpdList= [SELECT Id,Production_Amount_t__c,Quota_Mt__c FROM Production_Quota__c];
    System.assert(pqUpdList[0].Quota_Mt__c != null);
}
}