force-app/main/default/objects/SalesPlanFact__c/SalesPlanFact__c.object-meta.xml
<CustomObject>
    <label>Sales Plan and Fact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plan and Fact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanFact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Budget</fullName>
                <color>#FFCC33</color>
                <label>Initial Budget</label>
            </value>
            <value>
                <fullName>Corrected Budget</fullName>
                <color>#DDDDDD</color>
                <label>Corrected Budget</label>
            </value>
            <value>
                <fullName>Actual Budget</fullName>
                <color>#78C953</color>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Plan</fullName>
                <color>#AFCADF</color>
                <label>Plan</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <color>#2F5D85</color>
                <label>Open Orders</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <color>#419249</color>
                <label>Open Orders &amp; Opps</label>
            </value>
            <value>
                <fullName>Fact</fullName>
                <color>#2F5D85</color>
                <label>Fact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/ActualBudget.recordType-meta.xml
<RecordType>
    <fullName>ActualBudget</fullName>
    <active>true</active>
    <label>Actual Budget</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/CorrectedBudget.recordType-meta.xml
<RecordType>
    <fullName>CorrectedBudget</fullName>
    <active>true</active>
    <label>Corrected Budget</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Fact.recordType-meta.xml
<RecordType>
    <fullName>Fact</fullName>
    <active>true</active>
    <description>Actual production and sales data</description>
    <label>Fact</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/InitialBudget.recordType-meta.xml
<RecordType>
    <fullName>InitialBudget</fullName>
    <active>true</active>
    <label>Initial Budget</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Opportunity</fullName>
    <active>true</active>
    <label>Opportunity</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <description>Open order</description>
    <label>Order</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Plan.recordType-meta.xml
<RecordType>
    <fullName>Plan</fullName>
    <active>true</active>
    <description>Production and sales plan data</description>
    <label>Plan</label>
</RecordType>

force-app/main/default/classes/SalesPlanFactTriggerHandler.cls
public class SalesPlanFactTriggerHandler extends TriggerHandler implements ITrigger {
		
	Map<Id, RecordType> rtMap;
	
	
	public SalesPlanFactTriggerHandler(Map<Id, SObject> oldMap, Map<Id, SObject> newMap, List<SObject> oldList, List<SObject> newList) {
		super(oldMap, newMap, oldList, newList);
	}

	
	
	public void bulkBefore() {
		System.debug('bulkBefore SalesPlanFact');

		if (Trigger.isInsert || Trigger.isUpdate) {
			// Сформируем список соответствий рекорд тайпов объекта SalesPlanFact__c
			rtMap = new Map<Id, RecordType>([select Id, Name, DeveloperName FROM RecordType WHERE SobjectType = 'SalesPlanFact__c']);
		}
	}

	
	
	public void beforeInsert(SObject so) {
		//System.debug('beforeInsert SalesPlanFact');
		
		setType((SalesPlanFact__c) so);
	}
	
	public void beforeUpdate(SObject oldSo, SObject so) {
		//System.debug('beforeUpdate SalesPlanFact');
		
		setType((SalesPlanFact__c) so);
	}
		
	public void beforeDelete(SObject so) {
		//System.debug('beforeDelete SalesPlanFact');
	}


	
	public void bulkAfter() {
		//System.debug('bulkAfter SalesPlanFact');
	}

	
			
	public void afterInsert(SObject so) {
		//System.debug('afterInsert SalesPlanFact');
	}
		
	public void afterUpdate(SObject oldSo, SObject so) {
		//System.debug('afterUpdate SalesPlanFact');
	}
	
	public void afterDelete(SObject so) {
		//System.debug('afterDelete SalesPlanFact');
	}

	
	
	public void postProcessing() {
		//System.debug('postProcessing SalesPlanFact');
	}

	
	// Пиклист Type__с дублирует значения Record Type, для того чтоб в отчетах данные выводились именно в том порядке, как в пиклисте
	public void setType(SalesPlanFact__c spf) {
		String rtDevName = rtMap.get(spf.RecordTypeId).DeveloperName;

		switch on rtDevName {
			when 'InitialBudget' {
				spf.Type__c = 'Initial Budget';
			}
			when 'CorrectedBudget' {
				spf.Type__c = 'Corrected Budget';
			}
			when 'ActualBudget' {
				spf.Type__c = 'Actual Budget';
			}
			when 'Opportunity' {
				spf.Type__c = 'Opportunity';
			}
			when 'Order' {
				spf.Type__c = 'Order';
			}
			when 'Plan' {
				spf.Type__c = 'Plan';
			}
			when 'Fact' {
				spf.Type__c = 'Fact';
			}
		}
	}
}