force-app/main/default/objects/Deleted_Period__c/Deleted_Period__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deleted Periods</label>
</CustomObject>

force-app/main/default/objects/Deleted_Period__c/fields/Deleted__c.field-meta.xml
<CustomField>
    <fullName>Deleted__c</fullName>
    <label>Deleted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/Production_Quota__c.object-meta.xml
<CustomObject>
    <label>Production Quota</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Production Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/SalesBudget__c.object-meta.xml
<CustomObject>
    <label>Sales Budget</label>
    <nameField>
        <label>Sales Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <formula>Case(Type__c,
					&apos;Y&apos;, Text(Year__c) + &apos;: Year Initial&apos;,
					&apos;HY1&apos;, Text(Year__c) + &apos;: First Half Year&apos;,
					&apos;HY2&apos;, Text(Year__c) + &apos;: Second Half Year&apos;,
					&apos;Q1&apos;, Text(Year__c) + &apos;: Q1 Corrected&apos;,
					&apos;Q2&apos;, Text(Year__c) + &apos;: Q2 Corrected&apos;,
					&apos;Q3&apos;, Text(Year__c) + &apos;: Q3 Corrected&apos;,
					&apos;Q4&apos;, Text(Year__c) + &apos;: Q4 Corrected&apos;,
					null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/SalesBudgetRecord__c.object-meta.xml
<CustomObject>
    <label>Sales Budget Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Budget Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesBudget__c.field-meta.xml
<CustomField>
    <fullName>SalesBudget__c</fullName>
    <label>Sales Budget</label>
    <referenceTo>SalesBudget__c</referenceTo>
    <relationshipLabel>Sales Budget Records</relationshipLabel>
    <relationshipName>Sales_Budget_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/ProductionQuoteDeleteBatch.cls
global class ProductionQuoteDeleteBatch implements Database.Batchable<SObject>  {
	
    global Set<Id> sbrIdsSet = new Set<Id>();
    global List<Date> listDateCheck = new List<Date>();
   
    
    global ProductionQuoteDeleteBatch(Set<Id> idsSalesBudgetRecords){
        sbrIdsSet = idsSalesBudgetRecords;
        system.debug('start delete production quote records');
        
        List<Deleted_Period__c> dlper = new List<Deleted_Period__c>();
        //AggregateResult[] groupedResults= [SELECT Period__c  FROM SalesBudgetRecord__c where id in :idsSalesBudgetRecords group by Period__c ];
        AggregateResult[] groupedResults= [SELECT Period__c  FROM SalesBudgetRecord__c where SalesBudget__c in :idsSalesBudgetRecords group by Period__c ];
        
        Map<String,Deleted_Period__c> records = Deleted_Period__c.getAll();
        
        for(AggregateResult ar:groupedResults){
    
        if(records.get(String.valueOf(ar.get('Period__c')))==null){
                listDateCheck.add(Date.valueOf(ar.get('Period__c')));
                system.debug(ar.get('Period__c'));
                Deleted_Period__c newRecord = new Deleted_Period__c();
                newRecord.Name = String.valueOf(ar.get('Period__c'));
                newRecord.Deleted__c = Date.valueOf(ar.get('Period__c'));
                dlper.add(newRecord);
            }       
        }
        if(dlper.size()>0){
            insert dlper;
        }
        //SalesPlanFactDeleteBatch deleteSalesPlanFactBatch = new SalesPlanFactDeleteBatch(idsSalesBudgetRecords);
        //Id deleteSalesPlanFactBatchId = Database.executeBatch(deleteSalesPlanFactBatch);
    }
    
    global Database.QueryLocator start(Database.BatchableContext context) {	
        return Database.getQueryLocator('SELECT id FROM Production_Quota__c WHERE Period__c in :listDateCheck' );
	}
    
    global void execute(Database.BatchableContext context, List<Production_Quota__c> scope) {
        
        delete scope;
	}
    
    global void finish(Database.BatchableContext context) {
        system.debug('finish delete production quote records');
        ProductionQuoteCreateBatch createBatchProdQuote = new ProductionQuoteCreateBatch(sbrIdsSet);
		//Id createBatchProdQuoteId = Database.executeBatch(createBatchProdQuote);
        System.scheduleBatch( createBatchProdQuote, 'createBatchProdQuote', 2);
	}
}