force-app/main/default/objects/Deleted_Period__c/Deleted_Period__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deleted Periods</label>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/SalesBudget__c.object-meta.xml
<CustomObject>
    <label>Sales Budget</label>
    <nameField>
        <label>Sales Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudget__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <formula>Case(Type__c,
					&apos;Y&apos;, Text(Year__c) + &apos;: Year Initial&apos;,
					&apos;HY1&apos;, Text(Year__c) + &apos;: First Half Year&apos;,
					&apos;HY2&apos;, Text(Year__c) + &apos;: Second Half Year&apos;,
					&apos;Q1&apos;, Text(Year__c) + &apos;: Q1 Corrected&apos;,
					&apos;Q2&apos;, Text(Year__c) + &apos;: Q2 Corrected&apos;,
					&apos;Q3&apos;, Text(Year__c) + &apos;: Q3 Corrected&apos;,
					&apos;Q4&apos;, Text(Year__c) + &apos;: Q4 Corrected&apos;,
					null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/PeriodBeginning__c.field-meta.xml
<CustomField>
    <fullName>PeriodBeginning__c</fullName>
    <formula>CASE(Type__c, 
					&apos;Y&apos;, Date(Year__c, 01, 01),
					&apos;HY1&apos;, Date(Year__c, 01, 01),
					&apos;HY2&apos;, Date(Year__c, 07, 01),
					&apos;Q1&apos;, Date(Year__c, 01, 01),
					&apos;Q2&apos;, Date(Year__c, 04, 01),
					&apos;Q3&apos;, Date(Year__c, 07, 01),
					&apos;Q4&apos;, Date(Year__c, 10, 01),
				    null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period Beginning</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/PeriodEnd__c.field-meta.xml
<CustomField>
    <fullName>PeriodEnd__c</fullName>
    <formula>Case(Type__c,
					&apos;Y&apos;, Date(Year__c, 12, 31),
					&apos;HY1&apos;, Date(Year__c, 06, 30),
					&apos;HY2&apos;, Date(Year__c, 12, 31),
					&apos;Q1&apos;, Date(Year__c, 03, 31),
					&apos;Q2&apos;, Date(Year__c, 06, 30),
					&apos;Q3&apos;, Date(Year__c, 09, 30),
					&apos;Q4&apos;, Date(Year__c, 12, 31),
					null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesBudget__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
                <label>Year Initial</label>
            </value>
            <value>
                <fullName>HY1</fullName>
                <label>Corrected HY1</label>
            </value>
            <value>
                <fullName>HY2</fullName>
                <label>Corrected HY2</label>
            </value>
            <value>
                <fullName>Q1</fullName>
                <label>Corrected Q1</label>
            </value>
            <value>
                <fullName>Q2</fullName>
                <label>Corrected Q2</label>
            </value>
            <value>
                <fullName>Q3</fullName>
                <label>Corrected Q3</label>
            </value>
            <value>
                <fullName>Q4</fullName>
                <label>Corrected Q4</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesBudgetRecord__c/SalesBudgetRecord__c.object-meta.xml
<CustomObject>
    <label>Sales Budget Record</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Budget Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesBudgetRecord__c/fields/SalesBudget__c.field-meta.xml
<CustomField>
    <fullName>SalesBudget__c</fullName>
    <label>Sales Budget</label>
    <referenceTo>SalesBudget__c</referenceTo>
    <relationshipLabel>Sales Budget Records</relationshipLabel>
    <relationshipName>Sales_Budget_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/SalesPlanFact__c.object-meta.xml
<CustomObject>
    <label>Sales Plan and Fact</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Record ID Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Plan and Fact</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanFact__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Budget</fullName>
                <color>#FFCC33</color>
                <label>Initial Budget</label>
            </value>
            <value>
                <fullName>Corrected Budget</fullName>
                <color>#DDDDDD</color>
                <label>Corrected Budget</label>
            </value>
            <value>
                <fullName>Actual Budget</fullName>
                <color>#78C953</color>
                <label>Budget</label>
            </value>
            <value>
                <fullName>Plan</fullName>
                <color>#AFCADF</color>
                <label>Plan</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <color>#2F5D85</color>
                <label>Open Orders</label>
            </value>
            <value>
                <fullName>Opportunity</fullName>
                <color>#419249</color>
                <label>Open Orders &amp; Opps</label>
            </value>
            <value>
                <fullName>Fact</fullName>
                <color>#2F5D85</color>
                <label>Fact</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Fact.recordType-meta.xml
<RecordType>
    <fullName>Fact</fullName>
    <active>true</active>
    <description>Actual production and sales data</description>
    <label>Fact</label>
</RecordType>

force-app/main/default/objects/SalesPlanFact__c/recordTypes/Plan.recordType-meta.xml
<RecordType>
    <fullName>Plan</fullName>
    <active>true</active>
    <description>Production and sales plan data</description>
    <label>Plan</label>
</RecordType>

force-app/main/default/classes/SalesPlanFactDeleteBatch.cls
global class SalesPlanFactDeleteBatch implements Database.Batchable<SObject>  {
	
    global Id sbrIdsSet;
    global List<Date> listDateCheck = new List<Date>();
    global dateTime lastUpdateBudget;
    //global String selectedType = 'Actual Budget';
    global String typeActualBudget = 'Actual Budget';
    global String typeCorrectedBudget = 'Corrected Budget';
    
    global SalesPlanFactDeleteBatch(Id idsSalesBudgetRecords){
    sbrIdsSet = idsSalesBudgetRecords;
    // AggregateResult[] groupedResults= [SELECT Period__c  FROM SalesBudgetRecord__c where SalesBudget__c =:idsSalesBudgetRecords group by Period__c ];
    lastUpdateBudget = [ SELECT LastModifiedDate FROM SalesBudget__c WHERE id =:idsSalesBudgetRecords LIMIT 1].LastModifiedDate.addMinutes(-10);   
        
        List<Deleted_Period__c> dlper = new List<Deleted_Period__c>();
        //check periods to delete'
        List<SalesBudget__c> budget = [SELECT id, PeriodBeginning__c, PeriodEnd__c FROM SalesBudget__c WHERE id =:idsSalesBudgetRecords LIMIT 1];
       
        Map<String,Deleted_Period__c> records = Deleted_Period__c.getAll();
        
        Date startDate = budget[0].PeriodBeginning__c;
        Date endDate = budget[0].PeriodEnd__c;
        
        // Increment the start date until it reaches the end date
        while (startDate < endDate) {
            listDateCheck.add(startDate);
            startDate = startDate.addMonths(1);
        }

        // for(AggregateResult ar:groupedResults){  
        // 	if(records.get(String.valueOf(ar.get('Period__c')))==null){
        //         listDateCheck.add(Date.valueOf(ar.get('Period__c')));               
        //     }       
        // }
        system.debug(listDateCheck);
        system.debug(lastUpdateBudget);
        Triton.instance.debug(TritonTypes.Type.Backend, 
							  TritonTypes.Area.SalesPlanFact,   
							  'Sales Plan Fact Delete debug',
							  'Period : ' + listDateCheck + '; Last Update Budget : ' + lastUpdateBudget);
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext context) {	    
        
        return Database.getQueryLocator('SELECT id FROM SalesPlanFact__c WHERE Period__c in :listDateCheck AND (Type__c =:typeActualBudget OR Type__c =:typeCorrectedBudget) AND CreatedDate<:lastUpdateBudget' );//
        //return Database.getQueryLocator('SELECT id FROM SalesPlanFact__c WHERE Period__c in :listDateCheck AND Type__c =:selectedType AND CreatedDate<:lastUpdateBudget' );
	}
    
    global void execute(Database.BatchableContext context, List<SalesPlanFact__c> scope) {
        
        delete scope;
	}
    
    global void finish(Database.BatchableContext context) {
        
	}
}