force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionnaireHandler.cls
public class QuestionnaireHandler extends TriggerHandler implements ITrigger {

    public QuestionnaireHandler(Map<Id, SObject> oldMap, Map<Id, SObject> newMap, List<SObject> oldList, List<SObject> newList) {
		super(oldMap, newMap, oldList, newList);
	}

	public void bulkBefore() {
		System.debug('bulkBefore Questionnaire');
	}
	
	public void bulkAfter() {
		System.debug('bulkAfter Questionnaire');
	}

	public void beforeInsert(SObject so) {
		System.debug('beforeInsert Questionnaire');
	}

	public void beforeUpdate(SObject oldSo, SObject so) {
		System.debug('beforeUpdate Questionnaire');
        
		Questionnaire__c oldQuestionnaire = (Questionnaire__c)oldSo;
		Questionnaire__c newQuestionnaire = (Questionnaire__c)so;

        if(oldQuestionnaire.Status__c == 'Sent') {
            newQuestionnaire.addError('Questionnaire with Sent status can not be updated.');
        }
	}

	public void beforeDelete(SObject so) {
		System.debug('beforeDelete Questionnaire');
	}

	public void afterInsert(SObject so) {
		System.debug('afterInsert Questionnaire');
	}

	public void afterUpdate(SObject oldSo, SObject so) {
		System.debug('afterUpdate Questionnaire');
	}

	public void afterDelete(SObject so) {
		System.debug('AfterDelete Questionnaire');
	}

	public void postProcessing() {
		System.debug('PostProcessing Questionnaire');
	}
}