force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionnaireHandlerTest.cls
@IsTest
public class QuestionnaireHandlerTest {
    
    @IsTest
    static void testValidationSuccess() {
        Questionnaire__c questionnaire = new Questionnaire__c(Name = 'Test Name', Status__c = 'Draft');
        insert questionnaire;

        Boolean expectedExceptionThrown = false;
        try {
            questionnaire.StartDate__c = Date.today();
            update questionnaire;
        } catch(Exception e) {
            expectedExceptionThrown = true;
        }

        Assert.isFalse(expectedExceptionThrown, 'Questionnaire should be successfully updated');
    }

    @IsTest
    static void testValidationError() {
        Questionnaire__c questionnaire = new Questionnaire__c(Name = 'Test Name', Status__c = 'Sent');
        insert questionnaire;

        Boolean expectedExceptionThrown = false;
        try {
            questionnaire.StartDate__c = Date.today();
            update questionnaire;
        } catch(Exception e) {
            expectedExceptionThrown = true;
        }

        Assert.isTrue(expectedExceptionThrown, 'Exception should be thrown');
    }
}