force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Questionaire Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SectionTriggerHandler.cls
public class SectionTriggerHandler extends TriggerHandler implements ITrigger {
    public static Map<Id, Questionnaire__c> QuestionnaireMap;

    public SectionTriggerHandler(Map<Id, SObject> oldMap, Map<Id, SObject> newMap, List<SObject> oldList, List<SObject> newList) {
		super(oldMap, newMap, oldList, newList);
	}

	public void bulkBefore() {
		System.debug('bulkBefore Section');
		if(!Trigger.isDelete) {
			getQuestionnaireMap(newList);
		}
	}
	
	public void bulkAfter() {
		System.debug('bulkAfter Section');
	}

	public void beforeInsert(SObject so) {
		System.debug('beforeInsert Section');
        checkQuestionnaireStatus(so);
	}

	public void beforeUpdate(SObject oldSo, SObject so) {
		System.debug('beforeUpdate Section');
		checkQuestionnaireStatus(so);
	}

	public void beforeDelete(SObject so) {
		System.debug('beforeDelete Section');
	}

	public void afterInsert(SObject so) {
		System.debug('afterInsert Section');
	}

	public void afterUpdate(SObject oldSo, SObject so) {
		System.debug('afterUpdate Section');
	}

	public void afterDelete(SObject so) {
		System.debug('AfterDelete Section');
	}

	public void postProcessing() {
		System.debug('PostProcessing Section');
	}

    private void getQuestionnaireMap(List<SObject> newList) {
        Set<Id> questionnaireIdSet = new Set<Id>();
        for(SObject question : newList) {
            questionnaireIdSet.add(((Section__c) question).Questionnaire__c);
        }
        QuestionnaireMap = new Map<Id, Questionnaire__c>([SELECT Id, Status__c FROM Questionnaire__c WHERE Id IN :questionnaireIdSet]);
    }

    private void checkQuestionnaireStatus(SObject so) {
        Section__c newSection = (Section__c)so;
        if(QuestionnaireMap.get(newSection.Questionnaire__c).Status__c == 'Sent') {
            newSection.addError('Section with Sent Questionnaire can not be created/updated.');
        }
    }
}