force-app/main/default/objects/ProdQuoteToOppProduct__c/ProdQuoteToOppProduct__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product For Prod. Quotes</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Production Quote Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Product For Prod. Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProdQuoteToOppProduct__c/fields/Production_Quota__c.field-meta.xml
<CustomField>
    <fullName>Production_Quota__c</fullName>
    <label>Production Quota</label>
    <referenceTo>Production_Quota__c</referenceTo>
    <relationshipName>testProdQuoteToOppProds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Production_Quota__c/Production_Quota__c.object-meta.xml
<CustomObject>
    <label>Production Quota</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Production Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Production Quotas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductionQuoteDeleteOppItemsBatchTest.cls
@IsTest
public class ProductionQuoteDeleteOppItemsBatchTest {
    @IsTest
    static void testLastActivityDate() {
        Production_Quota__c prodQuota = new Production_Quota__c();
        insert prodQuota;

        List<ProdQuoteToOppProduct__c> prodQuoteToOppProductList = new List<ProdQuoteToOppProduct__c>();
        for(Integer i = 0; i < 200; i++) {
            ProdQuoteToOppProduct__c prodQuoteToOppProduct = new ProdQuoteToOppProduct__c(Production_Quota__c = prodQuota.Id);
            prodQuoteToOppProductList.add(prodQuoteToOppProduct);
        }
        insert prodQuoteToOppProductList;

        Test.startTest();
        Id batchJobId = Database.executeBatch(new ProductionQuoteDeleteOppItemsBatch(), 200);
        Test.stopTest();

        List<ProdQuoteToOppProduct__c> newProdQuoteToOppProductList = [SELECT Id FROM ProdQuoteToOppProduct__c];

        Assert.isTrue(newProdQuoteToOppProductList.size() == 0);
    }
}